### ISSUE TITLE
Review why functional tests aren't passing in Jenkins

### ISSUE THREAD

**Issue by zgramana** [couchbase/sync_gateway#1069]

**Comment by andreibaranouski** [comment]
excluded  cbl-document.js, cbl-views.js and cbl-large-data.js tests from the run(they have known issues for android/java cblite tests and they are not related SG), all other tests have been fixed. the job is green now.

**Comment by tleyden** [comment]
@andreibaranouski can you add a link to the successful job?  Also in general I think it's best to always link to jenkins jobs from related github tickets.  Many people don't even know where to find the jenkins jobs, so that will help advertise the resources.

By the way, how long does the job take to run?
