### ISSUE TITLE
Step for increasing max number of file handles is missing the config change required.

### ISSUE THREAD

**Issue by mcpaddy** [couchbase/sync_gateway#1080]
The steps set out in the [documentation](http://developer.couchbase.com/mobile/develop/guides/sync-gateway/os-level-tuning/max-file-descriptors/index.html) to increase the max number of open file handle are miss an important step.  The Sync-gateway configuration file needs to be update otherwise it defaults to a maximum of [5000](https://github.com/couchbase/sync_gateway/blob/c989442a8a5f14740e47ffcc5b089ba36676fa2b/src/github.com/couchbase/sync_gateway/rest/config.go#L45).

**Comment by adamcfraser** [comment]
@tleyden Do customers actually need to follow the additional steps in that documentation if they set the sync gateway config property, or does setting the SG property accomplish the same thing?

**Comment by tleyden** [comment]
@adamcfraser yeah, pretty sure they do.  Especially the `fs.file-max` property, in the sense that would be a hard ceiling.  (if it was set to 5K and you tried to set sync gateway config to 50K, wouldn't work)

Also, if the sync gateway is running as non-root and the default ulimit was X, your sync gateway config would not be able to set it higher than X.

I'm thinking in @mcpaddy's case, the Sync Gateway actually _lowered_ the max no files from the default it would have otherwise been, which makes me think that by default, maybe it should do _nothing_.

**Comment by adamcfraser** [comment]
@tleyden That's what I was trying to figure out - if instead of updating the docs, we should check the existing limits.Cur here to ensure we don't decrease the value:
https://github.com/couchbase/sync_gateway/blob/34dbbae5623680e887711860ebe5ee06e6610f4f/src/github.com/couchbase/sync_gateway/base/rlimit.go#L15

That's assuming there isn't a scenario where we'd actually want to use the SG property to reduce the number of file handles available.

**Comment by mcpaddy** [comment]
We still need to update the docs for older versions.

**Comment by adamcfraser** [comment]
Fair point @mcpaddy - assigned this to Jeff for the docs update, and filed #1083 for the potential enhancement.

**Comment by JeffThomasWriter** [comment]
From the discussion above, I am not clear what to write. I am also not clear about the procedure for updating prior versions of docs.

**Comment by adamcfraser** [comment]
@jamiltz This documentation (http://developer.couchbase.com/documentation/mobile/current/develop/guides/sync-gateway/os-level-tuning/max-file-descriptors/index.html) is missing the step about configuring the maxFileDescriptors property in the SG config (documented elsewhere here: http://developer.couchbase.com/documentation/mobile/1.3/develop/guides/sync-gateway/config-properties/index.html).
