### ISSUE TITLE
[Distributed index] DCP rollback errors

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1129]
Not sure how to reproduce this, but I'm on commit 2c4e743a76725a8a7a7e4fea736ff520fff3d93d and when I start my Sync Gateway, I'm getting these errors:

https://gist.github.com/tleyden/0cc4651da071d39235a2

I don't think it's related to a recent commit, I think it's more related to the state of the system.

**Comment by tleyden** [comment]
Notes to self:
- [set lastSeq: 4 for vbucket 57](https://gist.github.com/tleyden/0f1ab2c887cc1b7926bb#file-gistfile1-txt-L1)
- [process rollback request to set lastSeq to 0 for vbucket 57](https://gist.github.com/tleyden/0f1ab2c887cc1b7926bb#file-gistfile1-txt-L5)
- [returns lastSeq: 0 for vbucket 57 -- expected](https://gist.github.com/tleyden/0f1ab2c887cc1b7926bb#file-gistfile1-txt-L6)
- [returns lastSeq: 4 for vbucket 57 -- why!?](https://gist.github.com/tleyden/0f1ab2c887cc1b7926bb#file-gistfile1-txt-L14)

**Comment by tleyden** [comment]
I think I found the problem.  It appears that within the _same_ Sync Gateway instance, there are _multiple_ pindexes listening to the same dcp shard.  Eg, there are "old residue pindexes" that are causing issues.

From logs:

```
2015/09/14 15:39:45 OpaqueGet(): returning value:  with lastSeq: 0 for partition: 57.  pindex: 0xc20816c3c0
2015/09/14 15:39:45 OpaqueGet(): returning value:  with lastSeq: 0 for partition: 57.  pindex: 0xc2080ca600
```

Here is the [cbgt cfg json](https://gist.github.com/tleyden/99ef592bcdf0ba348612)

**Comment by steveyen** [comment]
Hi Traun, from looking at the cfg (https://gist.github.com/tleyden/99ef592bcdf0ba348612)...

I see that you have 2 indexes defined...
- bucket-2 (data-source is bucket "bucket-2")
- bucket-2e8328ddd84d1020bd82d72ebf09b05e3 (data-source is bucket "bucket-2")

So, of those indexes have the same bucket data source.

cbgt creates DCP streams per index.

So, let's say that you have 1 CB node, and 1 sync-gw node.  And 2 indexes.

Then I would expect that 1 sync-gw node to create 2 DCP streams to the 1 CB node (because of the 2 indexes).

One way you can confirm is to improve the logging that you copy-&-pasted above to show the pindex Name.  The pindex pointer values that you're already logging are showing two different pindexes, but this may be helpful to confirm what's going on.

**Comment by tleyden** [comment]
Example error message:

```
2015/09/15 16:33:13 CBGT contains an invalid index name: bucket-2.  Aborting. Valid index names: map[bucket-2e8328ddd84d1020bd82d72ebf09b05e3:n/a]
```

**Comment by tleyden** [comment]
Was not able to reproduce after clearing out cbgt state files and buckets.  Once #1136 is merged, this can be closed.
