### ISSUE TITLE
[Distributed index] 500 Internal error: Stored hash not found for sequence [3], returning zero clock

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1159]
During a gateload perfrun, I'm seeing [these errors](https://gist.github.com/tleyden/cc73c9363955c401b23f#file-gistfile1-txt-L16) in the Sync Gateway logs:

```
2015-09-22T01:21:47.699Z HTTP: #3501:     --> 500 Internal error: Stored hash not found for sequence [3], returning zero clock  (1.3 ms)
```

They seem to be critical, as they are making it back to the gateload client:

```
2015/09/22 01:23:51 #14417:   <-- HTTP error:500 (2562047h47m16.854775807s)
2015/09/22 01:23:51 WARNING: HTTP error: 500 Internal Server Error for http://10.155.22.205:4984/db/_changes?feed=continuous&heartbeat=300000&style=all_docs&since=3&n=14418
```

I didn't notice these on a previous run against the `feature/distributed_index` branch.

**Comment by tleyden** [comment]
Sequence hashes are never stored, and so `handleChanges()` is returning early because of this check:

```
        if options.Since, err = h.db.ParseSequenceID(h.getQuery("since")); err != nil {
            log.Printf("handleChanges return err1: %v", err)
            return err
        }
```

because `h.db.ParseSequenceID` will return an error if it can't lookup the hash for the `since` value.  It always fails since no sequence hashes are ever stored in the bucket.

**Why aren't sequence hashes ever stored?**

Sequence hashes are stored by calling `sequenceHash.GetHash()`, and the main place that seems to be being called is from the goroutine spawned in `database.VectorMultiChangesFeed()`, however that is never called because it only happens _lower_ down in the `handleChanges()` method:  

```
    switch feed {
    case "normal", "":
        return h.sendSimpleChanges(userChannels, options)
    case "longpoll":
        options.Wait = true
        return h.sendSimpleChanges(userChannels, options)
    case "continuous":
        return h.sendContinuousChangesByHTTP(userChannels, options)
    }
```

in both `sendSimpleChanges()` and `sendContinuousChangesByHTTP()` the following call is present:

```
    feed, err := h.db.MultiChangesFeed(channels, options)
```

but this is never called due to the early return mentioned above.

**Comment by adamcfraser** [comment]
What we need to work out is where gateload is getting the '3' value it's sending as the since value.  That looks like an integer sequence value (not a hashed value).  Do we have any gateload logging for the client that sent this sequence?

**Comment by tleyden** [comment]
I think I see what’s going on in gateload .. it’s a race between the different client goroutines:

https://gist.github.com/tleyden/4fffb3ba9f406dfe3c92

the first ones to start up get committed_update_seq:0 and immediately start writing docs, while the later ones get committed_update_seq:1 and then blow up

let me see if I can just hardcode that to 0 and fix it.

**Comment by tleyden** [comment]
Fixed via https://github.com/couchbase/sync_gateway/issues/1166

**Comment by ArihantRk** [comment]
@tleyden @adamcfraser i am just trying out upgrade of couchbase data which was written without using sg-accelerator  and also i don't want to loose the data.  i could see data is being inserted into source cluster but not into destination cluster(via sg-replication).
i just want to upgrade and continue with existing data. i could see that **replication is stopped** after up-gradation to sg-accelerator and seeing below messages.


**access.log**
09:57:47.557535 2017-04-26T09:57:47.557-05:00 Replicate+: Got notification CATCHING_UP
09:57:47.559328 2017-04-26T09:57:47.559-05:00 HTTP:  #5072: GET /ptxdata/_changes?feed=normal&limit=1000&heartbeat=30000&style=all_docs&since=106&filter=sync_gateway/bychannel&channels=*  (ADMIN)
09:57:47.559741 2017-04-26T09:57:47.559-05:00 Bucket: GetAndTouchRaw("_sequence:106") [303.365µs]
09:57:47.559757 2017-04-26T09:57:47.559-05:00 Changes+: Stored hash not found for sequence [106] collision index [0], #storedClocks:0
09:57:47.559806 2017-04-26T09:57:47.559-05:00 HTTP: #5072:     --> 500 Internal error: Stored hash not found for sequence [106], returning zero clock  (0.5 ms)

**error.log**

2017/04/26 10:06:53 ^[[33mReplicate: ^[[0msequenceNumberToString called with: 106 type: string
2017/04/26 10:06:53 ^[[33mReplicate: ^[[0msequence is a string
2017/04/26 10:06:53 ^[[33mReplicate: ^[[0msequenceNumberToString called with: 106 type: string
2017/04/26 10:06:53 ^[[33mReplicate: ^[[0msequence is a string
2017/04/26 10:06:53 ^[[33mReplicate: ^[[0m[ptxdata_C1_C2] changes feed resp: &{500 Internal Server Error 500 HTTP/1.1 1 1 map[Date:[Wed, 26 Apr 2017 15:06:53 GMT] Content-Length:[123] Content-Type:[application/json] Server:[Couchbase Sync Gateway/1.4.0]] 0xc420229300 123 [] false false map[] 0xc42062b950 <nil>}, err: <nil>
2017/04/26 10:06:53 ^[[33mReplicate: ^[[0m[ptxdata_C1_C2] Error getting changes feed.  Resp: &{500 Internal Server Error 500 HTTP/1.1 1 1 map[Content-Length:[123] Content-Type:[application/json] Server:[Couchbase Sync Gateway/1.4.0] Date:[Wed, 26 Apr 2017 15:06:53 GMT]] 0xc420229300 123 [] false false map[] 0xc42062b950 <nil>}
2017/04/26 10:06:53 ^[[33mReplicate: ^[[0m[ptxdata_C1_C2] channel: 0xc42098aea0
2017/04/26 10:06:53 ^[[33mReplicate: ^[[0m[ptxdata_C1_C2] stateFnActiveFetchChangesFeed got event: {FETCH_CHANGES_FEED_FAILED <nil>}
2017/04/26 10:06:53 ^[[33mReplicate: ^[[0m[ptxdata_C1_C2] new state: <nil>
2017/04/26 10:06:53 ^[[33mReplicate: ^[[0m[ptxdata_C1_C2] processEvents() is done
2017/04/26 10:06:53 ^[[33mReplicate: ^[[0m[ptxdata_C1_C2] Replication aborted .. try again
2017/04/26 10:06:53 ^[[33mReplicate: ^[[0m[ptxdata_C1_C2] continuous repl new state: 0x6e5b00
2017/04/26 10:06:53 ^[[33mReplicate: ^[[0m[ptxdata_C1_C2] continuous repl state: 0x6e5b00
2017/04/26 10:06:53 ^[[33mReplicate: ^[[0m[ptxdata_C1_C2] entered stateFnBackoffRertry



19:54:54.435715 2017-04-26T19:54:54.435-05:00 WARNING: MultiChangesFeed got error reading stable sequence: Error: Unable to retrieve index partition map, but index counter exists -- db.(*Database).VectorMultiChangesFeed.func1() at index_changes.go:93

SetUp:
3*CBS,1*SYNCGW, 1*SyncgwRep on both clusters and replication via sg-replicator
Steps:
1. insert some data using above setup without accelerator
2. Bring in sg-accelerator on each of cluster with basic config
3. insert and update some existing data to source cluster
