### ISSUE TITLE
Create sysv-init script for CentOS 5

### ISSUE THREAD

**Issue by zgramana** [couchbase/sync_gateway#1204]
Use the Couchbase Server script as the template.

**Comment by ajres** [comment]
There was a sysv_init script delivered previously but was removed as CentOS 5 was no longer a supported target for release builds.

The script and installer code were reinstated and tested on Centos5 / Amazon Linux.

Implementation deviates from the Couchbase Server script because SG can not be daemonized as it is a gloang built executable.

There is a separate ticket #1246 raised to cover the daemonize issue.

Fix has been merged to a branch off master and PR #1249 has been raised.

Closing this ticket.
