### ISSUE TITLE
Auto-expire unused _local checkpoint documents 

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#1280]
Sync Gateway doesn't currently set an expiry for _local documents.  This can result in an accumulation of obsolete replication checkpoint documents in the bucket.  

We can modify the _local document storage to:
(a) Set a relatively long expiry time on creation
(b) Update the expiry (GetAndTouch) when the checkpoint document is retrieved.

Clients that don't replicate within the expiry window will be forced to restart their replication from zero.  

The expiry value could default to something like 90 days, but probably makes sense as a config setting to let customers tune it to their use case.

**Comment by adamcfraser** [comment]
Should be a user-configurable setting.

**Comment by Fujio-Turner** [comment]
@adamcfraser ,
There are customers with pre-existing deployments of SG/CB that need to apply their pre-existing checkpoints with the new TTL.
Could we have in the _resync process an optional flag that also updates the checkpoints with the new ,non-Zero, TTL.  

I say optional flag because there are some customers with millions of checkpoints that might need an independent script ,to change the TTL, to speed up the process.

**Comment by adamcfraser** [comment]
@Fujio-Turner I think that migration tool would have to get handled as a separate enhancement, and as you say may make more sense as a non-integrated tool.
