### ISSUE TITLE
Recover from gocb timeouts and queue overflow

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#1289]
Currently we're treating gocb timeouts and queue overflow errors as fatal in several scenarios.  Instead, we should have backoff/retry handling in place for critical operations, and warnings for non-critical operations.

**Comment by adamcfraser** [comment]
Include expvar output for timeouts and overflow counts.

**Comment by tleyden** [comment]
Setting on couchbasebucket_gocb for retry handling.

Any method that has the potential to timeout / queue overflow error from gocb.

**Comment by tleyden** [comment]
I filed a [gocb jira ticket](https://issues.couchbase.com/browse/GOCBC-75) to improve the GoCB error handling.

**Comment by tleyden** [comment]
Jenkins job unit tests passing:

http://mobile.jenkins.couchbase.com/view/Sync_Gateway_Dev/job/sync-gateway-dev-build/376

**Comment by tleyden** [comment]
Functional tests are giving the same results as the distributed_index branch:

http://qa.sc.couchbase.com/view/mobile/job/centos-syncgateway-functional-tests-distributed-index/101/#showFailuresLink

```
Test Result (4 failures / -8)
functional_tests.test_dcp_reshard.test_dcp_reshard_sync_gateway_goes_down
functional_tests.test_roles.test_roles_sanity
functional_tests.test_sync.test_sync_sanity
functional_tests.test_sync.test_sync_sanity_backfill
```

**Comment by tleyden** [comment]
While trying to run performance tests, I'm seeing the non-writer Sync Gateway node crash with these logs: https://gist.github.com/tleyden/c513f8a02d2c568db1ca  

Not sure if that error is specific to the feature/distributed_index_1289_gocb_timeouts branch or is also happening on the distributed_index branch.

**Comment by tleyden** [comment]
Performance test results for feature/distributed_index_1289_gocb_timeouts branch:

https://gist.github.com/tleyden/c98c7e1ce934939902c4  (1.12 seconds PushToSubscriberInteractive P95)

Tests run via:

```
$ python provision/install_sync_gateway.py --branch=feature/distributed_index_1289_gocb_timeouts
$ python performance_tests/run_tests.py --number-pullers 1000 --number-pushers 1000 --use-gateload --gen-gateload-config --reset-sync-gw
```

See https://github.com/couchbaselabs/sync-gateway-testcluster README for setup info.

Provisioning config:

```
[sync_gateways]
sg1 ansible_ssh_host=ec2-152-50.compute-1.amazonaws.com
sg2 ansible_ssh_host=ec2-154-211.compute-1.amazonaws.com
sg3 ansible_ssh_host=ec2-245-134.compute-1.amazonaws.com

[sync_gateway_index_writers]
sg1 ansible_ssh_host=ec2-152-50.compute-1.amazonaws.com
sg2 ansible_ssh_host=ec2-154-211.compute-1.amazonaws.com
sg3 ansible_ssh_host=ec2-245-134.compute-1.amazonaws.com

[couchbase_servers]
cb1 ansible_ssh_host=ec2-226-13.compute-1.amazonaws.com
cb2 ansible_ssh_host=ec2-157-105.compute-1.amazonaws.com
cb3 ansible_ssh_host=ec2-186-14.compute-1.amazonaws.com

[load_generators]
lg1 ansible_ssh_host=ec2-83-247.compute-1.amazonaws.com
lg2 ansible_ssh_host=ec2-136-232.compute-1.amazonaws.com
```

Sync Gateway config:

https://gist.github.com/tleyden/884e645a0b56e27a5b24

Gateload config: 

https://gist.github.com/tleyden/2409a465f04e697a61e5

**Comment by tleyden** [comment]
Performance test results for feature/distributed_index:

https://gist.github.com/tleyden/1bfed8285090dfe7dbe0 (1.18 seconds PushToSubscriberInteractive P95)

Everything else was the same as the previous comment

**Comment by tleyden** [comment]
The functional tests might be showing some regressions:

http://qa.sc.couchbase.com/view/mobile/job/centos-syncgateway-functional-tests-distributed-index/134/console

Still digging into this

**Comment by tleyden** [comment]
I just ran one of the ones that failed against my aws func test cluster, and it passed.

```
python provision/install_sync_gateway.py --branch=feature/distributed_index_1289_gocb_timeouts && python -m pytest --capture=no functional_tests/test_users_channels.py::test_single_user_single_channel
```

Output: 

https://gist.github.com/tleyden/0a590533a210f05f1519

**Comment by tleyden** [comment]
Re-running the functional tests worked:

http://qa.sc.couchbase.com/view/mobile/job/centos-syncgateway-functional-tests-distributed-index/136/#showFailuresLink

**Comment by tleyden** [comment]
One more re-run, also worked:

http://qa.sc.couchbase.com/view/mobile/job/centos-syncgateway-functional-tests-distributed-index/137/#showFailuresLink

Looks like func test run 134 was an anomaly.

**Comment by sethrosetter** [comment]
I may have reproduced the intermittent failures with a run I kicked off last Friday (http://qa.sc.couchbase.com/view/mobile/job/centos-syncgateway-functional-tests-distributed-index/144/) I was able to capture the logs https://s3.amazonaws.com/sync-gateway-logs/job_144.tar

**Comment by tleyden** [comment]
@adamcfraser here are the logs for one of the sync gateways in the case where the test failed:

https://gist.github.com/tleyden/ba35e84b388ae10c3dc7#file-gistfile1-txt-L4227-L4235

I'm not sure if these errors are happening on the `distributed_index` branch, but do they look like errors that could cause functionality problems?

**Comment by tleyden** [comment]
Running the `functional_tests/test_multiple_dbs.py::test_multiple_db_unique_data_bucket_unique_index_bucket` test 10 times in a loop reproduced a failure in [func test run 161](http://qa.sc.couchbase.com/view/mobile/job/centos-syncgateway-functional-tests-distributed-index/161/console)

The test verification error is:

```
 -> |bulk_db_user_1| expected (num_docs: 1000 num_revisions: 0) _changes (num_docs: 523 updates: 0)
```

Grepping the sync gateway logs for "error" is showing logs mainly like this:

```
172.23.106.195/sync_gateway_error.log:2015-12-09T16:45:48.785-08:00 WARNING: Error writing sharded clock partition [%!d(string=_idx_c:_idx_stableSeq:clock-61)]:Key already exists. -- base.func·043() at sharded_sequence_clock.go:131
172.23.106.195/sync_gateway_error.log:2015-12-09T16:45:48.785-08:00 WARNING: Error writing sharded clock partition [%!d(string=_idx_c:_idx_stableSeq:clock-12)]:Key already exists. -- base.func·043() at sharded_sequence_clock.go:131
172.23.106.195/sync_gateway_error.log:2015-12-09T16:45:48.789-08:00 WARNING: Error writing sharded clock partition [%!d(string=_idx_c:_idx_stableSeq:clock-61)]:Key already exists. -- base.func·043() at sharded_sequence_clock.go:131
```

Which is the same error that was seen earlier in https://github.com/couchbase/sync_gateway/issues/1289#issuecomment-163046748.

The sync gateways are also returning a different number of changes for the changes feeds!

```
$ curl http://bulk_db_user_1:password@172.23.106.186:4984/db/_changes | wc -l
526
$ curl http://bulk_db_user_1:password@172.23.106.195:4984/db/_changes | wc -l
526
$ curl http://bulk_db_user_1:password@172.23.107.80:4984/db/_changes | wc -l
475 
```

(I lost the exact output, so the above is just an approximation)

**Comment by tleyden** [comment]
Theory regarding cause of `WARNING: Error writing sharded clock partition`:
- When gocb returns a timeout error, then the update will still happen
- The code will retry, but since the update from previous step will have happened, then it will get a CAS error which is returned to the caller.
- The calling code does not currently retry on a CAS failure, and just logs an error and gives up at this point (there's an issue logged for this here: https://github.com/couchbase/sync_gateway/issues/1339)

@adamcfraser I realized after our call that no retries are apparently happening -- I had added a [warning message](https://github.com/couchbase/sync_gateway/blob/feature/distributed_index_1289_gocb_timeouts/src/github.com/couchbase/sync_gateway/base/util.go#L274) every time the RetryLoop needed to retry, and there was nothing in the [logs from that failed run](http://sync-gateway-logs.s3.amazonaws.com/test_multiple_dbs.py-test_multiple_db_unique_data_bucket_unique_index_bucket-2015-12-09-16-42-50-sglogs.zip) with that retry warning.   Also, I verified that [build 435](http://mobile.jenkins.couchbase.com/view/Sync_Gateway_Dev/job/sync-gateway-dev-build/435/console) contained that commit.

**Comment by tleyden** [comment]
I think I found an issue -- the retry mechanism is not kicking in!  That explains why there are no retries observed in the logs, and also explains why this failure is only seen sporadically.  (only when gocb timeouts or queue overflows happen)

I modified the gocb timeout to be 5 ms, and despite seeing messages like `2015-12-10T12:17:30.506-08:00 WARNING: Error writing sharded clock partition key: _idx_c:_idx_stableSeq:clock-25.  Error: The operation has timed out., p.cas: 442385722358296, casOut: 0 -- base.(*ShardedClock).Write.func1() at sharded_sequence_clock.go:131`, I'm not seeing any logs related to retries.

What's happening is that in the worker:

```
            newCas, err := bucket.Bucket.Insert(k, v, uint32(exp))
            shouldRetry = shouldRetryGoCBOp(err)
            return shouldRetry, err, uint64(newCas)
```

where `err` contains the timeout error.

And in the `RetryLoop`:

```
    for {
        shouldRetry, err, value := worker()
        if err != nil {
            log.Printf("RetryLoop got error from worker: %v", err)
            return err, nil
        }

        if !shouldRetry {
            return nil, value
        }
```

The err is causing it to abort without retrying.

**Comment by tleyden** [comment]
After fixing the retry mechanism, I'm able to reproduce the error by setting the Gocb timeout to 5 ms and running the functional test against my local Sync Gw / CB Server.  

I added tracing for a particular sharded clock key (_idx_c:_idx_stableSeq:clock-20).   Here's the sequence of events as seen in the logs:
- [Timeout error and retry](https://gist.github.com/tleyden/c9b5169da61f2008fe4e#file-gistfile1-txt-L59-L60)
- Not shown in logs, but presumably the operation succeeds, despite the timeout.  It timed out for being in the gocb queue for too long, but the op remained in the queue and eventually succeeded.
- [Worker is called back after retry delay](https://gist.github.com/tleyden/c9b5169da61f2008fe4e#file-gistfile1-txt-L61-L62)
- [Cas failure, since it's using a stale cas value](https://gist.github.com/tleyden/c9b5169da61f2008fe4e#file-gistfile1-txt-L63-L64)
- The calling code does not currently retry on a CAS failure, and just logs an error and gives up at this point (there's an issue logged for this here: https://github.com/couchbase/sync_gateway/issues/1339)

**Comment by tleyden** [comment]
After rebasing this branch off of https://github.com/couchbase/sync_gateway/pull/1348, I'm no longer seeing any 

```
WARNING: Error writing sharded clock partition key
```

messages in the logs when running `python -m pytest --capture=no functional_tests/test_users_channels.py::test_single_user_multiple_channels` with the gocb timeout set to 5ms.  

Full SG logs: https://gist.github.com/tleyden/ea48e39cc3b55fe35d16

**Comment by tleyden** [comment]
After rebasing off of https://github.com/couchbase/sync_gateway/pull/1330, I kicked off a functional test:

http://qa.sc.couchbase.com/view/mobile/job/centos-syncgateway-functional-tests-distributed-index/168/

**Comment by tleyden** [comment]
I'm considering [func test 168](http://qa.sc.couchbase.com/view/mobile/job/centos-syncgateway-functional-tests-distributed-index/168/) a pass, since [func test 169](http://qa.sc.couchbase.com/view/mobile/job/centos-syncgateway-functional-tests-distributed-index/169/) against `feature/distributed_index` had the same results.

**Comment by tleyden** [comment]
I ran the performance tests and got these results:

https://gist.github.com/tleyden/67f1fd777f8ca5ff8e77

PushToSubscriberInteractive p95 was 1.16 seconds.

One caveat: only one gateload process seemed to be running

**Comment by tleyden** [comment]
Re-ran the performance tests with:
- 3 Sync Gateways total
  - 1 Sync Gateway Index Writer
  - 2 Sync Gateway non Index Writers
- 2 gateloads, pointed at the non Index Writers

PushToSubscriberInteractive p95 was 1.18 seconds

Full expvars: https://gist.github.com/tleyden/51e927da0dd055ef5eb9
