### ISSUE TITLE
(CORS) PouchDB basic auth does not work with sync gateway 

### ISSUE THREAD

**Issue by antoniusostermann** [couchbase/sync_gateway#1306]
(Sync-Gateway [Ubuntu 14.10]: 1.1.0-28, pouch: 5.1.0, pouch-authentication: 0.4.2, couchbase: 3.0.1-1444-rel)

Hey,

since I think this is a pretty common issue (and will become even more common in future with increasing hybrid app development), I create a new issue for this.

In https://github.com/couchbase/sync_gateway/issues/115, it is stated:

> OK I've blocked all login / logout on CORS requests 

does this mean combining PouchDB with https://github.com/nolanlawson/pouchdb-authentication to authenticate with sync gateway via basic auth wouldn't work? I am trying this currently, but I'm getting a 404 on  an `OPTIONS /_session` request. My sync gateway is configured for CORS like you described it:

``` js
   "CORS": {
    "Origin": ["http://localhost:8100"],
    "LoginOrigin": ["http://localhost:8100"],
    "Headers": ["Content-Type", "Accept", "Authorization", "Origin", "Referer","X-CSRF-Token"],
    "MaxAge": 17280000
   },
```

and I already tried different versions of connecting to it with pouchdb:

``` js
var remote = new PouchDB('http://'+user_id+':'+user_password+'@my-ip:4984/sync_gateway', {skipSetup: true});
    remote.login(user_id, user_password, function (err, response) {
      console.log("Login error occured");
      console.log(err);
      console.log(response);
    });
    var local = new PouchDB('db-synced');
    local.sync(remote, {live: true, retry: true}).on('error', console.log.bind(console));
```

gives me 404 on `OPTIONS /_session`, a 404 on a `GET _local/...` but also 200 for the `GET _changes` and `OPTIONS _changes` pulling.

``` js
var ajaxOpts = {
      ajax: {
        headers: {
          Authorization: 'Basic ' + window.btoa(user_id + ':' + user_password)
        }
      }
    };
    var remote = new PouchDB('http://my-ip:4984/sync_gateway', {skipSetup: true});
    var local = new PouchDB('db-synced');
    remote.login(user_id, user_password, ajaxOpts, function (err, response) {
      console.log("Login error occured");
      console.log(err);
      console.log(response);
    }).then(function(){
      console.log("in then function");
      local.sync(remote, {live: true, retry: true}).on('error', console.log.bind(console));
    });
```

Only gives me the 404 on `OPTIONS  /session`, `then`-function is not executed.

In both ways, my browser tells me that CORS-requests for _sessions are blocked. This is also stated by the error object catched in the above error function, although I find all headers I set in the `config.json` even in the response of the `OPTIONS`-request. There is also an `ACCESS-CONTROL-ALLOW-CREDENTIALS: true` header entry.

After hours of searching, I found https://github.com/couchbase/sync_gateway/issues/115. Is this anywhere related to my problem? Is basic auth like I am doing it with Ionic/PouchDB not possible with sync gateway?

**Comment by jamesnocentini** [comment]
Correct, the pouchdb-authentication plugin won't work. This forum thread should help you get the `/{db}/_session endpoint working https://forums.couchbase.com/t/user-authentication-plugin-for-pouchdb-work-with-sync-gateway/5174

**Comment by jchris** [comment]
@jamiltz you've done the research to reply to the forum thread and write the reverse-proxy blog post. Obviously some use cases will need the flexibility that comes with that approach, but I'm thinking we should be able to include all this in Sync Gateway, with config to activate it, so that common use cases like PouchDB support work out of the box.

Things like our login URL being `/foo/_session` instead of `/_session` mean maybe we need a config like `"root_session_database" : "foo"` that developers could use to work with clients that expect server-wide session resources. (Eg it would make `/_session` act like `/foo/_session`)

Maybe you can help me stand up a test environment? I probably won't be able to dig deep for a while though...

**Comment by antoniusostermann** [comment]
Thanks for your information so far! Based on your hints, I tried changing the pouchdb authenticator (instead of using a reverse proxy) and inserted my database name into the url: https://github.com/nolanlawson/pouchdb-authentication/blob/master/dist/pouchdb.authentication.js#L205

Now the login requests are going to `/db/_session` and it seems to work basically. But what confuses me is the overflow (many per second) of requests (`POST` and `OPTIONS` of `_changes` and `revs_diff`), like shown in the screenshot.

![request overflow](https://cloud.githubusercontent.com/assets/2332002/11401682/0b838244-9394-11e5-80fe-f8e459c8ddff.png)
(tested in ff)

Shouldn't sync gateway use long polling? Is this normal or do the changes mentioned above result in this behaviour?

Edit: In Chrome browser there is no such behaviour

**Comment by jamesnocentini** [comment]
@Canifex So, to understand correctly, you just changed that line to be `return getBaseUrl(db) + '/{db}/_session';` and it worked? The request overflow may be due to [this issue](https://github.com/pouchdb/pouchdb/issues/4602). Try with PouchDB 4.x to see if it makes any difference.

@jchris Ok I'll put together a simple test project and upload it here. Or should I look into adding a unit test in SG to show that behaviour?

**Comment by adamcfraser** [comment]
Closing based on age - could be revisited based on support cases.
