### ISSUE TITLE
[DB Online / Offline] sync_gateway fails to launch intermittently because it is not yet online

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#1336]
When creating a user via sync function, sync_gateway fails to launch intermittently because it is not yet online. It looks like the view are not being initialized in the bucket. 

https://gist.github.com/sethrosetter/31f4315e35c294768231#file-172-23-122-251-log-L18-L19

Attached are the logs of 3 sync_gateway launching in parallel with the same config:

```
{
    "interface":":4984",
    "adminInterface": "0.0.0.0:4985",
    "maxIncomingConnections": 0,
    "maxCouchbaseConnections": 16,
    "maxFileDescriptors": 90000,
    "slowServerCallWarningThreshold": 500,
    "compressResponses": true,
    "log":["*"],
    "verbose":"true",
    "databases":{
        "db":{
            "offline":true,
            "server":"http://{{ couchbase_server_primary_node }}:8091",
            "bucket":"data-bucket",
            "users": { "seth": { "password": "password", "admin_channels": ["*", "ABC"] } }
        }
    }
}
```

One sync_gateway succeeds and the other 2 fail to launch.

**Comment by sethrosetter** [comment]
I saw this again today using Couchbase Sync Gateway/1.2.0(4;cd848bd) using a slightly different config.

https://gist.github.com/sethrosetter/60ac18541092a2d4fb11#file-172-23-122-251-log-L21-L22

```
{
    "interface":":4984",
    "adminInterface": "0.0.0.0:4985",
    "maxIncomingConnections": 0,
    "maxCouchbaseConnections": 16,
    "maxFileDescriptors": 90000,
    "slowServerCallWarningThreshold": 500,
    "compressResponses": true,
    "log":["*"],
    "verbose":"true",
    "cluster_config": {
        "server":"http://XXX.XX.XXX.XXX:8091",
        "data_dir":".",
        "bucket":"data-bucket"
    },
    "databases":{
        "db":{
            "feed_type":"DCPSHARD",
            "feed_params":{
                "num_shards":64
            },
            "server":"http://http://XXX.XX.XXX.XXX:8091",
            "bucket":"data-bucket",
            "users":{
                "GUEST":{
                    "disabled":true,
                    "admin_channels":[
                        "*"
                    ]
                }
            },
            "channel_index":{
                "server":"http://http://XXX.XX.XXX.XXX:8091",
                "bucket":"index-bucket",
                "writer":true
            }
        }
    }
}
```

**Comment by ajres** [comment]
This looks like a race condition on first startup of an SG cluster, the SG views in CBS are created by PUT'ing a JSON design document to the CBS cluster using a request like:

```
curl -X PUT
    -H 'Content-Type: application/json'
    http://user:password@10.5.2.117:8092/bucket/_design/sync_gateway
    -d @byfield.ddoc
```

It is likely that it takes measurable time between the views being registered and the view indexes being built and the views being query-able.

In a cluster it's possible that if SG instances start simultaneously, then one instance created the design docs and the other instances fail to create the design docs (because they are registered in CBS) and try to use the associated views immediately which are still being built, the resulting user creation from the SG config on the additional nodes fails because the view query fails.

When starting a test SG cluster are all instances launched concurrently? It might be better to launch the first instance, then after a delay launch all additional instances?

Alternatively we could add retry logic when querying views for initial user creation to handle this case.
