### ISSUE TITLE
Doc: Duplicate docs returned to longpoll _changes request

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#1353]
Using Couchbase Sync Gateway/1.2.0(4;cd848bd)

I'm not totally sure this is invalid behavior but it seems strange. I am doing POST bulk_doc of 1000 docs every 1 sec in a loop. I am listening to the _changes response using a long poll. I am getting duplicate doc entry returned in the _changes response. 

Below is a gist listing all the duplicates that were found on the _changes request. I am working on an automated scenario.

https://gist.github.com/sethrosetter/e94bd0cf6dceb0210869

**Comment by adamcfraser** [comment]
Yes, that's an unexpected result.  I'll need more information about what exactly you're doing to create the scenario that reproduces this issue, though, including:
1. Are the 1000 docs/second all inserts?
2. What's the channel assignment in this test?
3. Do you get the same duplicates on a subsequent identical _changes request?
4. If it's straightforward to run the same test against 1.1.1, do you see the same behaviour there?
5. What's your sync function for this test?  Any access grants happening?
6. I've seen something similar when using curl, when I accidentally had two simultaneous _changes requests running.  Can we safely rule out that this is the case here?

**Comment by adamcfraser** [comment]
From the results it looks like you're getting a duplicate of every sequence from 4 to 502, then only one of each from 502 to 1002.  Since the size of the in-memory channel cache is 500 by default, this could be an issue where view-based backfill is returning duplicates.

I'm wondering if there's a duplication in view retrieval around the use of the `*` channel.  Are you explicitly assigning the documents to the `*` channel in the doc/sync function, or relying on the automatic channeling done by Sync Gateway?

**Comment by adamcfraser** [comment]
Per @sethrosetter, the documents were explicitly being assigned to the `*` channel, in addition to the automatic assignment that's done by Sync Gateway.  The fix from a client/test perspective would be to allow the normal auto-assignment to `*` by Sync Gateway.

The view could be enhanced to only emit once for the `*` channel, even if it's present in the channels metadata, but my feeling is that this scenario doesn't merit the additional complexity in the view.

**Comment by adamcfraser** [comment]
Looks like the same root cause as #1384 - should get reviewed once that is fixed.

**Comment by sethrosetter** [comment]
@adamcfraser Is this fixed and needs verification? If so, reassign me.

**Comment by adamcfraser** [comment]
@sethrosetter This was a result of the Sync Function assigning the star channel to a document.  At the time it didn't merit a code fix (partly because the code fix had potential for performance overhead).  

We should at minimum update the documentation on the \* channel to advise that manually assigning to the \* channel can result in duplication on the changes feed (which I think is why the docs tag was added).

**Comment by jamesnocentini** [comment]
Understood, I'm not sure what's the use case for calling `channel("*")`. If there isn't one we should warn against it in the docs.

Access on the other hand might be worth some clarification. Does calling `access("*")` in the sync function grant a user to all documents in the SG database?

**Comment by adamcfraser** [comment]
Agreed - there's no use case for `channel("*")`, but `access("*")` is valid.

**Comment by jamesnocentini** [comment]
Ok, this has been clarified in the docs in the referenced commit above. Closing this ticket as it appears to be a doc only issue. To be re-opened if that's not the case.
