### ISSUE TITLE
API docs for _changes have some incorrect options

### ISSUE THREAD

**Issue by zgramana** [couchbase/sync_gateway#1507]
Note, these look like legacy CouchDB API docs items needing cleanup.
## From @ethanfrey. 

For a documentation review, I decided to compare http://developer.couchbase.com/documentation/mobile/1.1.0/develop/references/couchbase-lite/rest-api/database/get-changes/index.html with `src/github.com/couchbase/sync_gateway/rest/changes_api.go` in the master branch.

If I look at the strings that are parsed from the query string into options, I that the GET request supports the following:
- since
- limit
- style (only allowed: all_docs)
- include_docs
- filter (only allowed: sync_gateway/bychannel) 
- channels
- doc_ids
- heartbeat
- timeout

The POST request supports the same as well as:
- feed
- accept_encoding (gzip compression, nice!)

The following parameters are listed in the documentation but are completely ignored by the codebase:
- attachments
- att_encoding_info
- conflicts
- descending
- last-event-id
- view

Please correct me if I am wrong.

**Comment by ethanfrey** [comment]
For the docs, it would be very helpful to make clear the differences between CouchDB and Couchbase Sync Server.  First, removing the unsupported parameters, and even better documenting how to get a conflicts change feed with sync server (style=all_docs&active_only=true) instead of the CouchDB way (include_docs=true&conflicts=true).

I don't think I'm the only person who starts with CouchDB for local testing to scale up to Couchbase for a production solution, and it would be good to fix up the docs for that.  IMHO, it would be great if they both support the same API, as that makes interoperability easier, but if that is not possible, at least clear documentation of the differences would be good.

**Comment by ethanfrey** [comment]
Hi guys,

I am training a new developer on our couchbase code-base and found out that the `db/_changes` documentation is still outdated.  It should only be a half-hour job to remove the 6 unsupported options and add the new (very useful) active_only flag.  And misleading documentation makes it much harder to onboard new developers.  Or are we the only people using server-side code and the couchbase HTTP API `_changes` directly?

Cheers,
 Ethan

**Comment by adamcfraser** [comment]
@ethanfrey The docs have already been updated to remove the unsupported features, although they don't yet include active_only.  http://developer.couchbase.com/documentation/mobile/1.2/develop/references/sync-gateway/rest-api/database-public/get-changes/index.html

**Comment by ethanfrey** [comment]
Thanks. I must have still been reading the 1.1 docs
