### ISSUE TITLE
[enhancement] Add all_or_nothing in request body on [POST /{db}/_bulk_docs] rest api

### ISSUE THREAD

**Issue by atom992** [couchbase/sync_gateway#1569]
If I can indicate whether to use all-or-nothing semantics for the database commit mode by all_or_nothing, I can get error if at least one document was rejected by validation function.Just like [POST /{db}/_bulk_docs REST api for CBL](http://developer.couchbase.com/documentation/mobile/1.2/develop/references/couchbase-lite/rest-api/database/post-bulk-docs/index.html)

**Comment by adamcfraser** [comment]
This would require transactional processing of the sync function for multiple documents, which in turn would require a transactional commit of multiple documents against the backing data store.  

Specifically: after Sync Gateway evaluates the sync function for a document, it writes that document to the backing data store using a CAS write, to ensure that someone else hasn't updated the document concurrently.  If the CAS write fails, the sync function needs to be re-executed before the next attempted write of the document.  This prevents Sync Gateway from doing all_or_nothing sync function execution for a bulk_docs set - even if all documents are run through the sync function before any are committed, it doesn't guarantee that there won't be a subsequent failure due to CAS retry.

**Comment by atom992** [comment]
ok, that means SyncGateway can not offer  all-or-nothing semantics for the database commit mode, Right?

**Comment by adamcfraser** [comment]
Right - SG can't do all-or-nothing commits, for the reasons described.
