### ISSUE TITLE
New warning happening on SG 1.2: "MultiChangesFeed: Terminator missing for Continuous/Wait mode"

### ISSUE THREAD

**Issue by snej** [couchbase/sync_gateway#1575]
I just noticed the following warnings in the SG log after running the iOS unit tests. I think these are from tests that specifically test the `_changes` feed, not a full replication.

```
2016-02-09T13:22:22.034-08:00 HTTP:  #1451: GET /cbl_replicator_scratch/_changes?feed=websocket
2016-02-09T13:22:22.034-08:00 HTTP+: #1451:     --> 101 Upgraded to WebSocket protocol  (0.0 ms)
2016-02-09T13:22:22.035-08:00 WARNING: MultiChangesFeed: Terminator missing for Continuous/Wait mode -- db.(*Database).MultiChangesFeed() at changes.go:185
```

**Comment by snej** [comment]
(SG 1.2 release, CBL/iOS 1.2 release)

**Comment by adamcfraser** [comment]
Do you think this is a new issue (i.e. not seen when running unit tests against SG 1.1.1)?

**Comment by adamcfraser** [comment]
If so, I expect the problem is the change to terminator handling in this commit:
https://github.com/couchbase/sync_gateway/commit/098e033339350781ae52011fe4f3d1c1bd160dea

It looks like we may need to retain re-initialization of the terminator inside the websocket handler.  I'd like to better understand why that's needed.  Is ServeHTTP not a blocking call?

**Comment by snej** [comment]
I don't know if it's a new issue. It's been a while since I've looked through the SG logs after running CBL unit tests.

**Comment by Crapulax** [comment]
This issue is new with SG1.2.
Never seen it before while looking daily on logs, have noticed it immediately after upgrade to 1.2...

**Comment by EthanRTF** [comment]
I have also started getting this after upgrading to SG 1.2

**Comment by tleyden** [comment]
@EthanRTF are you getting this while running the unit tests, or?  Exact steps to reproduce would be great.

**Comment by EthanRTF** [comment]
@tleyden We are getting this in our production environment. I can't really say the exact steps to reproduce because our usage has not changed. The only change that we made was upgrading from 1.1 to 1.2.

If you'd like any specific information on our setup, I'd be more than happy to get it to you so that we can get it fixed.

**Comment by tleyden** [comment]
@EthanRTF ok, thanks, that's good to know.  Are you seeing any incorrect behavior associated with the warning?  Any new warning/errors in the Couchbase Lite logs?

**Comment by ajres** [comment]
When _changes feed type is WebSocket, options are reread from the first message in the websocket stream. Changes_api.go Ln #557  

"// Read changes-feed options from an initial incoming WebSocket message in JSON format:”.

**Comment by ashvindersingh** [comment]
Verified that #1618 fixes the issue by running the iOS unit test. 
Steps:
- First reproduced the issue by running the iOS unit test https://github.com/couchbase/couchbase-lite-ios/blob/master/Unit-Tests/ChangeTracker_Tests.m#L149 against sync gateway 1.2-77 build. Logs with warning: https://gist.github.com/8ca5c221b686b2503a6b
- Built sync gateway from the master branch. Followed instructions from https://github.com/couchbase/sync_gateway#building-from-source-without-dependency-pinning
- Reran the same unit tests. Verified no Warning message was in logs. SG Logs: https://gist.github.com/681bde2f60e86f337bf0
