### ISSUE TITLE
Use latest version of Otto

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1580]
To reproduce:
- Point submodule to latest version of Otto
- `./test.sh -v -run TestUserViewQuery`
- `./test.sh -v -run TestAccessFunctionTakesNonChannelsInArray`

Spun out of https://github.com/couchbase/sync_gateway/issues/1572#issuecomment-182153496 (see that ticket for a link to a ticket we filed against Otto earlier)

**Comment by adamcfraser** [comment]
The following tests are breaking:
- [ ] TestAccessFunctionTakesNonChannelsInArray
- [ ] TestUserViewQuery

**Comment by adamcfraser** [comment]
TestUserViewQuery looks like it's due to a change in otto to return an array of strings as []string, instead of []interface{}.  It's failing in the filterViewResult code used for filtering of walrus views (in design_doc.go).  We may be able to work around by manually iterating over value[0] - which should be a list of channels - and doing a type-safe conversion to a list of strings (and modifying channelsIntersect to take a list of strings).  

A better approach would be to try to do a safe type conversion to both {}interface and []string.

It looks like the change in otto to return []string instead of {}interface is related to the scenario described below.

**Comment by adamcfraser** [comment]
TestAccessFunctionTakesNonChannelsInArray is failing due to the 'null' in the channels array.  Someone could hit this in the real world if they were using user data for channels, and ended up trying to use null as one entry in a list that was otherwise strings.

It looks like the latest otto has been enhanced to try to identify whether all elements in an array are a common type, and to return an array of that type if they are (as opposed to an array of interface{}):

This handles arrays of mixed values (e.g. ["three",3]), and just reverts to the default handling in that case.  However, it's not doing a nil check for t here:
https://github.com/robertkrimen/otto/blob/master/value.go#L696
which is where we're failing.  I think this is a valid bug in otto that we could file a PR for - to fall back to returning interface{} when the reflect on line https://github.com/robertkrimen/otto/blob/master/value.go#L692 returns nil, instead of panicking.

**Comment by tleyden** [comment]
Closing as duplicate of https://github.com/couchbase/sync_gateway/issues/2471
