### ISSUE TITLE
_sync:"sequence" is set to 0 causing documents not to replicate to our shadow bucket

### ISSUE THREAD

**Issue by lassebn** [couchbase/sync_gateway#1581]
Hi

We have a setup using bucket shadowing for our system. The system consists of 3 parts:
- A web application
- A number of services
- A smartphone application (Android and iOS) that needs to work offline - we are running couchbase lite on the devices

Most documents are only touched from one place, typically a service, but some documents can be created or edited by our users either through the web application, or from the smartphone application.

The web application and the services access the original bucket (source bucket), and the smartphone applications sync through the shadow bucket set up for the sync gateway.

We have seen some issues where some documents stop replicating to the shadow bucket. As I looked into the documents in the shadow bucket I can see that

```
{ _sync: {
  "sequence": 0
  "recent_sequences": [
    ...,
    0
  ]
}
```

for the documents that are not being updated in the shadow bucket, when they are updated in the source bucket. If I remove `0` from `recent_sequences` and update `sequence` to the value of the latest `recent_sequences` the document is being replicated again.

But I would like to understand why this is happening. Unfortunately I do not have a method to replicate this behaviour right now.

The documents we have experienced this behaviour with are only updated in the source bucket, and we are typically adding entries to a list in the updated document.

I also have an open thread on the forum here: https://forums.couchbase.com/t/understanding-the--sync-sequence-and-why-it-is-0/6821

**Comment by lassebn** [comment]
We are seing the following error in our logs, that might have something to do with it:

```
11:19:40.780796 2016-02-09T11:19:40.780+01:00 WARNING: Error from Incr in sequence allocator (0) - attempt (1/3): MCResponse status=DELTA_BADVAL, opcode=INCREMENT, opaque=0, msg: Non-numeric server-side value for incr or decr -- db.(*sequenceAllocator).incrWithRetry() at sequence_allocator.go:86
```

**Comment by adamcfraser** [comment]
That error does look suspicious.  What's the value of the `_sync:seq` document when viewed through the Couchbase Admin Console?

This looks similar to the behaviour that was reported on issue #302, but there wasn't a clear resolution for that ticket.  If you're able to provide a larger excerpt from your SG logs (in a gist, preferably), that might shed a bit more light on the issue.

**Comment by lassebn** [comment]
I have posted some of the log here: https://gist.github.com/lassebn/9b876b9a1fb75ca8b4bf
It is rather big - I called `_replicate` a few times, which added quite a few entries.

The value of `_sync:seq` is `61911`

I hope that this might help the investigation.

**Comment by adamcfraser** [comment]
It looks like you're getting intermittent failures on the Incr operation that updates the sequence.  In most cases the retry handling is successful, but in two cases the Incr doesn't succeed after the third retry:

```
WARNING: Too many failed Incr in sequence allocator - failing (1): <nil> -- db.(*sequenceAllocator).incrWithRetry() at sequence_allocator.go:92
```

At this point it looks like we're proceeding with the write with sequence 0, instead of returning error on the write request.  I'm going to use this ticket to track that issue/fix.

The other question is why you're seeing the intermittent Incr failures in the first place.  My suspicion is that it's a scenario where your Couchbase Server is overloaded, but let me know if you think that's unlikely given your sizing and load.

**Comment by adamcfraser** [comment]
There's a scoping problem for err here:
https://github.com/couchbase/sync_gateway/blob/master/src/github.com/couchbase/sync_gateway/db/sequence_allocator.go#L92

It's getting redefined inside the retry loop due to the multi-var assignment during the Incr call, and ends up getting returned as nil if the retries are unsuccessful.

**Comment by lassebn** [comment]
Great work, and thank you for the insights.
The server might very well have been overloaded. We have only seen this issue in our development setup, and that Couchbase Server hasn't got oceans of resources.
