### ISSUE TITLE
Sync Gateway May Not Like Document Updates Via REST API

### ISSUE THREAD

**Issue by nraboy** [couchbase/sync_gateway#1582]
User, Ravi, mentioned that the Sync Gateway may not be replicating documents that were updated via the REST API.

![original](https://cloud.githubusercontent.com/assets/983958/12984150/1a67dc50-d0b2-11e5-8cfd-a000ad776f04.jpg)

The blog thread can be found here:

http://blog.couchbase.com/using-couchbase-in-your-ionic-framework-application-part-2#comment-2507784468

**Comment by tleyden** [comment]
From Ravi:

> Thanks for the link .The updateDocument function is updating my local database Document(Mobile database) .
> But it is not pushing update to the server. Using sync gateway, CreateDocument and Delete function are working properly in my aplication and the Couchbase server sync is also working correctly through syncgateway. but while using update the server log is showing error as in screen shot

**Comment by adamcfraser** [comment]
This doesn't look like a Sync Gateway bug - it's the expected behaviour when your Sync Function rejects a document.  In particular it looks like a requireUser clause in your sync function is rejecting the document.  Diagnosing the user's sync function is better done via the forums, instead of as a github issue.
