### ISSUE TITLE
Split SG_Accel out to it's own repo

### ISSUE THREAD

**Issue by zgramana** [couchbase/sync_gateway#1586]

**Comment by adamcfraser** [comment]
Have moved sg_accel functionality to two independent packages (sg_accel, indexwriter) within the current SG repo, in preparation for migration of those packages to the sg_accel repo.  CBGT and index writer functionality is now decoupled from Sync Gateway's server and database contexts, so that the new sg_accel repo can treat SG as a library, instead of requiring significant code duplication.

Refactoring is complete and it builds - it's pushed to branch https://github.com/couchbase/sync_gateway/tree/feature/issue_1586.

The following work is still pending:
- [ ] Unit tests running clean
- [ ] Local deployment testing
- [ ] Migrate to new repo
- [ ] Support for addition/removal of databases at runtime
- [ ] Get functional tests running

I'm considering treating the last two as new issues to be filed against the new repo when it's created.
