### ISSUE TITLE
Travis CI build error after pushing to SG repo

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#1592]
After pushing a change the SG repo README.md, I received a Travis CI build error.

@tleyden:  Is this is a known issue with the SG repo refactor?

https://travis-ci.org/couchbase/sync_gateway/builds/109363708

**Comment by tleyden** [comment]
Travis needs a .travis.yml file checked into the repo.  I have a branch where I was trying to get travis to work:

https://github.com/couchbase/sync_gateway/tree/feature/travis_build
- Attempt #1: Use `go get` and `go test`, but the tests failed with [known issues](https://github.com/couchbase/sync_gateway#building-from-source-via-go-get) when building from `go get`, since it uses the master branch commit version of every dependency
- Attempt #2: Build with the repo tool, but got [these errors](https://travis-ci.org/couchbase/sync_gateway/builds/108932314), which I guess are related to the $GOPATH.  Also, I think Travis has it's own version of `repo` pre-installed so maybe we should use that.  The whole approach is kinda of wonky though, because when using `repo` you don't even need to clone the whole repo via `git clone`, but travis does that by default.  I think we might consider filing a support ticket to Travis and get their thoughts on it.

Anyway, I think we should prioritize Jenkins (see https://github.com/couchbase/sync_gateway/issues/1588)

**Comment by djpongh** [comment]
Now on Jenkins
