### ISSUE TITLE
Cleanup task for obsolete attachments

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#1648]
When a document is deleted or an attachment removed the binary document remains in the underlying CBS bucket.

For apps that create and delete docs with attachments on a regular basis this can have a big impact on storage.

There is already a _vacuum DB endpoint which is meant to purge orphaned attachments but it is currently not implemented.

```
// Deletes all orphaned CouchDB attachments not used by any revisions.
func VacuumAttachments(bucket base.Bucket) (int, error) {
    return 0, base.HTTPErrorf(http.StatusNotImplemented, "Vacuum is temporarily out of order")
}
```

**Comment by nbrys** [comment]
Is there any progress on this issue?

**Comment by adamcfraser** [comment]
This didn't make it into the 1.3 release, but should be available on master as soon as we get 1.3 out the door, and will be included on 1.4.

**Comment by adamcfraser** [comment]
Original issue was filed as on https://github.com/couchbase/sync_gateway/issues/64.  The main design issue remaining is handling concurrency issues during GC processing, specifically:

> Initial identification of orphaned attachments is relatively straightforward using a view, but there isn't a good solution for the associated concurrency problems when we try to perform the deletes based on the results of that view query:
> 1. A new document arrives referencing an attachment that's targeted for deletion while GC is in progress.
> 2. An incoming new attachment gets incorrectly flagged for delete by the GC, since it's committed before the document is committed.
> 
> In particular this is an issue for a multi-node SG cluster, where it's harder to do a 'stop the world' for attachments across the cluster while the GC is running.  We also need to ensure the solution only has a performance impact while GC is running, and has a negligible impact on standard attachment processing (i.e. we want to avoid significant work to lookup the attachment state during a normal write)

**Comment by adamcfraser** [comment]
Review this in a wider context as part of the attachment management strategy for 2.0.

**Comment by evanherc** [comment]
As you are delaying this issue ... Is there any way to manually get rid of these in the mean time that came out of the investigation ? Doesn't matter how ugly the solution is but I have a few hundred gigabytes of those sitting in a few buckets and they keep growing over time. I'm even willing to dump a backup, change that and restore it just to get rid of them occasionally but alas at the moment that doesn't seem to work either (or at least I don't know how).

**Comment by polfer** [comment]
I second the request from @evanherc.  Any strategy for dealing with this would be appreciated (we also have almost 100GB of orphaned and processed attachments).  We have gone so far as to build a view that identifies attachments that we think could be deleted, but an approved manual procedure (even if a little aggressive) would be very welcome while waiting for the feature.

**Comment by nbrys** [comment]
We currently keep struggling with this issue and are still waiting for a resolution.

**Comment by mikemliu** [comment]
+1 Our use case for attachment is only for temp storage of images synced up by couchbase lite. Deletion of these images after transfer to permanent storage is badly needed -- taking up majority of RAM in cluster.

Pls advise if this strategy can work temporarily:
1. query document of attachment list {digest_id}
2. update document to delete _attachments property
3. go thru **couchbase** api to directly delete each of the documents referenced by _sync:att:{digest_id}

will this strategy create any problems internally for sync gateway?

**Comment by adamcfraser** [comment]
@mikemliu That's the general approach.  The potential concurrency issue is if a new document arrives referencing an existing attachment between steps 1 and 3 - it will see that the attachment already exists, and create a reference to it in its _attachments property.  When you delete the attachment body in step 3, you're left with a reference to the non-existent attachment.

This is only an issue if you expect your application to have multiple documents referencing the same attachment.  If that's not the case, you should be fine.

**Comment by b-smets** [comment]
I think the workaround of @mikemliu won't work in our case. We currently have a great number of already deleted json documents which used to refer to now orphaned attachments. The only way we could do this, is by querying all the attachment digests in Couchbase and then check 1 by 1 if there is any alive json document still referring to them. This implies a very long downtime, I think.

Are there any alternatives that we are missing?

**Comment by adamcfraser** [comment]
Either a map reduce view or a N1QL query could be built to accomplish the same results.

For the MR view - the map function would emit a row for each attachment found (based on the _sync:att: prefix), and a row for each attachment reference in a doc.  The reduce would be a simple count, and then you'd be querying for results with a count of 1.

**Comment by polfer** [comment]
@mikemliu we have the exact same situation as you in that we have temporary media objects captured by devices and synced up with Couchbase Lite. These are shifted to S3 and then deleted, but the temporary object doesn't really clear.

@adamcfraser we have put together a view to identify these documents, acknowledging the concurrency risk. In case you want to review it, or others are interested, here is the view that we are testing: [map_js.txt](https://github.com/couchbase/sync_gateway/files/907777/map_js.txt)

We do a couple things there for safety sake.  First, we attempt to identify the targets (blobs), any original documents that have migrated to S3 (migrated - you can see we saved the digest separately as a cross check), documents of any type that still reference that digest (root), and also any conflict bodies that may reference the attachment (conflict) - we're not to sure about the last.  We then "score" candidates for deletion.  In our case we consider delete of the blob if there are no primary revision or conflict body references to the attachment _and_ we an clearly see that both the original attachment and the tracking object made it to the server and were pushed to S3. If all this is true, we take a backup of the raw attachment body to local storage (by digest) and delete the object.

None of this escapes the concurrency issue that Adam mentioned, but we are thinking this may be safe enough for our use case (which matches Mike's) that it may be worth a shot.

@adamcfraser What do you think?  Is the conflict stuff ok?  An alternate strategy is to try to resolve any outstanding conflicts full before an attempt.

Also, can you think of any caching or other issues that may hit Sync Gateway if we're deleting the attachments out from behind it while it is running?  I'd rather not have to down the whole service, but if you thought there was risk we may have no choice.  At the very least we could bounce the gateways and services immediately after a bulk action to delete. 

Any thoughts on this in the gap are really appreciated.  Thanks.

**Comment by mikemliu** [comment]
@polfer I've already implemented my strategy and sync gateway seems to be ok with the stuff changing underneath it. We use the changes feed strategy to move documents that need attachment transfer into separate channels for processing, then once they finish transfer, they are moved to a cleanup channel that then get processed to remove the attachment data out from couchbase directly.

We have no race condition concerns since the server side is only a sink for these documents. I think the only very rare case is when 2 clients somehow generate the same attachment in the same short span of time between sync and cleanup...since our documents are photos from the camera, shouldn't be a concern here.

**Comment by Grimal** [comment]
Pleased to see this come out of the icebox.  We're about to have the same storage bloat concerns as others, and need a solid plan for cleanup going forward.

**Comment by adamcfraser** [comment]
Needs followup to confirm 2.0 CBL behaviour - specifically whether there's a 1-to-1 association from attachment to document.  If so, the attachment lifecycle can be modified to follow the document lifecycle (i.e. clean up attachments on document removal).

**Comment by tleyden** [comment]
> specifically whether there's a 1-to-1 association from attachment to document

@adamcfraser looks like attachments are still shared among docs based on the content-addressable store approach.


To verify this, I used mobile-training-todo to add two docs with the same attachment:

## Doc id -lwoJM-z8EjO2tswcm5S9yp

```
{
  "_attachments": {
    "blob_1": {
      "content_type": "image/jpeg",
      "digest": "sha1-8Lg7sMzIqffCOp5I44ctpTDaaww=",
      "length": 241444,
      "revpos": 1,
      "stub": true
    }
  },
  "_deleted": false,
  "complete": false,
  "createdAt": "2018-02-26T20:37:38.095Z",
  "image": {
    "@type": "blob",
    "content_type": "image/jpeg",
    "digest": "sha1-8Lg7sMzIqffCOp5I44ctpTDaaww=",
    "length": 241444
  },
  "task": "IosTask2",
  "taskList": {
    "id": "user1.E2560109-44E7-4789-8C34-2E744941FB41",
    "owner": "user1"
  },
  "type": "task"
}
```

## Doc id -MCw8q3tzq5EYSdrivfWjy1

```
{
  "_attachments": {
    "blob_1": {
      "content_type": "image/jpeg",
      "digest": "sha1-8Lg7sMzIqffCOp5I44ctpTDaaww=",
      "length": 241444,
      "revpos": 2,
      "stub": true
    }
  },
  "_deleted": false,
  "complete": false,
  "createdAt": "2018-02-23T00:46:11.689Z",
  "image": {
    "@type": "blob",
    "content_type": "image/jpeg",
    "digest": "sha1-8Lg7sMzIqffCOp5I44ctpTDaaww=",
    "length": 241444
  },
  "task": "IosTask1",
  "taskList": {
    "id": "user1.E2560109-44E7-4789-8C34-2E744941FB41",
    "owner": "user1"
  },
  "type": "task"
}
```

and they both appear to refer to attachment doc: `_sync:att:sha1-8Lg7sMzIqffCOp5I44ctpTDaaww=`.

**Comment by tleyden** [comment]
There seems to be two overall approaches to this problem:

## Approach A: Modify couchbase lite to generate attachment digests to be per-document 

**Overview**

This proposed fix would make each attachment digest unique per document, so that as soon as a document was deleted, all of it's attachments could immediately be deleted.  Currently the attachment digests are shared among documents, which can save space.  However, it makes them tricky to clean up, since there is currently no way to know whether *other* docs are referring to an attachment.  

**Pros**

1. Simple

**Cons**

1. Potential data migration work involved.
1. In certain use cases where a large number of docs point to the same attachment, this could increase the overall attachment storage footprint for the Sync Gateway / Couchbase Server backend.

## Approach B: Implement ref-counting scheme

**Overview**

This proposed fix would continue the content-addressable-store approach to attachments, but add a "reference counter" to each attachment, so that it could safely determine when attachments could be reaped.  For example:

1. `Doc1` creates an attachment, which is a picture of cat
1. The system hasn't seen this attachment data yet, so it assigns a unique digest (`Attach1`) and adds it to the system
1. `Attach1` is given a refcount of 1, since 1 document is referencing it
1. Doc2 creates an attachment, which is the same picture of the same cat (the identical file as `Attach1`)
1. The system recognizes that this content already exists as `Attach1`, so does not add duplicated attachment content into the system
1. `Attach1` is given a refcount of **2**, since now both Doc2 and Doc1 are referencing it
1. Doc1 is deleted
1. `Attach1` has it's refcount decremented from **2** -> **1**, since now only Doc2 is referencing it
1. Doc2 is deleted
1. `Attach1` has it's refcount decremented from **1** -> **0**, since there aren't any docs remaining that are referencing it
1. `Attach1` is deleted and it's space is reclaimed.

**Pros**

1. No increase in storage
1. Data migration work would most likely be simpler than the per-doc attachment digests approach

**Cons**

1. No clear way to implement this since two documents might need to be updated atomically (however, with some more design discussions, this might be solvable)

**Comment by tleyden** [comment]
@snej any thoughts on the approaches mentioned in https://github.com/couchbase/sync_gateway/issues/1648#issuecomment-368655651?

@djpongh there's not any actionable work until we figure out an overall approach, so I'm going to re-assign to you to drive that forward.

**Comment by djpongh** [comment]
Unfortunately, this is too complicated to try and get into our 2.1 release.

**Comment by ArihantRk** [comment]
@djpongh @adamcfraser  When can we expect this feature is going to be added/fixed.

**Comment by adamcfraser** [comment]
Migrated to [CBG-795](https://issues.couchbase.com/browse/CBG-795)
