### ISSUE TITLE
Improve repo based build process

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1674]
Current action items:
- [ ] Change the protocol in the manifest from git to https or ssh avoid the problem of being unable to push without changing the remote definition?
- [ ] Restore clean.sh, to set the GOPATH and run go clean

**Comment by tleyden** [comment]
## How do I pull the latest changes on the current branch I'm on?
- Find the hash of the latest commit on github for the branch you are currently on
- Run `./bootstrap.sh <commit-hash> <commit-hash>`

Verified that this works with no local changes .. still need to verify what happens if there are local changes (will they be discarded or will the operation fail?)

**Comment by tleyden** [comment]
## How do I switch branches?
- Find the hash of the latest commit on github for the branch you want to swtich to
- Run `./bootstrap.sh <commit-hash> <commit-hash>`

Not tested, but I'm expecting it to work ..

**Comment by adamcfraser** [comment]
- [x] ~~Script to see all the changes across all repos~~  - use `repo forall -c 'git status'`
- [x] ~~Detect whether you've got local changes, and don't delete them when bootstrap is re-run.  Should cancel bootstrap and report which local changes are present~~ Repo tool already detects local changes and cancels the repo sync when it hits them

Other misc tasks:
- [ ] Validate that repo sync doesn't blow away repos that aren't in the current manifest.  e.g. If I'm working on a branch with a new dependency, will switching to master delete the local repo for the new dependency?
- [ ] Check whether the repo tool can check out a specified branch, instead of putting you on a detached head (at least for the SG repo).  Specifically, would like to be able to quickly switch to a (Sync Gateway) branch, make a change, and push.  Right now there's extra overhead to get yourself switched from a detached head to the actual branch you wanted to check out.  One option might be to rewrite the local manifest to point to a SG branch before running repo sync?
- [ ] Once the above issues are sorted, create a screencast to demo best practices

**Comment by adamcfraser** [comment]
Also include the change described on #1625
