### ISSUE TITLE
Investigate possible bulk_docs bottleneck

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#1695]
Using Couchbase Server 4.1.0 and sync_gateway 1.2.0-79

Discovered while running https://github.com/couchbaselabs/mobile-testkit/blob/master/testsuites/syncgateway/functional/1sg_1ac_1cbs.robot#L139-L140

The test case does the following.
- 3 channels are created ("KMOW", "HWOD", "KDWB")
- A user is created with no channels
- User is granted access to "KDWB" via sync function
- 3 sets of 5000 doc are pushed in sequence to each of the channel (3 POST bulk_docs )
- Verify user gets 5000 "KDWB" docs

This test will fail intermittently with ReadTimeouts on the client side. I was able to repro the issue with a client read timeout of 30 seconds (PacketCaptures/sg.pcap). The read times out on the first bulk_docs request. 

I bumped the client read timeout to 120 second and the test was able to complete. Upon inspecting the the packet capture (PacketCaptures/sg120to.pcap), I was able to see up to 13 sec long long deltas from when sync_gateway recieved the bulk_doc request and when it issued a 201 response

Example:

```
882    14.524555    192.168.2.21    172.23.106.48   HTTP    1161    POST /db/_bulk_docs HTTP/1.1  (application/json)
1665    27.745847   172.23.106.48   192.168.2.21    HTTP    1294    HTTP/1.1 201 Created [Malformed Packet]
```

The `14.52` and `27.75` is the delta between the request and response

Packet Captures from sync_gateway machine - [PacketCaptures.zip](https://github.com/couchbase/sync_gateway/files/217784/PacketCaptures.zip)

**Comment by sethrosetter** [comment]
- [x] Get verbose logging

**Comment by adamcfraser** [comment]
@sethrosetter Does the failing test with the 30 second client read timeout mean that the bulk_docs requests were taking 30+ seconds in that case?

**Comment by sethrosetter** [comment]
@adamcfraser It appears so. Although I'm not certain. If you look at the `sg.pcap` aka the 30 sec client read timeout, you can see that a response is never delivered. The test throws an exception and fails after issuing the first bulk_docs call. If you look at `sg120to.pcap`, they client read timeout was 120 seconds, and it gets all of the 201 responses from the bulk_docs POST, albeit after ~10 seconds

**Comment by adamcfraser** [comment]
@sethrosetter  Getting the verbose logs from SG that you mention above for the failing case should help shed some light on what's going on - I'll take a look once you've got those.

**Comment by sethrosetter** [comment]
@adamcfraser Here is a packet capture with verbose logging on the sync gateway. 

[PacketCapWithVerboseSG-logging.zip](https://github.com/couchbase/sync_gateway/files/221534/PacketCapWithVerboseSG-logging.zip)

Looks like a lot of sync_function processing.

**Comment by adamcfraser** [comment]
In this log it looks like it's taking ~8s to push 5000 docs for each of the three _bulk_docs calls.

That's probably not too far out of the expected range for _bulk_docs today - we do sync function execution and the DB PUT operations for each doc serially, so that's something like 1.5 ms per doc to execute the sync function and write the doc to the server. 

There isn't any obvious optimizations.  Spawning a set of worker goroutines to process the docs in parallel would help in this scenario (where there's only one active client), but I'm not sure it would end up a net performance improvement for a Sync Gateway in a real-world scenario with many active clients.

When we move standard Sync Gateway to gocb, we could think about refactoring the write operations to take advantage of the async pipelining gocb uses for bulk ops. It's not completely straightforward, since we need the Sync Function execution to be inside the write CAS loop.  It would probably require refactoring the write operations in general to use a write worker pool.

**Comment by adamcfraser** [comment]
Closing based on age, and write throughput enhancements in 2.6.
