### ISSUE TITLE
Let user define friendly name for a replication to _replicate

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#1707]
Currently when starting a replication it is given a random UUID.

It would be useful to allow users to specify a label for a replication that will be reported in _active_tasks responses.

This should be supported for both REST API requests and Sync Gateway config

**Comment by ajres** [comment]
Should we allow users to provide their own "replication_id" value instead of generating a UUID for new replications? Or should the user define a label as a separate property on the replication?

Individual replications defined in SG config have a property name, we could use this for the custom label but it is defined outside of the replication JSON Object so it is not compatible with the REST API. 

It would be better to make config "replications" an array of unnamed JSON Objects and define the label in the replication JSON body to match the REST API.

**Comment by adamcfraser** [comment]
My expectation is that we're just providing a way for users to define their own replication_id.  

I agree that consistency with the API payload is preferable, and I've never been a huge fan of using map keys as user-defined values in the config.  I'm fine with switching to an array instead of a map in the config.
