### ISSUE TITLE
Sync Gateway unable to reconnect to TAP feed when Server node goes down

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#1709]
User reported Sync Gateway going offline in the following scenario:
- [ ] Multi-node Couchbase Server cluster (2 or 3)
- [ ] One node in the cluster goes down 
- [ ] Sync Gateway drops TAP feed, and goes to offline as a result

In this scenario I'd expect Sync Gateway to attempt to reconnect to the TAP feed, and only go offline if unable to connect after the retry timeout.

Conversation here:
https://forums.couchbase.com/t/syncgateway-databases-offline/7847/6

Relevant SG logs from the above ticket:

```
WARNING: Bucket Updater for bucket ptxdata returned error: Get http://xx:8091/pools/default/bucketsStreaming/ptxdata: dial tcp 10.2.0.184:8091: getsockopt: connection refused -- base.GetCouchbaseBucket.func1() at bucket.go:469
11:34:37.243467 2016-04-18T11:34:37.243+05:30 WARNING: Lost TAP feed for bucket ptxdata, with error: Get http://xx:8091/pools/default/bucketsStreaming/ptxdata: dial tcp xx:8091: getsockopt: connection refused -- rest.(*ServerContext).getOrAddDatabaseFromConfig.func1() at servercontext.go:646
11:34:37.243482 2016-04-18T11:34:37.243+05:30 CRUD: Taking Database : ptxdata, offline
11:34:37.243492 2016-04-18T11:34:37.243+05:30 CRUD: Waiting for all active calls to complete on Database : ptxdata
```

In particular the failed Bucket Updater call is relevant - go-couchbase uses that to identify changes to the cluster topology.  It's possible that this scenario occurs when the node that drops is the server address defined in the Sync Gateway config.  Expectation is that go-couchbase should get the full set of node IPs on initial connection, and roll over to other node addresses if the primary node fails, including when making bucket updater calls.

**Comment by ddash1** [comment]
Adam any updates on this? Is this an issue with sync gw in general or is caused due to a 1 or 2 node CB cluster?

**Comment by vk07519** [comment]
I have got the same issue. This happens only in case of multi-node Couchbase cluster. But in my case, none of the Sync Gateway nodes was connecting to CBS which got down and still one of the Sync Gateway database went offline and never came to online state.
Is there workaround to fix it in 1.4.0 ? Should I put CBS nodes under Load Balancer? In which version can we expect its fix?

**Comment by vk07519** [comment]
Following are log:
07:45:39.034458 2017-10-03T07:45:39.034Z WARNING: Bucket Updater for bucket default returned error: Get http://***.**.**.***:8091/pools/default/bucketsStreaming/default: dial tcp ***.**.**.***:8091: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. -- base.GetCouchbaseBucket.func1() at bucket.go:404
07:45:39.034458 2017-10-03T07:45:39.034Z WARNING: Lost TAP feed for bucket default, with error: Get http://***.**.**.***:8091/pools/default/bucketsStreaming/default: dial tcp ***.**.**.***:8091: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. -- rest.(*ServerContext)._getOrAddDatabaseFromConfig.func1() at server_context.go:350
07:45:39.034458 2017-10-03T07:45:39.034Z CRUD: Taking Database : db1, offline
07:45:39.034458 2017-10-03T07:45:39.034Z CRUD: Waiting for all active calls to complete on Database : db1
07:45:39.034458 2017-10-03T07:45:39.034Z CRUD: Database : db1, is offline
07:45:39.265400 2017-10-03T07:45:39.265Z HTTP: #037:     --> 503 DB is currently under maintenance  (0.0 ms)
07:46:16.935309 2017-10-03T07:46:16.935Z CRUD: Connection to TAP feed for db1 re-established, bringing DB back online
07:46:24.921069 2017-10-03T07:46:24.921Z HTTP: #041:     --> 503 DB is currently under maintenance  (0.0 ms)
07:46:26.936028 2017-10-03T07:46:26.936Z Closing db /db1 (bucket "default")

It does not log anything after this and Sync Gateway does not respond for /db1 requests.

Ideally it should also have below logs (which were missing in my case):
10:20:31.168319 2017-10-03T10:20:31.168Z Opening db /db1 as bucket "default", pool "default", server <http://***.**.**.***:8091>
10:20:31.168319 2017-10-03T10:20:31.168Z Opening Couchbase database default on <http://***.**.**.***:8091> as user "default"
10:20:31.485322 2017-10-03T10:20:31.485Z Cache: Initializing changes cache with options {ChannelCacheOptions:{ChannelCacheMinLength:0 ChannelCacheMaxLength:0 ChannelCacheAge:0s} CachePendingSeqMaxWait:5s CachePendingSeqMaxNum:10000 CacheSkippedSeqMaxWait:1h0m0s}
10:20:31.485322 2017-10-03T10:20:31.485Z Feed: Using TAP feed for bucket: "default" (based on feed_type specified in config file

**Comment by adamcfraser** [comment]
DCP reconnection has been improved and validated since SG 2.0 - closing.
