### ISSUE TITLE
Add convenience methods to support put, delete doc without rev

### ISSUE THREAD

**Issue by ThomasMatzner** [couchbase/sync_gateway#1730]
The documentation of SG's rest API states that, for put and delete, the revision identifier of the requested document has to be submitted, either via the rev parameter or the HTTP header.

Although validating that revision identifier is a valuable feature for some use cases, it isn't needed in all use cases of an update or delete. It puts unnecessary constraints on the application architecture:
- Either the document that has been previously read from the database, needs to carry the revision id around all the time it is processed. This is not a matter of course. E.g., if the database records get converted to database-unaware POJOs, the revision id will be lost.
- Or, before updating or deleting, the document will have to be read (again), just to acquire the revision id. This doesn't offer any additional safety and is a performance obstacle.

So the demand of a revision id is neither sufficient to enforce something like a locking scheme, nor is it necessary: Locking can and should, if possible, be done on the business process layer, thereby preventing user actions that are in conflict from the very beginning.

**Comment by adamcfraser** [comment]
Your points apply to a single author model, but for a distributed application with many potential authors, you need a way to identify and manage concurrent updates and conflicts. 

I think the documentation at http://developer.couchbase.com/documentation/mobile/1.2/develop/guides/couchbase-lite/native-api/revision/index.html does a good job describing how and why revisions are needed.

**Comment by ThomasMatzner** [comment]
Sure, but still the platform should not enforce a programming model. The SQL worlds lives quite well with UPDATE and DELETE commands that don't force you to perform a previous read operation - although, of course, there are cases in which it is better to do so. That's a point to decide by the application architect, not the platform developer.

BTW, this appears to be an idiosyncrasy of buckets handled by Sync Gateway. On CB server, one may just do updates like in a regular database without caring for revision ids.

**Comment by househippo** [comment]
> BTW, this appears to be an idiosyncrasy of buckets handled by Sync Gateway. On CB server, one may just do updates like in a regular database without caring for revision ids.

@ThomasMatzner , Couchbase Mobile fundamentally operates its replication method via Master(Couchbase Lite)/Master(Couchbase Server). So you have to have revision and history so that you can properly respect the users local database as "Another Source of Truth". So in this manner you can reconcile changes between the DB's states when users are offline for mins, hours , days , weeks or months.

**Comment by ThomasMatzner** [comment]
That's true, but forcing the app to provide that rev id isn't a solution to this. Let the mobile client update a document on some revision that it previously read, but be offline and not synchronizing back at once. At the same time my server app does an update on the same document, performs the (unnecessary) revision logic, but still has no idea that something is wrong.

Reading the rev id and immediately performing a put or delete will only catch those conflicts where the other update happens during the tiny time interval between read and update/delete. This is useless in nearly all cases. So my request is equivalent to providing a convenience method that does the read and update/delete in one step, which is again equivalent to making the revision id optional altogether.

**Comment by adamcfraser** [comment]
There may be some value in a convenience API that acts as a set instead of replace - when an application knows a particular document only has a single author, and that author only updates from a single platform.

I've got a couple of concerns, though, that make this a relatively low priority enhancement from my perspective:
- I don't completely agree with the overhead associated with maintaining the rev value on the client.  The _rev property can be managed completely internally with the document (and so be included in a POJO representation), so I'm not convinced of the burden on the application to maintain it.  
- The new convenience API would definitely have more Sync Gateway overhead than the current PUT operation.  As you say, it would need to do a read then write for each document.
- If you're not actually in a single-author setting, this API will eventually lead to data loss, where your server application overwrites a document that's been updated by another client between read and write - even if that's a small window.

**Comment by ThomasMatzner** [comment]
The background for my stubbornness is this: According to the documentation of bucket shadowing, it is strongly discouraged and should be replaced by accessing the SG bucket via its REST API. Now that means for an architect who
- has the requirement to build a mobile app and a server app and support synchronization between them,
- or has the requirement to build a mobile app, but must be prepared for a future request to have a server app as well,
- or has the requirement to build a server app, but must be prepared for a future request to have a mobile app as well (very trendy),

that the SG REST API will be the main tool for communicating with the DB. Strictly speaking, in all those cases the programming language specific APIs will lose importance. Therefore, the SG REST API won't just be a tool for those who like fiddling with replication issues, but the main interface for development with CB, and should be made as versatile as possible.

**Comment by adamcfraser** [comment]
There are definitely good reasons to avoid bucket shadowing - it puts a ceiling on scalability, increases storage requirements, and adds an additional point of failure.

We're working on improved capabilities for Sync Gateway to co-exist with data written by the Couchbase Server SDKs - we understand it's a pain point - but those enhancements are still some distance out on the roadmap.

In the immediate term I think building your REST client to be revision-aware is the best approach - you'll need that to avoid data loss for multi-author documents in any case, and by doing a few things (using _rev inside the document body in particular) I think you can avoid the main issues you outlined (requirement for read-then-write, marshalling/unmarshalling of the document, etc).

We've also got plans to add convenience methods to the API in an upcoming release (currently targeted for 2.0) - I'll make sure this ticket gets reviewed when we define that scope.

**Comment by rversteegh** [comment]
We have a similar single-author use case that requires deletion of documents. In our case we needed a view to identify which documents to delete. To avoid reading the document prior to the delete just to get the revision we stored the revision in the view.

**Comment by wtatum** [comment]
I know this is quite old, but I'd like to add my support for something akin to this. As @ThomasMatzner noted, it _seems_ like use of the REST API is the preferred method for server applications to sync data to the gateway, and I have a single-author case as well. In particular, the role of the single author is to function as a replication service between a back-office system which is outside the Couchbase ecosystem and is not revision aware. Updates are submitted to the back-office system "out of band" and then Couchbase is updated to reflect this after commits are accepted. Since the back-office system serves as the "single source of truth" I would like to be able to blindly replace the document content with the data synced from this service.

The only alternatives I see are reading the current revision just in time, caching the last revision some place, or using a CB Lite instance (and replicating rather than using REST). All of these seem a little awkward. If I opt to go to the DB and fetch the last revision number, can I easily create a view that only exposes the _rev property (so I'm not paying bandwidth for other data I don't need)?

**Comment by egroj97** [comment]
Hi, I'm having an issue with the revision identifier. I want to fetch the revision identifier so that I can delete a document, but I'm unable to do so. I tried when fetching the arguments, but not versioning is returned. I really need this to be implemented in my code. If anyone could give me an advice, I would really appreciate it.

**Comment by bbrks** [comment]
Hi @egroj97

It sounds like you're mainly having trouble fetching a rev ID.

Can I suggest you post this question to the Couchbase Forums instead?
Be sure to include the steps you've already taken, and where it doesn't work to your expectations

https://forums.couchbase.com/c/mobile/sync-gateway

There will be more people there actively looking to answer questions for you than here.

**Comment by egroj97** [comment]
Thank you very much!

**Comment by adamcfraser** [comment]
The underlying requirement - the ability to do a set without caring about revision history - is addressed by using shared_bucket_access and writing to the bucket via the SDK.
