### ISSUE TITLE
sgcollect_info - System information log named 'couchbase.log'

### ISSUE THREAD

**Issue by mattcarabine** [couchbase/sync_gateway#1742]
Testing `sgcollect_info` and found that it generates the file `couchbase.log` for the system-level information.
It would probably be useful (for programmatically determining if a given zip is an `sgcollect_info` or a `cbcollect_info`) and less confusing for this file to be renamed `sync_gateway.log`.

If you think that this idea is acceptable then I'll submit a patch which changes the file name.

**Comment by tleyden** [comment]
If you send a PR for this, make sure to do it in such a way that it's parameterized so that any code in https://github.com/couchbase/sync_gateway/blob/master/tools/cbcollect_info or https://github.com/couchbase/sync_gateway/blob/master/tools/tasks.py would be "generic" and still function if they were being run in a non-sync-gateway scenario.

In other words, if the `couchbase.log` filename is defined in either of those two files (I haven't checked), it should just be changed to a hardcoded `sync_gateway.log`

@McPaddy will the Supportal stuff still work if the system-level logfile is renamed to `sync_gateway.log`?

Btw, I think if we are renaming that file, I think it should be renamed to `system_level_diagnostics.txt` which seems a lot more accurate and descriptive than either `sync_gateway.log` or `couchbase.log`

**Comment by JFlath** [comment]
> will the Supportal stuff still work if the system-level logfile is renamed to sync_gateway.log?

Well, not out of the box, but I think @mattcarabine's point was that instead of searching just for a `couchbase.log` in a given zip file (as the output zip could be named anything) we could search for `couchbase.log` OR `sync_gateway.log`. We can then reuse a lot of the parsers, and we know what the zip we're looking at is, and can go off and handle the other files appropriately.

> Btw, I think if we are renaming that file, I think it should be renamed to system_level_diagnostics.txt which seems a lot more accurate and descriptive than either sync_gateway.log or couchbase.log

On the one hand I agree, `couchbase.log` has a confusing name. But I definitely think it should be `sync_gateway.log`, otherwise we end up with `cbcollect_info` and `sgcollect_info` getting further and further away from each other. The more that happens the more difficult life becomes.

**Comment by mattcarabine** [comment]
Merged into master as part of #1833
