### ISSUE TITLE
Windows InstallShield installer fails when installing on Windows

### ISSUE THREAD

**Issue by wilsondy** [couchbase/sync_gateway#1776]
Very similar to #1573 only without an existing installation.  Tried on Windows Server 2012 R2 and Windows 10 Pro x64.  Used couchbase-sync-gateway-enterprise_1.2.1-4_x86_64.exe

`Product: Couchbase Sync Gateway -- Error 1721. There is a problem with this Windows Installer package. A program required for this install to complete could not be run. Contact your support personnel or package vendor. Action: IS_INSTALL_SERVICE_WRAPPER, location: C:\Program Files (x86)\Couchbase\sg-windows.exe, command: install "C:\Program Files (x86)\Couchbase\"\sync_gateway.exe "C:\Program Files (x86)\Couchbase\"\serviceconfig.json`

**Comment by borrrden** [comment]
In the meantime here is a hacky workaround that I just used because the uninstall workaround didn't work.

From an admin command prompt (possible it doesn't need to be admin but for this directory it does.  You can try changing the directory as well)
`couchbase-sync-gateway-enterprise_1.2.1-4_x86_64.exe /s /x /b"C:\tmp" /v"/qn"`

This will extract the MSI package into the directory you specify.  You can then decompress it (7-zip works well for me) and inside you will find the files you need.  Copy (at least) sync_gateway.exe file.  The standard directory is "C:\Program Files (x86)\Couchbase\" but the exe will run from anywhere.

**Comment by adamcfraser** [comment]
@ajres Is this fixed in 1.3?

**Comment by borrrden** [comment]
On my side I'm able to use the installers now, for what it's worth.
