### ISSUE TITLE
Error installing SG 1.3 on CentOS 5

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#1920]
There is a regression with SG 1.3.0 on RedHat/CentSO 5, the rpm package fails to install with the following message:

```
rpm -i couchbase-sync-gateway-enterprise_1.3.0-234_x86_64.rpm
error: Failed dependencies:
    rpmlib(FileDigests) <= 4.6.0-1 is needed by couchbase-sync-gateway-1.3.0-234.x86_64
    rpmlib(PayloadIsXz) <= 5.2-1 is needed by couchbase-sync-gateway-1.3.0-234.x86_64
```

SG 1.2.1 .rpm installed without error

`rpm -i couchbase-sync-gateway-enterprise_1.2.1-4_x86_64.rpm`

**Comment by michaelkwok** [comment]
I will rebuild on Centos 6.5 tomorrow for you to try since we both suspect it's probably caused by Centos 7 which adds new dependencies to the rpm installer.  

@adamcfraser Do we want to continue supporting Centos 5?  You may have more information on the customer side.

**Comment by michaelkwok** [comment]
I will revert to build on Centos 6.5 since we do have existing customer running on Centos 5.

**Comment by ajres** [comment]
Tested 1.3.0 build 245 clean install on Centos 5 and upgrade from 1.2.1, both passed.

**Comment by michaelkwok** [comment]
I have removed the 2 failed dependency from rpmbuild to allow new rpm installer to be backward compatible with older rpm version.  The issue was that some features available in newer rpm version are not supported in lower rpm version.  Rebuilding on an older Centos does not guarantee no rpm mismatch.  The best solution is to build without the new rpm features as we continue to support older Centos.

**Comment by adamcfraser** [comment]
@michaelkwok Are Centos 6/7 users going to be impacted by the missing rpm features?  Do we know specifically what features will be missed?

**Comment by ajres** [comment]
Install tests completed with build #266, no issues seen on any Centos OS, closing this out.
