### ISSUE TITLE
Pluggable Binary Store

### ISSUE THREAD

**Issue by ldoguin** [couchbase/sync_gateway#1943]
Talking to @rafaelugolini about their use case. They are storing about 10milliions docs, each of then have a 500k attachment.
Would it be possible to plug a binary store on the sync gateway to store binaries somewhere else than in the database? Say S3 or Manta or a NAS?

**Comment by tleyden** [comment]
@ldoguin @rafaelugolini are there any known specific issues with trying to store the attachments directly in the backing couchbase server database?  I'm just trying to narrow into the actual bottlenecks in the current system.

@adamcfraser it definitely feels like we'd want to spec out a "pluggable attachment store" interface such that different attachment storage backends could be plugged into sync gateway, the default backend being couchbase server.

**Comment by rafaelugolini** [comment]
@tleyden we still didn't find any performance issue with it but we would like to be able to store it directly in a file system and serve it like static files.

We discussed this issue some time ago in the forums: https://forums.couchbase.com/t/sync-gateway-attachments-on-separate-disk/6553

**Comment by tleyden** [comment]
@rafaelugolini will there be a mobile app in the picture where attachments are syncing between the mobile app and sync gateway?

**Comment by tleyden** [comment]
> serve it like static files.

Can you elaborate on that a little bit?

**Comment by rafaelugolini** [comment]
@tleyden I have a mobile app which takes pictures, run some image recognition algorithm to generate metadata and store it all in Couchbase lite: eg

```
{
  "meta": {...meta},
  "_attachments": {...files},
  ...
}
```

Once the device has Internet access, the app does a push replication with the sync gateway. I love the fact that Couchbase Lite makes my life super easy, especially with the replication of attachments but would like to set on Sync Gateway or Couchbase Server where these files should be stored.

The idea is to separate the attachments files from the database. It would be great if we also could specify names or directory structure where these files would be stored.

This solution has some APIs to access the content of the metadata and the attachments, so I would like to access the attachments direct from the file system instead of retrieving it from Sync Gateway Views. Makes sense for you? (this is what I mean by _serve it like static files_)

**Comment by tleyden** [comment]
@rafaelugolini Ok thanks, that makes sense.  I noticed you said you wanted to store them in S3, but S3 is accessed via a REST API in the same way that Sync Gateway attachments are.  Or were you planning to mount the S3 bucket onto the filesystem via something like [s3fs-fuse](https://github.com/s3fs-fuse/s3fs-fuse)?

**Comment by rafaelugolini** [comment]
Something like that... but what would be great is a plugin system where we could choose the storage system.

**Comment by jburich** [comment]
This would be a fantastic feature. I am developing an application right now that would like to sync very large 500mb video files. That is not realistic with the current architecture with the 20mb limit on the server side. It would be nice to store any attachment in Couchbase Lite and have it sync properly. Using an S3 bucket instead of the database for these would be ideal.

**Comment by tleyden** [comment]
Thanks for the feedback @jburich!  

I definitely agree that s3, or something compatible with s3 (a la [minio](https://minio.io/)) would be perfect.

**Comment by danlannz** [comment]
has anyone come up with a decent implementation or workaround for this? might try my had at it if not

**Comment by tleyden** [comment]
@jburich nope, no progress on this.  If interested, please write up a proposed solution on this ticket and we can go from there.

**Comment by adamcfraser** [comment]
Closing based on age - may be revisited based on priority in future.
