### ISSUE TITLE
DCP rollback handling (sg-accel)

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1963]
1. Clean the index if there is a rollback
2. Hard b/c from a bunch of vbucket sequence numbers that you want to remove from the index, but you don't know how to get to the channels
3. Fix for clients that already have data 
   1. Fix hashes
   2. Keep rollback history
   3. Use rollback history to fix hashes

**Comment by adamcfraser** [comment]
Additional details on the above:

## Index Rollback

The index is built for retrieval of recent sequences by channels.  In a rollback scenario we'll have a set of sequences we need to remove from the index, but no information on channel membership.

Caching recent updates to the index in memory isn't enough, as we'd lose the ability to handle rollback when sg-accel gets restarted.

The current index storage model persists shared data for a sequence to an index entry document.  We could add channel data to this document to enable a reverse lookup of channels based on vbno and sequence.   However, we want to move away from the index entry storage model, to improve index read performance (see #1965).  One option could be to continue to write these documents solely for rollback handling, setting a TTL value for auto-cleanup.  Would need to review with server team the optimal expiry window to catch all potential rollbacks.

## Client Rollback

We could potentially identify replications that have replicated rolled back data based on the sequence hash entries.  However, we don't have any search capability for these today (they are stored as non-indexable binary documents), so there isn't an option to do a one-time cleanup of hash values that have been impacted by a rollback.  An alternative would be to handle them at request time - when a hash value is read, evaluate whether it's `since` value falls in a rollback window.  This would require:
- maintaining a history of (recent?) rollbacks 
- including an index generation token in the hash value, to differentiate between pre-rollback and post-rollback sequence values.

**Comment by adamcfraser** [comment]
@adamcfraser to split this into separate tickets for Index vs. client.

**Comment by adamcfraser** [comment]
Tracking with:
https://github.com/couchbaselabs/sync-gateway-accel/issues/9
https://github.com/couchbaselabs/sync-gateway-accel/issues/10
