### ISSUE TITLE
Make Index storage scale with number of channels

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1965]

**Comment by adamcfraser** [comment]
Currently index retrieval performance degrades when the number of channels increases significantly.  This is primarily down to the sparse index block storage model.

To better handle scenarios with a large number of sparsely populated channels, we should support a dense index block model which:
- stores all changes entry information in the index block, to minimize the total number of reads required to complete the normal changes requests 
- has an alternate mechanism to identify sequence location within a large set of blocks (for since with limit handling)

Requires updates to the read and write performance tests to validate the performance benefit.

**Comment by adamcfraser** [comment]
This issue was moved to couchbaselabs/sync-gateway-accel#23
