### ISSUE TITLE
sg-replicate: introduce local uuid

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1986]
from @adamcfraser 

> interesting about no local UUID for Sync Gateway - wonder if we should think about adding one in future (i.e. store a UUID doc in the bucket that SG will try to write on startup if it's not found)

**Comment by adamcfraser** [comment]
@tleyden Can you document here the benefits of having a local UUID defined?  My recollection is that it was related to checkpoint handling, but need a reminder on the specifics.

**Comment by tleyden** [comment]
Hmmm, not ringing a bell

**Comment by Fujio-Turner** [comment]
@adamcfraser ,

1.I could see use cases when a global load balancer fails over CBL to another SG/CB cluster with the same SG DB name but with no checkpoint and different UUID.
...CBL might do _changes?since=0&active_only=false
or
2.SG/CB has the same checkpoint but the seq do not match.
...CBL might do _changes?since=0&active_only=false  b/c the UUID is the same as before but the seq in checkpoint is different.
or
3.SG/CB has no checkpoint(maybe it was deleted in CB) but CBL has seen UUID before.
_changes?since=0&active_only=false
