### ISSUE TITLE
Sync Gateway terminating changes requests

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#1999]
Continuing the investigation of the issue outlined here:

https://forums.couchbase.com/t/sg-endless-loop/9203

**Comment by ThomasMatzner** [comment]
[SG user.txt](https://github.com/couchbase/sync_gateway/files/385651/SG.user.txt)
[Android log loop.txt](https://github.com/couchbase/sync_gateway/files/385650/Android.log.loop.txt)
[CB SG log loop.txt](https://github.com/couchbase/sync_gateway/files/385652/CB.SG.log.loop.txt)

[ReplicationUtil.zip](https://github.com/couchbase/sync_gateway/files/385680/ReplicationUtil.zip)

Attached are the log files of the Android device and SG, the SG user initiating the synchronization, and the Java source for initiating the synchronization (zipped because this site doesn't let me upload a .java file).

Environment:

CB Server: 4.0.0-4051, Windows 10
CB Android: com.couchbase.lite:couchbase-lite-android:1.2.1-2
SG: 1.2.1 (4;26c202a)

What happened:
1. Created a fresh CB bucket named shoppingsync2
2. Started SG on that bucket
3. Created three views on that bucket using the SG admin interface
4. Freshly installed Android app, created an Android account (of my own type), created an SG user from the Android app, after which the synchronization gets initialized by the app (ReplicationUtil class uploaded above)
5. Then the app initializes the database with some 250 documents, which get nicely synchronized to the server bucket.
6. Changed one of the documents on Android, which also got synchronized.
7. 18 seconds later, the looping occurs.
8. Killing the emulator (or force close the app on a real device) makes the looping stop.

**Comment by adamcfraser** [comment]
The 'looping' in this case is multiple longpoll iterations - for some reason the longpoll request is being terminated, which triggers the client to resubmit the changes request.

It looks like this looping doesn't start until after the SocketTimeoutException in the client logs.  After that point the client seems to be sending repeated changes requests, but isn't logging anything.  It might be helpful to get some additional logging about what's happening there.

From the Sync Gateway side, I haven't been able to identify why the changes request is getting terminated.   Using strictly REST API calls against SG I've reproduced the request (user with no channel access), and it's staying in wait mode as expected.  

If the Android client was dropping the connection, I think we'd expect to see multiple instances of `Changes: Connection lost from client:  (as user1)` in the logs, but there's only the single instance.

@hideki I think I'll need your help to try to reproduce this issue, or at least get some visibility into what the client is doing after hitting the SocketTimeoutException.

**Comment by hideki** [comment]
To avoid `java.net.SocketTimeoutException` at the client side, you could change [`DEFAULT_HEARTBEAT`](https://github.com/couchbase/couchbase-lite-java-core/blob/release/1.2.1/src/main/java/com/couchbase/lite/replicator/Replication.java#L58) value to smaller value like 120 sec instead of 300 sec (default value for v1.2.1).

Please add following line at begining of `ReplicationUtil.init(...)` method?

``` java
Replication.DEFAULT_HEARTBEAT = 120; // 120 sec
```

**Comment by adamcfraser** [comment]
@ThomasMatzner I'm still looking into why Sync Gateway ends up in a bad state (rapidly terminating the longpoll changes requests) after the initial timeout.  Hideki's suggestion might be a workaround for you until I get to the bottom of that.

**Comment by adamcfraser** [comment]
@ThomasMatzner Can you share a few more pieces of information, to help us repro the issue:
1. How the Android app is creating the SG user.
2. The contents of the user doc, taken from the Couchbase Server Admin Console (doc id=_sync:user:user1)

Thanks.

**Comment by adamcfraser** [comment]
Found what looks like the root cause of this - this is similar to #916, but for the additional case where the changes request attempts to use a channel as a filter that the user doesn't have access to.

The changes processing should be resolving the incoming channel set down to the one the user has access to before initializing the change waiter.  

@ThomasMatzner As a workaround, you can ensure that your user has been granted access to the channel being requested before starting pull replication.  It looks like whatever process you're using to create users isn't assigning the user to channels.

**Comment by ThomasMatzner** [comment]
True, silly mistake on my side. Thanks a lot.
