### ISSUE TITLE
Update build go version to 1.6.3

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#2015]
Tracking ticket for https://issues.couchbase.com/browse/CBLT-438

**Comment by adamcfraser** [comment]
Review the golang security issue in 1.5.3 to determine if this merits a security notice in the 1.3.1 release notes for existing customers.

**Comment by michaelkwok** [comment]
GO 1.5.3 fixed a security in math/big package.  The vulnerability causes a plausible leak of an RSA private key in package crypto/tls.  GO 1.6.0 will additionally double-check the RSA computation.

Go 1.6.3 has 1 security fix for a CGI hole found in 1.6.1 and 1.6.2.  It's irrelevant since we jumped directly from 1.5.3 to 1.6.3.

Overall, I don't think we need to publish this in 1.3.1 release note.

**Comment by michaelkwok** [comment]
Btw, we have updated to GO 1.6.3
