### ISSUE TITLE
Need a way to atomically add/update user channel

### ISSUE THREAD

**Issue by keimoon** [couchbase/sync_gateway#2071]
Currently, to add new channel for an user, we have to get user data using GET /{db}/_user API then update it using PUT /{db}/_user. This will eventually cause problems in high traffic system because it is not atomic. The consequence is this user will miss some documents because he does not subscribe to the channels he intended to.

So we need an API to atomically add/update user channel to overcome this problem.

**Comment by adamcfraser** [comment]
How are your users retrieving documents?  If it's via _changes/replication, they won't miss any documents - any documents that are written to the channel before the user is granted access will be backfilled in the changes response.

**Comment by keimoon** [comment]
Our users retrieve documents via _changes, and the replication process worked fine. The problem is when we add new channels for an user but from different processes, sometimes it is not atomic and causes one update to be overwritten be other.

For example, currently user A is subscribing to channel "0". Process 1 wants to add channel "1" to user A, and process 2 also wants to add channel "2" at the same time. Because in order to add new channel, we must get user information via /_user API, then update it with PUT method, so sometimes thoses 2 processes run concurrently and cause the update to be wrong. The final outcome is user A maybe subscribe to channel ["0", "1"] or ["0", "2"] instead of ["0", "1", "2"] as intended.

**Comment by Crapulax** [comment]
Hello Keimoon,

This is a pure DB update issue whatever the underlying DB is. The _user API does not provide revisions management and as such it will be difficult to handle correctly concurrency. Solutions I see are:
- serialize your channels updates in a single process. But this might not work either on _user because the GW also updates _user when there are channels changes for instance
- why do not use special document to grants access in the sync function?

Have a sync function doing something like:
if type == grantdoc {
access(doc.userid,doc.yourchannel)
}
Instead of updating _user you create a granting document which grants the channel acess. This is how the sync_gateway is supposed to be used for what you want to acheive (at least this is my understanding)

Hope it helps

**Comment by keimoon** [comment]
Thank @Crapulax it really help!

**Comment by adamcfraser** [comment]
Closing this, as sync function-based channel assignment is the way to manage user doc updates when there are concurrency concerns.
