### ISSUE TITLE
Support _exp property on DELETE operation

### ISSUE THREAD

**Issue by ArihantRk** [couchbase/sync_gateway#2075]
Documents are set with expiration time and deleted from syncgateway before expiry time, a new revision will be created with _deleted=true which does not have expiration time in document.
expiration will not work when documents deleted before expiry time.

**Comment by adamcfraser** [comment]
You can performa a delete with expiry via an update operation that sets the _exp value along with _deleted=true in the body of the document.

Are you asking for a way to set the expiry value on a DELETE /db/doc operation?

**Comment by ArihantRk** [comment]
yes we can set delete with update operation. 
we are using DELETE /db/doc operation to delete the document. expiration time wont be available if we delete doc using DELETE /db/doc. how to retain the expiration value after DELETE /db/doc operation so that document get purged after expiration time of document which has _deleted=true.

**Comment by adamcfraser** [comment]
There's no way to set an expiry on a DELETE /db/doc operation.  As mentioned, you can accomplish the desired result by switching your DELETE /db/doc operation to an PUT or POST to /db/doc, and setting _deleted:true and the _exp value in the document body.

It might be a reasonable enhancement to support an _exp property on the DELETE /db/doc operation.  However, I don't expect we'll support carrying forward an existing expiry value to a DELETE that doesn't otherwise specify expiry.  Since DELETE is really just another revision, expiry needs to be explicitly specified for that revision.

**Comment by ArihantRk** [comment]
Thanks @adamcfraser  for the update. it was helpful

**Comment by adamcfraser** [comment]
When running with enable_shared_bucket_access:true, tombstone cleanup is automatically covered by the server's metadata purge interval.  Closing this ticket, as there aren't plans to add additional support beyond what's described above.
