### ISSUE TITLE
Feature Request to change Sync-Gateway session cookie name

### ISSUE THREAD

**Issue by PureRockets** [couchbase/sync_gateway#2096]
This is an ask to be able to change sync-gateway session cookie name from 'SyncGatewaySession' to something else. A customer may wish to host multiple databases with the same domain name. They need a session to each of the databases and one domain cannot have multiple cookies with same name. Each user needs to be able to sync his/her data from browser (let's say using PouchDB) to sync-gateway. So each user gets a session from sync-gateway admin port and add a cookie in browser. but the problem is the cookie name is same for all buckets. In browser the cookie name must be unique per domain.

**Comment by adamcfraser** [comment]
Cookies aren't restricted to domain only - cookies can be associated with both domain and path.  That's the case for SetCookie responses returned by Sync Gateway - the Path property is included, so it should be straightforward for clients to differentiate between session tokens assigned to different databases running on the same domain using the path.

**Comment by monkeyalive** [comment]
We can set the cookies with same name but different path and able to sync data to sync-gateway, but when the user logs out (let's say via a backend server, not sync-gateway), those cookies with different path are not being sent to backend for invalidation, because browser sends cookies that match the logout request path or empty path.

So have a feature to customize cookie name and set them in browser with empty path ('/') will help applications that are planning to use multiple databases (like us).

**Comment by monkeyalive** [comment]
That would be removing the following hardcoded const in /auth/session.go and reading the name from 'sync-gateway.json' 
const CookieName = "SyncGatewaySession"

**Comment by monkeyalive** [comment]
you make wanna take a look at this. **DELETE /{db}/_user/{name}/_session**. Looks like this REST will delete all sessions for the user and this may work for logout scenarios to kill all user's sessions without tracking individual sessionIds (only if sync-gateway nodes and buckets are same? which may not solve the problem here?). 

https://developer.couchbase.com/documentation/mobile/1.3/references/sync-gateway/admin-rest-api/index.html#!/session/delete_db_user_name_session

It may be possible to to achieve this, but might be tricky.

**Comment by tleyden** [comment]
## Requirements

- [ ] Add new optional per-DB configuration value `session_cookie_name` 
- [ ] [Update docs](https://github.com/couchbaselabs/couchbase-mobile-portal/pull/834)
- [ ] Create unit test that has custom config and ensures correct cookie name is used
