### ISSUE TITLE
Query channel(s) flexibility and/or wild cards(Ranged)

### ISSUE THREAD

**Issue by househippo** [couchbase/sync_gateway#2156]
I'm hearing from people asking for flexibility in read filtering
```
{
"_id":"1",
"channels":["A"]
}
{
"_id":"3",
"channels":["A","B","C"]
}
```

currently filter by channel is a OR operation
Example  "A" or "C" channels
?filter=sync_gateway/bychannel&channels=A,C
the above would give you both documents.

They are asking for an intersection of the "A & C"
?filter=sync_gateway/bychannel&channels=A**&**C

so that their results will only get them doc "_id":"3"

True they could just ask for channel "B", but in this case "B" would be equal to a channel called "AC".

Only worry is that a "AC" method could lead too many permutations of channels:  AB , AC , AD , BC , BZ , ABC, ABD ... etc

**WILD CARD or RANGED**
 
?filter=sync_gateway/bychannel&channelsStart=A&channelsEnd=Azzzz

So this would get channels "A"  and "AC"   but not "D"

**Comment by gtur-disney** [comment]
May I request a more flexible structure, something like: (A|B)&!C. With the current approach, our permutations are running into hundreds of combinations.

**Comment by adamcfraser** [comment]
Typically this type of complex filtering would be done using a query against the local database, and not via replication-time filtering.  

If it's actually a security concern, the usual recommendation would be as described - build the logic to calculate the permutations of channels into the sync function (so that documents are getting written to channels A, C, and AC).  This would allow you to grant the channels A, C or AC as appropriate.

However, I'd like to better understand the use case: what problem are you hitting because this type of changes request isn't currently possible?

**Comment by adamcfraser** [comment]
Closing based on age.
