### ISSUE TITLE
How to verify Firebase ID Tokens

### ISSUE THREAD

**Issue by mockitor** [couchbase/sync_gateway#2189]
i want to [verify](https://firebase.google.com/docs/auth/admin/verify-id-tokens) Firebase Auth Token with Sync Gateway. is there a Firebase oidc provider ? 

Firebase auth suggests Firebase Admin SDK or third party JWT libraries to verify their ID tokens. how can i implement firebase token authentication which is implicit flow auth ?  

Can you provide a working Firebase Token authentication (JWT) example  ?

**Comment by jade-42** [comment]
Firebase's Authentication is really nice looks like it would be a good fit for authentication with the Sync Gateway. @mockitor were you able to find an answer?

**Comment by adamcfraser** [comment]
Closing based on age.

**Comment by MSchmack** [comment]
@adamcfraser still relevant. Saw a similiar question on the Couchbase forum. I think it's referring to the implicit oidc configuration mentioned in the [couchbase doc](https://docs.couchbase.com/sync-gateway/current/authentication.html#openid-connect). An example config with firebase and perhaps another big auth provider like azure ad / Amazon cognito would help.  What probably confuses is the need for the client ID for a service that only authenticates the token.

Here's how an example for the service hasura looks when authenticating against firebase Auth.
 
{ "type":"RS256", "jwk_url": "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com", "audience": "<firebase-project-id>", "issuer": "https://securetoken.google.com/<firebase-project-id>" }

**Comment by function1983** [comment]
Luckily I found a way that works. I just want to share with anyone who faces the same issue.
- The problem is firebase id_token is not (and most likely will never be) signed since google also offers Google Identity Service.
- You need a translation layer, I use Keycloak because of reasons (open source, ability to run as standalone in docker container, multi-tenant, and flexibility just to name a few).
- Since both Firebase Auth and Keycloak have their official nodejs SDKs, its very convenient to link those two services together.
- You now have unsigned firebase id_token in, fully signed Keycloak id_token out.
- Put your keycloak oidc credentials into sync gateway configuration file as instructed. It's a long read, you should end up with just 5 to 10 configuration lines of code. If you are lazy, just copy from the screenshot I posted on Stackoverflow. [https://developer.couchbase.com/tutorial-syncgateway-openid-auth](url)
- Sync gateway should accept your Keycloak id_token and issue a proper session cookie.

I have to admit, it is quite involved to set up the whole system to work correctly and fit your needs. I have a few screenshots if anyone interested. [https://stackoverflow.com/questions/41540402/how-to-use-firebase-authentication-in-couchbase-sync-gateway/69712627#69712627](url)
