### ISSUE TITLE
log rotation based on maxsize does not work on Windows

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/sync_gateway#2242]
### Sync Gateway version
1.4-42

### Operating system
Win 10

### Config file
```
{
  "logging": {
    "default": {
      "logFilePath": "C:\\Program Files (x86)\\Couchbase\\var\\lib\\couchbase\\logs\\sync_gateway_error.log",
      "logKeys": ["*"],
      "logLevel": "debug",
      "rotation": {
        "maxsize": 1,
        "maxage": 30,
        "maxbackups": 2,
        "localtime": true
      }
    }
  },
  "databases": {
    "db": {
      "server": "http://<Server_IP>:8091/",
      "bucket": "default",
      "users": {"GUEST": {"disabled": false,"admin_channels": ["*"]}}
    }
  }
}

```

### Expected behavior
- After the log file hits 1MB, the log should get backed up.
- A new empty log file should get created and any new logs should get logged in the new log file.

### Actual behavior
- After the log file hits 1MB, logging stops in sync_gateway_error.log.
- No backup logs are created.
- Any new logs are lost.

### Steps to reproduce
1.  Use the above config for sync gateway and restart sync gateway service.
2.  From a remote system execute this command on multiple terminals in parallel, where Sync_Gw_IP is the IP address of the windows system where sync gateway is running
```
for ((i=1;i <= 10000;i += 1)); do curl -s http://<Sync_Gw_IP>:4984/ > /dev/null ; done
```
3.  Wait for the log file size to hit 1MB.

**Comment by ajres** [comment]
I am unable to reproduce this issue, one issue I did see the logFile path shown in the config above requires Administrator privilages to write to.

I think this is caused by running Sync Gateway using the Windows Service wrapper.

Please retest with a logFilePath outside of the Couchbase installation.

OS Windows 8

Definition of 1MegaByte = 1048576 Bytes 

Sync Gateway config:

```
{
	"adminInterface": "127.0.0.1:4985",
	"databases": {
		"db": {
			"server": "walrus:data",
			"users": {
				"GUEST": {"disabled": false, "admin_channels": ["*"] }
			}
		}
	},
	"logging" : {
	    "default": {
		  "logFilePath": "C:/var/tmp/sync_gateway.log",
		  "logKeys": ["*"],
		  "logLevel": "debug",
		  "rotation": {
		    "maxsize":1,
			"maxage":30,
			"maxbackups":2,
			"localtime": true
		  }
		}
	}
}
```
I have tested the following scenarios

1) Start Sync Gateway with log rotation MaxSize = 1 and a log file that is already over 1MB

Expected Result: Existing log will be immediately rotated out of the way and a new empty log file created.

Actual Result: Existing log was be immediately rotated out of the way and a new empty log file created.

2) Start Sync Gateway with log rotation MaxSize = 1 and a log file that is under 1MB

Expected Result: The existing log will remain in place until enough additional characters have been written to the log to increase the size > 1M. The log file will then be rotated out of the way and a new log file created.

Actual Result: The existing log remained in place until enough additional characters were written to the log to increase the size > 1M. The log file was then be rotated out of the way and a new log file created.

3) Start Sync Gateway with a log file that is exactly 1M in size.

Expected Result: When Sync Gateway attempts to write the initial banner line to the log i.e. the line containing "Couchbase Sync Gateway/1.4(42;9f28d6b)" this will cause the existing log to be rotated out of the way as it is already 1M. A new log file will be created and the banner line will be written to that log file.

Actual Result: When Sync Gateway started it caused the existing log to be rotated out of the way. A new log file was created and the banner line was written to that log file.

**Comment by raghusarangapani** [comment]
"C:\\Program Files (x86)\\Couchbase\\var\\lib\\couchbase\\logs\\sync_gateway_error.log" is the default logfile to which sync gateway writes to. I will test other paths and update

**Comment by raghusarangapani** [comment]
Rotation works with these logfile paths:
```
C:\sg logs\sync_gateway_error.log, 
C:\sg_logs\sync_gateway_error.log, 
C:\sg (x86) logs\sync_gateway_error.log
```
No rotation:
```
C:\Program Files (x86)\Couchbase\var\lib\couchbase\logs\sync_gateway_error.log
```

This path is automatically created at install time. Should we not be creating this path then?

**Comment by raghusarangapani** [comment]
With ```C:\Program Files (x86)\Couchbase\var\lib\couchbase\logs\sync_gateway_error.log``` as the logfilepath, if I delete the sync_gateway_error.log and restart the sync gateway service, a new sync_gateway_error.log gets created. So we must have the privileges to create the file. Probably the rotation is not done with the right privileges?

**Comment by ajres** [comment]
@raghusarangapani it looks like you can't get log rotation to work at all on your system. Lets plan to do a screen share to try and understand the issue you are seeing.

**Comment by ajres** [comment]
@raghusarangapani I have been able to reproduce an issue with the log rotation when SG is run from the service wrapper. I'll debug and fix the issue from this end and update here when I have a solution.

**Comment by raghusarangapani** [comment]
Log rotation works with the below config format:
```
"logFilePath": "C:/Program Files (x86)/Couchbase/var/lib/couchbase/logs/sg_log_rotation.log",
```

**Comment by ajres** [comment]
The service wrapper is using the `C:\\Program Files (x86)\\Couchbase\\var\\lib\\couchbase\\logs\\sync_gateway_error.log` path as output for anything that is written to Sync Gateway's stdout since the service has no console. This will interfere with the logrotation trying to write to the same file. From the last comment by @raghusarangapani. I think we should recommendation that if users want to write to the same folder they should use a differenet file name e.g. sync_gateway.log

**Comment by raghusarangapani** [comment]
Confirming that rotation does not work with the below format:
```
"logFilePath": "C:/Program Files (x86)/Couchbase/var/lib/couchbase/logs/sync_gateway_error.log"
```

**Comment by ajres** [comment]
Added notes to log rotation docs in this PR

https://github.com/couchbaselabs/couchbase-mobile-portal/pull/545
