### ISSUE TITLE
Skipped sequences appearing under heavy load, not being seen

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#2257]
During client testing, @borrrden has one test that periodically ends with skipped sequences (n::m format).  Would like to investigate the root cause - whether it's slow TAP feed, coalesced feed entries, or something else.

**Comment by borrrden** [comment]
The test being run is a test called `test_client_to_sync_gateway_complex_replication_with_revs_limit`.  Here are the [logs](https://github.com/couchbase/sync_gateway/files/733882/test_client_to_sync_gateway_complex_replication_with_revs_limit-2017-01-26-10-02-15-sglogs.zip) from the run from SG.

The test performs the following actions:

- Create a user and session
> POST http://10.17.2.201:4985/db/_user/ 201
POST http://10.17.2.201:4985/db/_session 200

- Create a client DB, add 10 documents, and start a continuous push replication
- Verify that SG received the 10 documents
> POST http://10.17.2.201:4985/db/_bulk_get 200

- Update each document 100 times through SG REST
- Update each document 100 times on the client
- Start a continuous pull replication
- Wait for both replications to become idle
- Verify that each document only has 20 revisions (due to auto pruning) on the client
- Verify that each document only has 100 revisions on SG
> GET http://10.17.2.201:4984/db/ls_db_0?conflicts=true&revs=true

- Delete conflicts on the client caused by the previous concurrent updating
- Verify that the document still has a generation of 101 (deletions cannot win) on both client and SG
- Delete the new winning revision (resulting in a deleted document) and verify 404 on client and SG
- Add 10 documents with the same names as the just deleted ones
- Update each document 100 times on the client
- Verify the new generation (203-) on the client
- Compact the client database
- Verify that each document only has 20 revisions on the client
- Stop the push and pull replication and wait for them to finish
- Delete any remaining conflicts on client and SG
- Delete the documents on the client
- Start a new continuous push and pull replication
- Verify that the documents are deleted on client and SG (this test run failed here because one document remained on the client but that seems like a client problem)

I notice that SG goes from 

> 2017-01-26T17:59:10.402Z Changes+: MultiChangesFeed sending &{Seq:1 ID:_user/sg_user Deleted:false Removed:{} Doc:map[] Changes:[map[rev:]] Err:<nil> allRemoved:false branched:false}·

to

> 2017-01-26T17:59:10.415Z Changes+: MultiChangesFeed sending &{Seq:1067::1203 ID:ls_db_0 Deleted:false Removed:{} Doc:map[] Changes:[map[rev:101-b9d8c2c413f3849a47c0cddfa363ec05] map[rev:101-56a8da0f8c2414adc60a28cf79957735]] Err:<nil> allRemoved:false branched:true}·

It seems that `#1068` is holding up the show.

**Comment by adamcfraser** [comment]
I suspect this may be fixed by https://github.com/couchbase/sync_gateway/issues/2365

@borrrden Let me know if we can close, and reopen if you continue to see this after moving to the latest SG build.

**Comment by borrrden** [comment]
That seems fine by me.  I don't think we will have the intense testing sessions we had when we were uncovering this for a while, but I'm sure either @sethrosetter or I will remember if we see it again.
