### ISSUE TITLE
sg-replicate can not scale horizontally

### ISSUE THREAD

**Issue by ArihantRk** [couchbase/sync_gateway#2264]
### Sync Gateway version
1.3.1
### Operating system
RedHat 7.2
### Config file
"replications":[
   {
               "replication_id":"C2_C1",
               "source": "default",
               "target": "http://localhost:4985/default/",
               "continuous":true,
               "changes_feed_limit":1000
    }
### Expected behavior
By adding a nodes to sg-replicate cluster, sg-replicate should scale horizontally. replication should happen in load balanced manner

### Actual behavior
All sg-replicates are doing duplicate. Each of them trying to replicate same documents from _sync:seq =zero. Throughput is not increasing.

### Steps to reproduce
1.  Run a single sg-replicator with above configuration and run traffic
2.  Add a replicator with same config as above and run traffic

**Comment by tleyden** [comment]
Very interesting ticket!  This has been discussed internally and there is an amorphous plan to re-architect it to scale horizontally.

I'm very curious to hear what your requirements are:

- Fault tolerance / High availability (in case one sg-replicate node goes down, there are others)
- Config symmetry (no need for sync gateways to have separate configs)
- Higher throughput (one sg-replicate node can't keep up with throughput)

Which of those are most important to you -- or are there others that aren't listed?

**Comment by ArihantRk** [comment]
As a system we would need both Fault tolerance and Higher throughput.  sg-replicate should be scaled equally as syncgateway does so that there will not be any lagging in replication.

**Comment by ArihantRk** [comment]
@tleyden , any luck ?

**Comment by kirangandhi** [comment]
Any plan to fix this in 1.5.0?

**Comment by tleyden** [comment]
@kirangandhi this isn't on the 1.5 roadmap as far as I know, but there have been discussions on how to re-architect sg-replicate to be tighter integrated with Sync Gateway Accelerator and be distributed by default.

In the meantime, for the higher throughput side of things, I think the bottleneck might be on the Sync Gateway side of the equation rather than the sg-replicate side of things, since sg-replicate is doing so little work in comparison to Sync Gateway.  However, if you have any repro steps that show otherwise, please post to this ticket.  Maybe sg-replicate could be tuned for higher throughput.  

For fault tolerance, you could setup a "hot standby" system -- where if the primary sg-replicate process fails, that is detected and a sg-replicate process is started on the standby system.

**Comment by ghost** [comment]
We are into same problem where the sync gateways are running on open shift and now we need to do 2 deployments one for SG replicate and one for apps. Because if we have the same config on all 3 pods then the data will travel 3 times for replication. And the network in our Use case is very very expensive. Secondly the SG which is doing replication if goes down then the high availability issue is also there.

**Comment by adamcfraser** [comment]
Closing based on age - many scalability enhancements since this release, additional sg-replicate enhancements planned for Hydrogen.

**Comment by kirangandhi** [comment]
@adamcfraser, Is SG replicator scaling issue is resolved in 2.6 or 2.7? I don't see this is getting addressed in 2.6 also. Any roadmap available?

**Comment by bbrks** [comment]
@kirangandhi We're currently working on a set of sg-replicate enhancements intended to provide HA, and a new replication protocol that supports delta sync.
