### ISSUE TITLE
docs not replicating when modifying sync function and _resync-ing

### ISSUE THREAD

**Issue by stemail23** [couchbase/sync_gateway#2346]
I have observed that if I modify the sync function such that more existing documents are now included in an existing channel, and then execute a _resync, then existing clients with an existing pull replication on this channel will not pull replicate the new docs now included in the channel.

If I make a change to one of the docs then the new revision is replicated down to the client.

Starting replication on this channel from a new client will include all the new docs in the channel.

This feels like a bug to me. Is it, or is my understanding of expected behaviour incorrect?

Couchbase 4.6.0
Sync Gateway 1.3.1.1
OSX 10.12.2

**Comment by adamcfraser** [comment]
Resync rewrites channel access without modifying sequence numbers and forces recalculation of channel access all users/roles, but doesn't invalidate existing replication checkpoints (_local docs).

This would explain the behaviour you're seeing - it means that existing pull replications will continue from the since value at which they left off, and not see any new documents until they are modified and get a newer sequence value.

The challenge with fixing this is that checkpoints are opaque to Sync Gateway, and don't look any different than other _local documents written by clients.  I don't think that Sync Gateway (today) has a way to identify and delete these.  @snej - let me know if that's correct, or if there is actually a way for SG to differentiate between checkpoint and non-checkpoint _local docs written by Couchbase Lite.

**Comment by adamcfraser** [comment]
Closing based on age.  Might be best considered as part of admin functionality to force removal of all checkpoint documents, but pending prioritization.
