### ISSUE TITLE
SG collect info is not case sensitive on the config's logFilePath property

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#2400]
A recent sgcollectinfo submission wasn't able to retrieve the logs from a custom location, even though that location was specified in the config.

running_server_config.log included the following:
`"logfilepath": "/var/log/syncgateway_log", `

sync_gateway_error.log doesn't show this path in the list of paths attempted for log retrieval.

**Comment by tleyden** [comment]
It looks like the issue is that it's looking for it under `logging`

In [these docs](https://developer.couchbase.com/documentation/mobile/1.4/guides/sync-gateway/config-properties/index.html) I see 

```
  "logFilePath": "string",
  "logging": {
    "default": {
      "logFilePath": "string",
```

I don't know if that means that the `logFilePath` can be either at the top level *or* under logging, or both.

In any case when I tried with this `_config`:

```
{
    "Interface":":4984",
    "AdminInterface":":4985",
    "log":[
        "*"
    ],
    "logFilePath":"/Users/tleyden/Development/sync_gateway/logfile",
    "Databases":{
        "db":{
            "server":"http://localhost:8091",
            "pool":"default",
            "bucket":"db",
            "name":"db",
            "users":{
                "GUEST":{
                    "name":"",
                    "admin_channels":[
                        "*"
                    ],
                    "all_channels":null,
                    "disabled":true
                },
                "foo":{
                    "name":"foo",
                    "admin_channels":[
                        "*"
                    ],
                    "all_channels":null,
                    "password":"bar"
                }
            },
            "allow_empty_password":true
        }
    }
}
```

and tried manually calling the sgcollect_info python function:

```
guessed_logging_path = sgcollect_info.extract_element_from_default_logging_config('LogFilePath', config_str)
```

I got an empty response.

From looking at the code, it looks like [sgcollect](https://github.com/couchbase/sync_gateway/blob/master/tools/sgcollect_info#L210) expects it under `logging` and not at the top level

**Comment by adamcfraser** [comment]
It looks like it's still trying to check the top-level location here:

https://github.com/couchbase/sync_gateway/blob/master/tools/sgcollect_info#L250

**Comment by ajres** [comment]
The issue is related to the format of the _config, response.

top level "logFilePath" property is returned as "logFilePath"

logging config "logFilePath" property is returned as "LogFilePath"

I think this is due to the definition of the `struct`s used to unmarshal the config.

One way to fix this is to change sgcollect_info (my line 250)

```
# Find log file path from old style top level config
    guessed_log_path = extract_element_from_config('LogFilePath', config_str)
```

to

```
# Find log file path from old style top level config
    guessed_log_path = extract_element_from_config('logFilePath', config_str)
```

This line has not bee changed in the last few releases, so either this did not work before, or the config struct definitions have been updated and not picked up as a regression for sgcollect_info.

**Comment by adamcfraser** [comment]
Go's JSON unmarshal doesn't enforce case sensitivity, so `logFilePath` and `LogFilePath` would both be valid.  In the config related to this issue, it was showing up as `logfilepath`.

Can we enhance extract_element_from_config to ignore case?
