### ISSUE TITLE
Deferred attachment download issue with sync gateway

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2621]
From @tophatch in a [forum post](https://forums.couchbase.com/t/deferred-attachment-download-issue-with-sync-gateway/13043)

--------------

We made a [change in couchbase lite](https://github.com/tophatch/couchbase-lite-ios/commit/5e4909f89a88b6fdea7c277ddcdbfa35974b6229) that fixed issues with deferred download of attachments. This is mostly working in production, except for one issue we have come across. Here are the steps…

1. Pull from server, but don’t download attachments
1. Change a document locally (but do not push changes)
1. Attempt to download attachment on changed document

Step 3 fails with 404 missing as the revision id is unknown to sync gateway. It seems that in this circumstance that sync gateway should return the attachment for the last known revision. We made a quick [change](https://github.com/tophatch/sync_gateway/commit/da15d84aa0cd153e4349b87f2aa1327531b692e1) to validate this works. Any thoughts on whether this is the right approach?

It seems reasonable to me that in the case that the client does not have an attachment and asks the server then the best the server can do is return the attachment for the latest revision. 

--------------

**Comment by adamcfraser** [comment]
If a client is explicitly specifying the revision when requesting an attachment, and that revision doesn't exist, I don't think Sync Gateway should assume they want the active revision.  If the active revision is desired, clients can already just omit the rev parameter.

**Comment by combinatorial** [comment]
How does the client know to omit the revision id from the request? It can't know if it has the active revision or not. It just knows it doesn't have the attachment. The only data it could provide is the revpos of the attachment, but I don't think it knows the revision id associated with the revpos.

**Comment by adamcfraser** [comment]
My point is that rev is already an optional parameter on getAttachment.  The expectation is that if a client is specifying a revision ID, they are trying to request an attachment associated with that particular revision.  I don't think it's appropriate for Sync Gateway to return an attachment when the revision is invalid - it implies the existence of a revision that Sync Gateway doesn't actually know about.

It could also be the case that the document has been updated on the server, so that the attachment being returned isn't the same one the client thinks it is requesting.

If the client is attempting to defer retrieval of an attachment, I think it needs a way to request the attachment based on the revision that it was originally associated with.  Using revpos would be one approach - the revpos should be the generation of the active revision's direct ancestor that originally had the revision, so it should be possible to look up that revision in its rev tree.

**Comment by combinatorial** [comment]
That makes sense. My knowledge of couchbase lite is a bit limited to be sure whether it will always work. It looks like the revision history on iOS in our test case always extends back to before the attachment's revpos, is this just luck, or is this guaranteed to be true?

**Comment by adamcfraser** [comment]
I don't know whether lite does revpos handling during revtree pruning to ensure revpos references non-pruned revisions.  @snej or @pasin - do you know?

**Comment by combinatorial** [comment]
I modified couchbase lite to request the specific revision that matches revpos, and when I do this, every attachment request fails, unless the revision id matches the latest revision on the server. Here are the changes in `- (NSProgress*) downloadAttachment: (CBLAttachment*)attachment`. 

    //find revision that matches revpos
    CBLRevision *revision = attachment.revision;
    NSString *attachmentRevposString = attachment.metadata[@"revpos"];
    NSInteger attachmentRevpos = attachmentRevposString.integerValue;
    while (revision != nil) {
        NSArray *revisionComponents = [revision.revisionID componentsSeparatedByString:@"-"];
        NSParameterAssert(revisionComponents.count == 2);
        if (revisionComponents.count < 2) {
            revision = attachment.revision;//something went wrong, revert to original behavior
            break;
        }
        NSString *revisionRevposString = revisionComponents[0];
        NSInteger revisionRevpos = revisionRevposString.integerValue;
        if (revisionRevpos == attachmentRevpos) {
            NSLog(@"Found matching revpos");
            break;
        }
        revision = revision.parentRevision;
    }
    if (revision == nil) {
        revision = attachment.revision; //something went wrong, revert to original behavior
        NSLog(@"Warning: failed to find matching revpos");
    }

    NSLog(@"Original attachment revision: %@\nRevpos: %@\nRequesting revision: %@", attachment.revision.revisionID, attachmentRevposString, revision.revisionID);
    
    CBL_AttachmentID *attID;
    attID = [[CBL_AttachmentID alloc] initWithDocID: attachment.document.documentID
                                              revID: revision.revisionID
                                               name: attachment.name
                                           metadata: attachment.metadata];


When we run this code, we see `Found matching revpos` and it is generating revisions that match the revpos for the attachment. And on sync gateway we have checked the requested revisions are contained in the history by examining the raw document. The failure is `missing`, and it fails in the call to `body, err := h.db.GetRev(docid, revid, false, nil)` inside `handleGetAttachment`. If I understand correctly the look up of that document revision is failing. Any ideas why that might be happening?

**Comment by combinatorial** [comment]
Wondering if this is the right track, we found a patch for a similar issue...

https://github.com/couchbase/sync_gateway/pull/1725/commits/4d5be0c6d56d4b4a9d28a0f9315e3da7190e6620

Do we have to look through ancestors of the revision until we find one that has not been pruned and return that?

**Comment by adamcfraser** [comment]
Ah right - if the revpos ancestor revision isn't recent (i.e. it's not resident in the rev cache, or still be available as a temporary backup), Sync Gateway isn't going to be able to find that revision.  Using revpos doesn't accomplish the real goal - retrieval using the revid that was last replicated from SG to the client.

So that I better understand the problem, how long are you typically planning to defer attachment retrieval?  Until there's a request to access the particular attachment by the user?

**Comment by combinatorial** [comment]
In our case the problem is fairly immediate. We are using one-way sync to pull data, but in some cases a modification has been made to a document locally. We resolve that conflict by using the server version, but that creates a new revision locally. So, for the documents that had a local change, the attachment download always fails.

**Comment by adamcfraser** [comment]
Reviewed with @snej and @pasin, and this sounds like an issue that needs to be addressed on the Lite side.  Filed https://github.com/couchbase/couchbase-lite-ios/issues/1780
