### ISSUE TITLE
Removing users from channels does not remove documents

### ISSUE THREAD

**Issue by jnordberg** [couchbase/sync_gateway#264]
I'm building a test app to try to get my head around the channels and roles thing.

The app just has a list of documents and the sync gateway is using the default sync function.

Each user has is assigned an admin_channel with the same name as their username. And when a user creates a document it is created with 2 channels, their username and a 'admin' channel. I have also created an admin role with `admin_channels: ['admin']`.

So far so good, when i create new documents they get synced to all users with the admin role, and when i assign the admin role to a user their documents list get populated with all documents.

The problem is when i remove the admin role from an user, they still have all the documents (or at least they don't get notified that the documents have been removed, i.e. my live query does not get triggered) and they can still modify them and the changes propagate.

Am i missing something or is this a bug?

**Comment by vbenso** [comment]
Any update on this?

**Comment by atom992** [comment]
I do agree the following point:
CBL doesn't know what channels docs are in. That information only lives on the server.
and at the same time,If you loss access to a channel,you client should know which docs should be removed.

so I think a feasible solution is:
If you loss access to a channel:
1. you should removed the docs which should be removed in the CBL manually  ;
2. in your sync function, you should add requireAccess(channel) in the doc which might be removed in the CBL, so If you loss access to a channel, and you deleted the docs in CBL, the docs in Sync Gateway will not be deleted.

**Comment by ajres** [comment]
An additional use case from [this](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/mobile-couchbase/scBfRI7eeIA/zDPqbgKPAuQJ) thread.

If there is a single document that is mapped to a channel and also gives a user access to that same channel.

If the document is deleted, the deleted revision is never sent to any _changes feed as the users access to the channel is removed before the deleted rev is sent to any active _changes feed.

Also if an offline user had an earlier revision of the doc, if they start syncing again at a time after the _deleted revision has been written to sync gateway, they will not see any active revisions for that document either.

**Comment by elevine** [comment]
From https://groups.google.com/d/msg/mobile-couchbase/scBfRI7eeIA/rvPv9Qpc2eAJ:

**Comment by ddash1** [comment]
@zgramana Is this still target 1.2

**Comment by tommyo** [comment]
According to http://developer.couchbase.com/documentation/mobile/1.1.0/develop/guides/sync-gateway/sync-function-api-guide/routing/index.html

> If the document was previously routed to a channel, but the current call to the sync function (for an updated revision) doesn't route it to that channel, the document is removed from the channel. This may cause users to lose access to that document. If that happens, the next time Couchbase Lite pulls changes from the gateway, it will receive an empty revision of the document with nothing but a "_removed":true property. (Of course the previous revisions of the document remain in your Couchbase Lite database until it's compacted.)

Does that mean this feature is now working as requested by the OP? Or are the docs wrong?

Or does it only apply to docs updated after the sync logic was modified? It's pretty unclear.

**Comment by petr-vysotskiy** [comment]
Hi! Is there a fix/workaround for that?

**Comment by tleyden** [comment]
Here are a few workaround scenarios that I put together w/ @adamcfraser.  Hopefully at some point a more refined version of these will make it into our official docs.  

The examples center around hypothetical Sales Associates, Sales Managers, and Sales Leads, and hopefully map easily to common data models.  The formatting is a bit rough since they are just sketches at this point.

@jnordberg @petr-vysotskiy @TommyO @atom992 -- would love to hear feedback on what does and doesn't make sense with these examples!

## Scenario + Workaround #1: Sales Associate Promotion + Demotion

![sales_associate_promotion_demotion_scenario_and_workaround](https://cloud.githubusercontent.com/assets/296876/25446806/9699d55c-2a67-11e7-9267-bbd3b899b667.png)

**Comment by tleyden** [comment]
## Scenario + Workaround #2: Sales lead assigned to Sales Associate and later un-assigned

![sales_lead_assignment_unassignment_scenario_and_workaround](https://cloud.githubusercontent.com/assets/296876/25446888/d5c20808-2a67-11e7-8543-d9054251bea4.png)

**Comment by jamesnocentini** [comment]
- workaround 1

  It should just work and doesn't require any data modeling changes to make it work which is nice! The use of a 3rd channel acts as the mechanism to send the revision one last time to the user that lost access so it can clean its own database.

- workaround 2

  Not sure I follow all of it. But isn't this approach relying on the fact that the database change listener on CBL would bubble up a revision with `"removed": true`? I don't think that's the case at the moment so the application doesn't know when that revision is received.

**Comment by jnordberg** [comment]
AFAIK the solution we ended up using was very similar to workaround 1, I've since left the company but the @safetyculture guys might have some input, ping @dancet @tjdavey :wave:

**Comment by tleyden** [comment]
> workaround 2

> Not sure I follow all of it. But isn't this approach relying on the fact that the database change listener on CBL would bubble up a revision with "removed": true? I don't think that's the case at the moment so the application doesn't know when that revision is received.

The difference is essentially the following:

1. In the problem scenario of "Scenario + Workaround #2"
 the sales associate is being dynamically added and removed from channels via the admin REST API.  This has issues, because when they are removed from a channel, their already sync'd docs remain visible in their local couchbase lite database since there is currently no mechanism to signal this over the `_changes` feed.

1. In the workaround for  "Scenario + Workaround #2", the modeling is flipped around so that sales associates have much more static assignment to their channels, for example SA1 is assigned to the SA1_Leads channel at the point that the SA1 user is created, and this channel assignment never changes.  Docs will then move in and out of these static channels, and so the time sequence of events is that:
    1. A lead is assigned to SA1 (and possible other SA's), and so the sales lead doc is updated with `channels: ["SA1_Leads", etc.. ]` and so the lead appears on SA1's Couchbase Lite database
    1. That lead is later *unassigned* from SA1 and all other sales associates, and so the sales lead doc is updated with `channels: []`.  At this point the lead will disappear from SA1's Couchbase Lite instance, due to the fact that it will receive a `_removed` flag for that sales lead, which tells it to basically locally purge the doc from the couchbase lite database.

**Comment by geraldapeoples** [comment]
Workaround 1 does not work with the current versions of software - couchbase 5.0.1, sync gateway 1.5.1 and couchbase lite 1.4.1.

- Assign user to channel works perfectly and the user receives the docs from that channel.
- Unassign user from channel works, the user no longer receives changes from documents in the channel.
- The mobile database now contains documents from the channel that they were removed from
- THE BROKEN BIT - deleting the documents that are in the channel the user was removed from on the mobile app deletes the document from the sync gateway

Is this a bug? or has the expected behavior changed?

**Comment by geraldapeoples** [comment]
Please ignore my previous email ... I updated the sync gateway config to have a sync function which includes a RequireAccess function for the documents current channels and the delete from the mobile device does not delete the doc from the gateway. This in co-ordination with the purge document works a treat :o)

**Comment by tleyden** [comment]
@geraldapeoples glad to hear!

**Comment by adamcfraser** [comment]
Moved to https://issues.couchbase.com/browse/CBG-639
