### ISSUE TITLE
Configurable View Timeout: SG responding gracefully when the data is being rebuild should be configurable (enable/disable)

### ISSUE THREAD

**Issue by ArihantRk** [couchbase/sync_gateway#2699]
### Sync Gateway version
1.4.1

 ### Expected Behavior:
SG responding gracefully during data rebuild should be configurable to enable or disable this feature. When disabled, it should fallback to existing behavior. 
 
 ### Actual Behavior
 Requests to syncgateway nodes are getting hung/not responding/timeout during couchbase views rebuilding

**Comment by tleyden** [comment]
Thanks @ArihantRk, this sounds like it would be an improvement.

Can you provide high level steps to repro here?  (or link to another ticket with clear steps to repro?)

**Comment by kirangandhi** [comment]
@tleyden, Our understanding from the support discussion is sync gw hanging during view rebuild is getting fixed by timing out. So we wanted to make timeout as configurable and we should be able to fall back to hung behaviour if fix is not stable. Not sure what reproduction steps we need to provide here.

**Comment by djpongh** [comment]
See #2639
