### ISSUE TITLE
Security Scan [ scanned through zap]" X-Content-Type-Options Header Missing on sync gateway

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/sync_gateway#2711]
**Here is the request** : GET http://192.168.33.11:4984/ HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0
Pragma: no-cache
Cache-Control: no-cache
Content-Length: 0
Host: 192.168.33.11:4984
### Sync Gateway version
1.5
### Operating system
The operating system you're running Sync Gateway on.

### Config file
```{
    "interface":":4984",
    "adminInterface": "0.0.0.0:4985",
    "maxIncomingConnections": 0,
    "maxCouchbaseConnections": 16,
    "maxFileDescriptors": 90000,
    "slowServerCallWarningThreshold": 500,
    "compressResponses": false,
    "log": ["*"],
    "databases":{
        "db":{

            "unsupported": {

            },
            "server":"http://192.168.33.10:8091",
            "bucket":"data-bucket",
            "username":"data-bucket",
            "password": "password"
        }
    }
}

```

**Comment by sridevi-15** [comment]
[sync-gateway-1.5-xcontentTypeMissing.html.zip](https://github.com/couchbase/sync_gateway/files/1132743/sync-gateway-1.5-xcontentTypeMissing.html.zip)

**Comment by adamcfraser** [comment]
Additional specifics from report:
The Anti-MIME-Sniffing header X-Content-Type-Options was not set to 'nosniff'. This allows older versions of Internet Explorer and Chrome to perform MIME-sniffing on the response body, potentially causing the response body to be interpreted and displayed as a content type other than the declared content type. Current (early 2014) and legacy versions of Firefox will use the declared content type (if one is set), rather than performing MIME-sniffing.

**Comment by tleyden** [comment]
From https://security.stackexchange.com/questions/147554/security-headers-for-a-web-api:

> If you're running a JSON API you should serve the responses with Content-Type: application/json. If you do that correctly there will be no need to add the nosniff directive.
