### ISSUE TITLE
Add Sync Gateway version/build to DCP HELLO string

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#2747]
Allows us to determine SG version from server logs.

https://issues.couchbase.com/browse/MB-25434?focusedCommentId=226874&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-226874

**Comment by tleyden** [comment]
Related server issue: https://issues.couchbase.com/browse/MB-24201

**Comment by tleyden** [comment]
Similar sync gateway issue: https://github.com/couchbase/sync_gateway/issues/2526

**Comment by tleyden** [comment]
@adamcfraser should this look like the following:

`SyncGateway-<sg-version>-<random-number>`

Where the random number is generated via `r := rand.New(rand.Source(now)) ` (per your suggestion in [MB-24237](https://issues.couchbase.com/browse/MB-24237?focusedCommentId=214138&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-214138))

**Comment by adamcfraser** [comment]
@tleyden That looks good - thanks for catching that we still need a random element to ensure there's no stream name collision between SG multiple nodes.

**Comment by tleyden** [comment]
- Sync Gateway example

`SG-v-1.5-commit-cd843bc-uuid-000001f5-7c6a-21e7-8800-a45e60e68b03`

![screen shot 2017-08-08 at 11 54 28 am](https://user-images.githubusercontent.com/296876/29089207-5fc782ac-7c30-11e7-991f-ecb533cb793c.png)


- SG Accel example

`SGA-v-1.5-commit-cd843bc-uuid-000001f5-7c6b-21e7-bf00-a45e60e68b03data-bucket8298b8060516ae6fed6f40fe036dd42c_33416f6649935217-b99e163`

This is longer due to this [code in feed_dcp.go](https://github.com/couchbase/cbgt/blob/d45c4c2414e1a0935fbb899a65b3880ee42347e3/feed_dcp.go#L261-L275):

```
	options := &cbdatasource.BucketDataSourceOptions{
		Name: fmt.Sprintf("%s%s-%x", DCPFeedPrefix, name, rand.Int31()),
                ...
         }
```

![screen shot 2017-08-08 at 11 59 18 am](https://user-images.githubusercontent.com/296876/29089426-0a23e100-7c31-11e7-819a-6d0a1ca47d21.png)
