### ISSUE TITLE
Unit test code coverage

### ISSUE THREAD

**Issue by djpongh** [couchbase/sync_gateway#2836]
Need to measure code coverage of our unit tests.

- [ ] Update unit integration to have a flag (generate coverage report)
- [ ] Attach coverage report to results
- [ ] HTML report

## Options

- [ ] Run tests + coverage in single-pass by using gocoverutil exclusively
- [ ] Currently Walrus and Non-Xattr only -- doesn't do XATTR vs Non-Xattr or Couchbase vs Walrus

## Nice to have

- [ ] Adding stats to PR (requires build machine change)

Possibly move to separate ticket

**Comment by adamcfraser** [comment]
Background info here:
https://github.com/couchbase/sync_gateway/issues/766

**Comment by tleyden** [comment]
## Run tests + coverage in single-pass by using gocoverutil exclusively

Pros

* Single pass, more efficient

Cons

* Could introduce noise if has differences with `go test`
* Harder to get summary percentage (need to use grep + tee maybe)
* Complicates script so that it works with and without gocoverutil installed

**Comment by tleyden** [comment]
- [ ] If coverage report is true, run integration test and generate separate report

**Comment by tleyden** [comment]
I'm closing this issue in favor of tracking this via https://github.com/couchbase/sync_gateway/pull/2880 -- since I ended up posting the most recent updates there.
