### ISSUE TITLE
Gocb sdk client pool

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2852]
According to @agyryk, there might be opportunity for increasing throughput by having multiple GoCB instances and doing "round-robin" requests through the instances, which is the normal approach in perf testing against a single Couchbase Server node for other SDK testing.

**Comment by djpongh** [comment]
related to performance testing

**Comment by ingenthr** [comment]
@tleyden and I were talking about this on the side just now and he pointed me to this issue.

Recently @brett19 looked into gocb throughput and if I recall correctly, there is no bottleneck  endemic to the client itself. We had, IIRC, over 50k ops/s from a microbenchmark with high concurrency. higher level go programming using channels may see lower throughput, but that's not a function of gocb directly.

Beyond that, it's relatively known that you can get higher throughput with more TCP connections (regardless of language), but not by much.  The higher throughput comes at a space cost.  You're basically creating bigger buffers in switches/OSs/etc.  We do this in some places, but tend to prefer a single connection with multiplexed IO since the number of connections can get very large at scale.  We have, today already, some deployments with 15k physical systems connecting to a single cluster.  

There are a couple of academic papers about this phenomena specifically.  I'd have to look back to find my references.  This is one: http://conferences.sigcomm.org/sigcomm/2005/poster-119.pdf

Point is, if you have any data pointing to a bottleneck in a client instance, it'd be interesting to share that.  From discussion with @brett19 earlier, we believe there's nothing in gocb/gocbcore that can't be addressed by opting in to a lower programming model that avoids some of the synchronization bits in higher level go.

**Comment by brett19** [comment]
Hey Guys,

Just wanted to chime in here that as of somewhere in the 1.1.x range of gocb client releases, we started using pools of channels and timers to handle synchronization between the users application and the asynchronous callbacks of gocbcore.  That release reduced the overhead of using gocb to ~5%.  As long as the application is performing operations across a number of different goroutines concurrently, there should be very little performance difference between using gocb and gocbcore.

P.S. We recently performed some updated performance testing of the gocb and gocbcore clients to evaluate if there was anything worth investigating and deduced that the Go SDK is likely one of the fastest SDKs available at the moment.

Cheers, Brett

**Comment by tleyden** [comment]
Awesome!  Thanks for the clarification.

**Comment by ingenthr** [comment]
One issue, not gocb specific but more a protocol issue with mcd binprot, is the so-called head-of-line problem.  If you have an operation backfilling off of disk that is adding latency to items that should be served from memory, for now you can add to the number of KV connections with a tuneable.

The MB tracking the protocol issue is https://issues.couchbase.com/browse/MB-10291 and it's recently been picked up to be actively worked on.  It'll be a while though, so for now adjust the number of KV connections used.  Not sure if this is what @agyryk suspected was related or not, but @brett19 mentioned that it had once come up in other tests.

**Comment by adamcfraser** [comment]
@brett19 @ingenthr This ticket is based on performance results seen by @agyryk when doing standalone SDK testing, but he was using the Java SDK and not gocb.  I don't rule out that gocb might be much better at concurrent requests than the Java SDK, but the perf team doesn't currently have any way to validate that. 

We decided that the shortest path to testing throughput of multiple gocb instances would be to do a poc using Sync Gateway - that's where this ticket came from.  If you've got benchmarking results that you can share demonstrating a significant difference between gocb throughput and Java SDK throughput, that might be sufficient to put this item on hold for now, but I'd like to keep this open until those are reviewed by @agyryk.

**Comment by agyryk** [comment]
I ran series of read/write tests with various client threads amounts against Sync Gateway. Plain read/write operations stop scaling pretty quickly. And I don't see any oblivious resource constrains when hitting the limit rather than noticing single SDK opening single connection to CB server. From numbers perspective:
20k reads/sec is the top I could get through SG (single gocb instance)
Accessing CB directly with Java SDK:
 5k reads/sec max with single Java SDK / singe connection
 up to 1M reads/sec with multiple SDK instances

Also please note that my testing machine is quite powerful, 48 core/64GB RAM. I'm wondering if it adds more "pressure" to the networking part of the code path as its enough computing power to handle the rest (like sync function execution). Max CPU load I could get was about 20%. 

The poc SG build utilizing multiple connections/SDK instances would definitely help me with further investigations

**Comment by brett19** [comment]
Hey @agyryk ,
Could you describe a little bit about the workload you are performing?  You're single instance performance is quite a bit lower than I can get even on my MBP.
P.S. You can find a little workload generator for Go here:
https://gist.github.com/brett19/b6d8906065d51b3eb4c3063f219351dd
Cheers, Brett

**Comment by agyryk** [comment]
I'm using YCSB for read/write tests. For reads its plain GET on SG's /db/docId 
1 CB, 1 SG instance.
1M docs, doc size is 1KB + channels[] field 
Here is the YCSB branch https://github.com/couchbaselabs/YCSB/tree/syncgateway
Driver name is "syncgateway".

**Comment by adamcfraser** [comment]
@agyryk The POC is available for testing using branch https://github.com/couchbase/sync_gateway/tree/feature/issue_2852.

**Comment by ingenthr** [comment]
@djpongh can you put a summary in of how this was resolved?

**Comment by adamcfraser** [comment]
@ingenthr Not going forward with this change.  Based on perf analysis by @agyryk, we didn't see any performance benefit.  Have also heard from @brett19 that support for similar functionality has been added to the gocb library itself, so if we decide to revisit we should go that route.

**Comment by ingenthr** [comment]
Thanks for the updated @adamcfraser !
