### ISSUE TITLE
Guidance on how to deal with keeping track of "processed" documents

### ISSUE THREAD

**Issue by epitka** [couchbase/sync_gateway#2865]
Background:
In our mobile app, users can perform actions that can result in processing of the commands in the backend.  When we establish a web socket connection to get pending commands (documents), a "since" value has to be provided.  This since value has to be tracked somewhere, so that if service goes down, next time it starts from the last sequence that was processed. So I thought I'll create a doc and after each command is processed, I'll update value with a sequence of the document processed. Well what I found out, when looking at couchbase server is that it keeps track of each revision. As we are talking about millions of commands, that would yield a doc that is just huge.  What  I really need is just a document such as  "_sync:seq", or a doc, that does not have all that revision, history etc. just a field with a number.
Any guidance would be highly appreciated.

lastProcessedDocumentSequence doc

```
{
    "value": 6
  "_sync": {
    "rev": "3-688542223bca3bb9d516eb2b5728826d",
    "sequence": 8,
    "recent_sequences": [
      2,
      5,
      8
    ],
    "history": {
      "revs": [
        "1-f282563eb44318552395c7e34e734aa2",
        "2-8f1d4129dfd6eebf628bd751792bfdeb",
        "3-688542223bca3bb9d516eb2b5728826d"
      ],
      "parents": [
        -1,
        0,
        1
      ],
      "channels": [
        null,
        null,
        null
      ]
    },
    "time_saved": "2017-08-30T18:45:00.2041133Z"
  },
}
```

**Comment by Crapulax** [comment]
Hello Edvard,

If I understand correctly, you have a backend server listening for command's documents and processing them. When you receive new/updated document you get an associated seq number with each. You need to store last processed value to restore processing when server goes down. Is this correct?

If yes, beside simply storing last processed sequence value into a file, you can also store it directly into a Couchbase document for instance. In that case you do not have revision history created. As it is the gateway creating them for replication purpose. This is what we implemented in our Go backend servers.

Feel free to come back to me, if necessary.

Brgds,

**Comment by epitka** [comment]
@Crapulax
Yes, first paragraph is correct, that is exactly what intention is. I am not sure I understand " you can also store it directly into a Couchbase document for instance".   Are you suggesting that I create an attribute "seq" on the document "lastProcessedDocumentSequence"? Could you supply a small example on the structure of the document?

I have a document called "lastProcessedDocumentSequence", and after command has been processed I take a seq number from that document and put it in the "lastProcessedDocumentSequence" "value" attribute and just keep updating that same doc. with each new seq of command document that has been processed.   
```
private void UpdateSequence(long seq)
        {
            var url = _syncUri + "/lastProcessedSequence";
            lastProcessedSequenceDoc.value = seq;

            var json = JsonConvert.SerializeObject(lastProcessedSequenceDoc);

            var  data = Encoding.UTF8.GetBytes(json);

            var request = WebRequest.CreateHttp(url);

            request.Method = WebRequestMethods.Http.Put;
            request.ContentType = "application/json; charset=UTF-8";
            request.Accept = "application/json";

            request.ContentLength = data.Length;

            using (Stream stream = request.GetRequestStream())
            {
                stream.Write(data, 0, data.Length);
            }

          .... and so on...
}
```

**Comment by adamcfraser** [comment]
@epitka This is a question better suited for [the mobile forums](https://forums.couchbase.com/c/mobile)- the github issue tracker is intended for bug reports or enhancement requests.

**Comment by Crapulax** [comment]
Hello,

humm, maybe I start to understand what you are doing. The only communication flow between your mobile clients and your backend server(s) is through the sync gateway, isn't it? And you want to 'tell' your clients apps 'your command was processed', correct?

If that's the case, indeed you need to go through a shared doc. You will not end up with millions of revisions as they are capped (to 1000 if I remember correctly and this is configurable on SG side).

But, I strongly suggest establishing instead a network connection between your clients and your server(s). This would be much more powerful and open the way to much more possibilities. At the end of the day, above need is:
- ask server last processed value
- server replys

The only way I foresee to handle it in a SG only context is to have one document for each client which is updated by server with last value handled WHEN NECESSARY (i.e. clients asked for something). Because more than number of revisions you mentioned the issue would be to have one document shared among hundreds of thousands of clients (you did not mentioned number of clients though). Updating often one document which is then spread to xxK clients is not a so good idea.

Hope it helps,
Steve.

PS: I just realized that Adam rightly closed this topic here, let me know (steve.faye@appscie.com) another issue you might open and we can continue our discussion.

**Comment by epitka** [comment]
@Crapulax 

I've posted a question in mobile forums, and have gotten answers that will get me on the right track. 

But to answer you question, clients are not  in picture, clients only save new documents that go from Pending to Processed or ErroredOut state. They are one way, to server. Server processes command and updates document with State, and then updates sequence of the last processed document. If the server goes down we get that sequence and keep processing from that value.
