### ISSUE TITLE
Improve code coverage report

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#2937]
Prerequisite issues:

- [x] [Run integration tests as full suite #2938](https://github.com/couchbase/sync_gateway/issues/2938)

Want to include integration tests into the total test coverage report.  Requires:

- [x] Ability to run the integration tests in coverage mode
- [x] Combine test coverage from integration mode with test coverage from unit test mode
- [x] Run test_integration_with_coverage in the existing jenkins job when the coverage flag is set, and merge the output with the standard test_with_coverage.sh output
- [x] Simplify the integration jenkins job to always run unit tests, integration tests, coverage

Out of scope for this ticket:

- [ ] To generate full code coverage for integration tests, need to run test_integration_with_coverage.sh in xattr and non-xattr mode, and merge both with the test_with_coverage.sh output.  Requires modifying the jenkins job to automatically run in both modes (instead of checkboxes).
- [ ] Generate before-and-after code coverage reports for a PR

**Comment by tleyden** [comment]
> Create test_integration_with_coverage.sh to run the integration tests in coverage mode

This is tricky given the current state of the integration tests, which run one at a time.

gocoverutil doesn't work in this case:

```
gocoverutil -coverprofile=TestGetRemovedAsUser.out test -v -covermode=count -run '^TestGetRemovedAsUser$' github.com/couchbase/sync_gateway/...
flag provided but not defined: -run
```

and neither does `go test`:

```
+ go test -coverprofile=TestDocDeletionFromChannelCoalescedRemoved_coverage.out -v -run '^TestDocDeletionFromChannelCoalescedRemoved$' github.com/couchbase/sync_gateway/...
cannot use test profile flag with multiple packages
```

**Comment by tleyden** [comment]
I ran into something of a blocker -- it's not possible to use the `-p 1` flag to `go test` in conjunction with `gocoverutil`.  I filed an issue w/ goverutil here: https://github.com/AlekSi/gocoverutil/issues/4

Without that flag, there's no way to run the tests in integration mode.  And with the standard `go test` tool, there's no way to unify the coverage reports due to https://github.com/golang/go/issues/6909

**Comment by AlekSi** [comment]
👋 `gocoverutil` always acted as if `-p 1` is passed. Now that flag is accepted and ignored so the tool can be used as a drop-in replacement of `go test` in more cases.

You may also be interested in https://github.com/AlekSi/gocoverutil/issues/2.

**Comment by tleyden** [comment]
Thanks @AlekSi!  I woke up and it was fixed .. magic!

**Comment by tleyden** [comment]
From http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-coverage/2/:

In the test against Walrus bucket_gocb.go has 9.6% coverage

<img width="493" alt="screen shot 2017-10-20 at 4 03 31 pm" src="https://user-images.githubusercontent.com/296876/31844873-679d2a7c-b5b0-11e7-985e-cd1e3ae9add0.png">

Whereas in the integration test  bucket_gocb.go has 53.2% coverage

<img width="480" alt="screen shot 2017-10-20 at 3 53 52 pm" src="https://user-images.githubusercontent.com/296876/31844882-736d382e-b5b0-11e7-96d6-44ea7a18d23a.png">

In the merge, it has 53.2% coverage, presumably since the coverage is overlapping

<img width="492" alt="screen shot 2017-10-20 at 4 05 55 pm" src="https://user-images.githubusercontent.com/296876/31844887-7a4829ce-b5b0-11e7-9375-60ebce1ed07e.png">

**Comment by tleyden** [comment]
- Fix jenkins job
