### ISSUE TITLE
[Perf] High CPU usage and limited scalability in "roundtrip write" testing scenarios

### ISSUE THREAD

**Issue by agyryk** [couchbase/sync_gateway#2948]
This is placeholder for my future investigations on the behavior below. I will update the ticket with my findings if any.

When doing plain reads/writes on the SG cluster both resource usage and overall scalability look good and expected. But when test scenario introduces frequent requests to _changes feed the SGs CPU usage is way higher and also system isn't scaling well. Adding more SG nodes doesn't distribute the load, all nodes remain heavy-loaded from CPU perspective.
Details and numbers can be found here: https://hub.internal.couchbase.com/confluence/display/CY/Sync+Gateway+performance+baselining

**Comment by adamcfraser** [comment]
Looked into the significant difference in CPU utilization between the following two runs (from https://hub.internal.couchbase.com/confluence/pages/viewpage.action?pageId=22988393)

2 nodes, 400 threads, roundtrip write, longpoll feed with channels filter
2 nodes, 400 threads, roundtrip write, longpoll feed w/o filters

At first glance the higher CPU in the filter test was unexpected.  It looks like the underlying cause is that the unfiltered longpoll feed never ends up blocking (there's always new data found), while the filtered longpoll feed doesn't find changes at first and blocks until there's a change in their channel.  It's expected that this will result in more concurrent changes connections.

It's still worth digging into the details on why the connections that end up in the Waiting state end up with such high CPU utilization, though - whether that's actually happening *while* they are in wait mode, or a consequence of the additional processing that's done when the feeds are subsequently woken up.

**Comment by agyryk** [comment]
For those tests, every doc has two channels – one global channel and one random. Users have access to all channels.
And the workflow is:
Client inserts a new doc, assigning two channels to it - "ycsb" (global) and "channel-555" (random). Then  calls _changes  with filter by "channel-555".

So I'm thinking if I change it to filter by channel "ycsb" it will put both test scenarios (w/ filter and w/o filter) in the same condition it terms of how may docs will get into the feed.

This might prove your conclusion. 
What do you think?

**Comment by adamcfraser** [comment]
Yes, that approach would yield a useful data point that would help confirm the theory.

Another angle to go at it would be to only grant the user access to a single random channel, and call _changes with no filter.

**Comment by adamcfraser** [comment]
Another thing that jumps out at me from the flame graphs for those two cases:

There's a significant difference in the CPU breakdown within (*handler).handleChanges - the filtered case spends almost 40% of the time in handleChanges doing query parsing, versus 1% in the no filter case.  This is a much bigger gap than I'd expect.  There are known inefficiencies in query parsing (#1850) - it's probably worth tackling that to see how much it helps.

**Comment by adamcfraser** [comment]
Closing based on age, and write throughput enhancements in 2.7.0 not identifying this as bottleneck.
