### ISSUE TITLE
Wrong content type for _user and _role

### ISSUE THREAD

**Issue by jnordberg** [couchbase/sync_gateway#299]
The gateway is responding with `text/plain` for some requests when it should be `application/json` 

```
$ http -v --json get localhost:4985/soter/_role/
GET /soter/_role/ HTTP/1.1
Accept: application/json
Accept-Encoding: gzip, deflate, compress
Content-Type: application/json; charset=utf-8
Host: localhost:4985
User-Agent: HTTPie/0.8.0



HTTP/1.1 200 OK
Content-Encoding: gzip
Content-Length: 153
Content-Type: text/plain; charset=utf-8
Date: Fri, 21 Mar 2014 05:40:12 GMT
Server: Couchbase Sync Gateway/0.93

["role_82cb700682d74c5ab62b403acdaed6ec","role_b785b7b13b3d4165bc6b1291592acc61","role_ca1a0f1e1cef47acb93b6b8792d81a0e","role_da5858fedc4745a98a7baf54b66999b5","role_f4508b6b2fed497eaf534ba25540c310"]

```

**Comment by cavalier123** [comment]
Just hit this problem when writing a REST client using the RESTEASY Client Proxy Framework - basically the framework won't 'automatically' deserialise the JSON returned by GET user because the MIME type of the response is text/plan rather than application/json. I can work around this but getting the wrong content type back is annoying - please fix!

**Comment by adamcfraser** [comment]
Moved to https://issues.couchbase.com/browse/CBG-640
