### ISSUE TITLE
Sporadic test failure: TestLowSequenceHandlingAcrossChannels

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#3001]
## TestLowSequenceHandlingAcrossChannels

In [jenkins build sgw-unix-build/3109](http://mobile.jenkins.couchbase.com/view/Sync_Gateway/job/sgw-unix-build/3109/consoleFull):

```
02:15:27 2017-06-26T02:28:10.478-07:00 Changes+: No new changes to send to change listener.  Waiting for "test_data_bucket-86a3ecb3b97c33e0df1bcc05595985b6"'s count to pass 5
02:15:27 2017-06-26T02:28:10.479-07:00 Cache: Received #3 after   0ms ("doc-3" / "1-a")
02:15:27 2017-06-26T02:28:10.479-07:00 Cache:   Received previously skipped out-of-order change (seq 3, expecting 10) doc "doc-3" / "1-a" 
02:15:27 2017-06-26T02:28:10.479-07:00 Cache:     #3 ==> channel "PBS"
02:15:27 2017-06-26T02:28:10.479-07:00 Cache:     #3 ==> channel "*"
02:15:27 2017-06-26T02:28:10.480-07:00 Changes+: Notifying that "test_data_bucket-86a3ecb3b97c33e0df1bcc05595985b6" changed (keys="{*, PBS}") count=6
02:15:27 2017-06-26T02:28:10.571-07:00 waitForSequence(9) took 100 ms
02:15:27 2017-06-26 02:28:10.622699 I | Feed retrieving  0xc42041eae0 1
02:15:27 2017-06-26 02:28:10.622857 I | Changes entry: {Seq:2::9, ID:doc-9, Changes:[map[rev:1-a]]}
02:15:27 2017-06-26 02:28:10.622905 I | returned numEntries - returning
02:15:27 2017-06-26 02:28:10.622978 I | verifyChangesFullSequences: sequence mismatch at index 3, changes=2::9, sequences=3::9
02:15:27 
02:15:27 	change_cache_test.go:598
02:15:27 	assert.True(t, verifyChangesFullSequences(changes, []string{"1", "2", "2::6", "3::9"}))	
02:15:27 --- FAIL: TestLowSequenceHandlingAcrossChannels (3.64s)
``` 

On the same commit, the test passed on several other build slaves, so I'm assuming it's a sporadic test failure.

**Comment by adamcfraser** [comment]
Similar failure in TestLowSequenceHandling in  http://mobile.jenkins.couchbase.com/view/Sync_Gateway/job/sgw-unix-build/4568/consoleFull.

From failing test logs, late-arriving sequence is being sent twice in separate changes loop iterations:

```
22:10:35 2017-11-08T06:09:37.791Z Changes+: MultiChangesFeed sending {Seq:2::3, ID:doc-3, Changes:[map[rev:1-a]]}   (to naomi)
...
22:10:35 2017-11-08T06:09:37.792Z Changes+: MultiChangesFeed waiting...   (to naomi)
...
22:10:35 2017-11-08T06:09:37.793Z Changes+: MultiChangesFeed sending {Seq:3, ID:doc-3, Changes:[map[rev:1-a]]}   (to naomi)
22:10:35 2017-11-08T06:09:37.793Z Changes+: MultiChangesFeed sending {Seq:4, ID:doc-4, Changes:[map[rev:1-a]]}   (to naomi)
```

That document (doc-3) is present in four different channels.  The duplication on the changes feed may be due to the document being treated as a late sequence in one channel, and a non-late sequence in another (because the latter channel didn't have any previous sequences)

**Comment by adamcfraser** [comment]
I believe this is a gap in how we're using currentCachedSequence to ensure that individual channel feeds are consistent.  When there are skipped sequences, currentCachedSequence is just the normal sequence value (not the low sequence value).  This is fine for the normal channel feeds, but doesn't enforce consistency between multiple late feeds.  An update that starts hitting multiple late feeds midway through a changes iteration could end up being sent from one channel's late feed in that iteration, and from another channel's late feed in the subsequent iteration.

To avoid, we need to force consistency on late feeds using lowSequence, instead of depending on currentCachedSequence.

**Comment by tleyden** [comment]
Should this ticket get renamed then?  Sounds like a code issue rather than a test issue

**Comment by adamcfraser** [comment]
Moved SG bug to https://github.com/couchbase/sync_gateway/issues/3056.  Working on disabling or reworking the tests until that's fixed.
