### ISSUE TITLE
Couchbase Lite <=> (Sync Gateway) <=> CouchDB

### ISSUE THREAD

**Issue by dryewo** [couchbase/sync_gateway#312]
Hello couchbase!

Thank you for your great effort on making nosql available to mobile devices! I'm now starting to use it and I like it very much.

But there's some issue I'm having with synchronization.
On my android device I need to have documents with arbitrary sized attachments. I tried to insert files up to 100 Mb, they are stored and available.

But now I'm stuck with how to sync them with database server.
Couchbase Server has 10 Mb limit for a single attachment, therefore I decided to use CouchDB.

In the Sync Gateway FAQ it's said:

> Apps using Couchbase Lite can sync with servers running Apache CouchDB and with Couchbase Server via Sync Gateway.

I have CouchDB set up on `http://127.0.0.1:5984`.
Then I installed Sync Gateway and ran it, but got this error:

```
FATAL: Error opening database: 502 Unable to connect to server: HTTP error 404 Object Not Found getting "http://127.0.0.1:5984/pools": {"error":"not_found","reason":"no_db_file"}
```

I have this config:

```
{
   "interface":":4984",
   "adminInterface":":4985",
   "log":["CRUD", "CRUD+", "HTTP", "HTTP+", "Access", "Cache", "Shadow", "Shadow+", "Changes", "Changes+"],
   "databases":{
      "mob_hello":{
         "server":"http://127.0.0.1:5984",
         "bucket":"mob_hello",
         "sync":`function(doc) {channel(doc.channels);}`
      }
   }
}
```

It seems that Sync Gateway is trying to use `pools` feature that CouchDB doesn't have.

Then I tried to do direct replication from my Couchbase Lite to CouchDB.
It worked only for documents with no attachments. I saw the following message in `couch.log`:

```
attempted upload of invalid JSON (set log_level to debug to log it)
```

So, the question I have, is there a working way to do this kind of replication between Couchbase Lite and CouchDB and vice versa?

**Comment by chintan-mishra** [comment]
With the release of Couchbase Lite 2.0 is this solution still valid?

Couchbase Lite 2.0's release notes show that it is not compatible with CouchDB replication protocol.

**Comment by rajagp** [comment]
@chintan-mishra  That is correct. Couchbase Lite 2.0's enhanced replication protocol is not compatible with CouchDB .  
The Sync Gateway 2.0 however will supporting both Couchbase Lite 2.0 mobile clients  with the new protocol and the CouchDB enabled replication protocol.

However, the suggestion to keep large attachments in a separate store and store the URL in the document is still a viable option.

**Comment by HBODKR** [comment]
@rajagp   i have server couchDB and mobile app i use couchbase lite 1.3 ,i want to change version of couchbase lite to 2.0, but i can't replicate couchdb with couchbase lite because the version 2.0 not compatible ,so you said the solution is sync gateway but i found in couchbase community the sync gateway it's work only with couchbase server not couchDB because sync gateway is a product for couchbase server, can you explain me how support couchDB  ?

and in this link  where i found you can't use sync gateway with couchDB :
https://forums.couchbase.com/t/cbl-2-0-couchdb-server-syn-gateway/13362

**Comment by chintan-mishra** [comment]
I found two viable solutions for using Couchbase Lite with CouchDB:
1. Switch from Couchbase Lite to Cloudant Sync [Android](https://github.com/cloudant/sync-android)/[iOS](https://github.com/cloudant/CDTDatastore). Cloudant Sync is an embeddable NoSQL DB by IBM. It works like charm and feels like a breeze to use. And you can also user CouchDB per user feature easily. Also, Cloudant is like managed version of bleeding edge CouchDB.
2. Add the feature to Couchbase Lite. After reading the code I realized that SyncGateway can easily replicate data from CouchDB compliant replication protocol to Couchbase but not the other way around. You can verify this by using SyncGateway with PouchDB(CouchDB for browsers). The support has been dropped only for mobile DB.

The latter is a repititive task and would require continued effort. So, I went with 1. I haven't faced issues till now.

@HBODKR A similar reply was once deleted. I will DM this on LinkedIn if need be.

**Comment by snej** [comment]
You can connect CouchDB to Couchbase Lite by using Sync Gateway as an intermediary, since it speaks both replication protocols.

1. Set up Couchbase Server with Sync Gateway
2. Configure CouchDB to replicate bidirectionally with Sync Gateway
3. Configure Couchbase Lite to replicate with Sync Gateway

If I may put on my marketing hat for a sec: Cloudant Sync is actually a fork of an ancient (circa 2013) version of Couchbase Lite (back when it was called TouchDB.) These things happen in open source... Cloudant has made a bunch of changes (like a query language) but if they're still using that code base it must be super creaky by now 😝. We rewrote Couchbase Lite from scratch for version 2.0, largely in optimized C++, with a lot of innovative features like N1QL-based queries and a more efficient new replication protocol.

On the server side, I love CouchDB (it's a big part of Couchbase's DNA) but it's not nearly as scalable as Couchbase Server. And it lacks document-level access control for reads, which is pretty limiting for shared databases.

**Comment by chintan-mishra** [comment]
N1QL is nice for those coming from RDBMS background. I fail to understand why so many NoSQL DBs have a query language that has look and feel of RDBMS.

CouchDB has Mango queries which provide similar functionality but the syntax is not SQL-ish. Last I checked TouchDB codebase is not present in Cloudant Sync Android or CDTDatastore.

**Comment by HBODKR** [comment]
@chintan-mishra  thx for help 
@snej  what i know you can't use sync gateway with couchdb it's only work with couchbase server so how  can i configure couchDB with sync Gateway ?,  and there is way to replicate between couchdb and couchbase server without sync gateway ?

@rajagp can you help me please ?

**Comment by OmarBenyahyaten** [comment]
@snej can you explain how we can

> Configure CouchDB to replicate bidirectionally with Sync Gateway

as I read many replies posted by couchbase admins on their forum 
[https://forums.couchbase.com/t/couchdb-sync-gateway-in-node-js/14159](url) 
[https://forums.couchbase.com/t/can-i-use-cb-lite-sync-gateway-with-couchdb-or-cloudant/2050/4](url) 
[https://forums.couchbase.com/t/cbl-2-0-couchdb-server-syn-gateway/13362/3](url) 
[https://forums.couchbase.com/t/local-cache-to-sync-gateway-syncing/20101](url) 
where they talked about the incompatibility of CouchDB & Sync Gateway. So now I'm a little bit confused about what you're saying. Can you explain please?

**Comment by snej** [comment]
@chintan-mishra: Don't confuse query languages with database architectures. SQL-type languages aren't tied to relational semantics, as N1QL shows. And anyway, there is no N1QL syntax in Couchbase Lite.

@HBODKR Sync Gateway requires Couchbase Server. You set up Couchbase Server and Sync Gateway. Then you configure CouchDB to replicate with Sync Gateway the same way you would with another CouchDB.

Anyway, this is not a support forum. Please ask further questions on the [Couchbase web forum](https://forums.couchbase.com/c/mobile). We use Github issues only for bug reports and feature suggestions. Thanks.
