### ISSUE TITLE
Database encryption crashes on doSync method in iOS

### ISSUE THREAD

**Issue by Yuvraj-Sorav** [couchbase/sync_gateway#3185]
I am using couchbase lite 1.4.1. I am trying to implement database encryption in iOS and successfully done with the integration part as described in the documentation.

But when i am using database doSync method, it crash. It shows the error on line number:162 in CBLDatabase.m file.If i comment this database doSync method in my code, it works fine.

Also,I have cross check by removing database encryption, everything works well like before.

Ex: -  Suppose I have a function A():

1.    function A() {
2.    //get your database reference/Instance here
3.     [database doSync: ^ {
4.       //your code stuff
5.    }];
6.   }
when i run the function A, it will give a crash on line number:3.

Thanks in Advance

**Comment by bbrks** [comment]
Hi @Yuvraj-Sorav. This looks like an issue intended for couchbase-lite-ios.

Could you open an issue at https://github.com/couchbase/couchbase-lite-ios so that it can get seen by the right people?

Additionally, could you also provide a stacktrace/output of the crash and your couchbase server version in the new issue? This should help to resolve your issue quicker.

Thanks!
