### ISSUE TITLE
Improving reloaduser() performance

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#3193]
Follow-up change from https://github.com/couchbase/sync_gateway/pull/3197:

- Modify the user to store cas
  - Specifically, this would be adding to roleImpl
- Check cas when calling reloaduser

**Comment by tleyden** [comment]
- Modify the user to store cas
- Check cas when calling reloaduser

**Comment by tleyden** [comment]
Note from @adamcfraser:

> I was going to suggest checking whether db.user is nil before calling ReloadUser, but since ReloadUser already guards for that we could omit for now. Might be worth revisiting in the followup ticket/fix for code clarity.

**Comment by adamcfraser** [comment]
Instead of modifying reloadUser, would be preferable to add a new 'reloadUserIfChanged' method that does the cas check first.  The existing reloadUser would continue to be used in cases where we know the user has been changed (e.g. after notification during continuous changes).

ReloadUserIfChanged would do the cas check first, then fall back to reloadUser on cas mismatch.

**Comment by adamcfraser** [comment]
The potential performance benefit of doing the cas check instead of a full reload for each message is:
 - To determine if the user object has changed, retrieve only the meta instead of the full user doc, and use cas to determine whether we need to retrieve the full user doc:  same number of kv ops, but less data transferred over the wire
 - When there's no change, avoid unmarshalling the user doc and creating a new principal struct: reduced CPU and reduced allocs

However, user documents are currently loaded using an update callback pattern (auth.getPrincipal) that doesn't support passing in an initial cas/value.  To better support the reloadIfChanged scenario, this would need to be changed to accept cas/value as input parameters, similar to the pattern used in WriteUpdateWithXattr.  This has a knock-on effect - it would require the same change to WriteUpdate.  This would need to be supported in all bucket implementations (which currently still include go-couchbase).

There's an additional problem - the Update method also doesn't return a cas value (for storage on the Principal object) - this means that any cas-based check would require a rewrite of Update to support cas.  This prevents us from efficiently doing a cas check, even independently of the Update processing.

Given this, the risk/reward for 2.0 feels like it's swinging too far to the 'risk' side.  Recommend we defer this work until 2.1, unless performance testing indicates that ReloadUser is a major bottleneck.

**Comment by adamcfraser** [comment]
Implemented in 2.7.0.
