### ISSUE TITLE
SGW 1.5 fatal runtime: out of memory, caused by normal operations and _resync 

### ISSUE THREAD

**Issue by SightplanDipen** [couchbase/sync_gateway#3240]
The Sync Gateway issue tracker is reserved for bug reports and enhancement 
requests. For general questions, please use the Couchbase forums:
https://forums.couchbase.com/c/mobile/sync-gateway. Thank you!

### Sync Gateway version
1.5

### Operating system
Ubunutu

### Log output
2018-01-22T18:50:02.229Z Changes+: MultiChangesFeed: channels expand to “” …
2018-01-22T18:50:02.230Z Cache: getCachedChanges("*", 0) --> 1 changes valid from #96424173
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xc005ee, 0x16)
/usr/local/go/1.7.4/go/src/runtime/panic.go:566 +0x95
runtime.sysMap(0xc5ce510000, 0x100000000, 0x0, 0x1156398)
/usr/local/go/1.7.4/go/src/runtime/mem_linux.go:219 +0x1d0
runtime.(*mheap).sysAlloc(0x113ce40, 0x100000000, 0x11370d0)
/usr/local/go/1.7.4/go/src/runtime/malloc.go:407 +0x37a
runtime.(*mheap).grow(0x113ce40, 0x80000, 0x0)
/usr/local/go/1.7.4/go/src/runtime/mheap.go:726 +0x62
runtime.(*mheap).allocSpanLocked(0x113ce40, 0x80000, 0x43224f)
/usr/local/go/1.7.4/go/src/runtime/mheap.go:630 +0x4f2
runtime.(*mheap).alloc_m(0x113ce40, 0x80000, 0x100000000, 0x2)
/usr/local/go/1.7.4/go/src/runtime/mheap.go:515 +0xe0
runtime.(*mheap).alloc.func1()
/usr/local/go/1.7.4/go/src/runtime/mheap.go:579 +0x4b
runtime.systemstack(0x7fa22ce3add8)

### Expected behavior
It should not crash. 

### Actual behavior
trying normal operations and tried a offline, resync cause this error. We are upgrading from 1.3. we have about 25M+ docs, with a 8GB box.

### Steps to reproduce
1.  
2.  
3.

**Comment by adamcfraser** [comment]
Resync currently uses a view query to get the set of documents to re-evaluate, and doesn't do any pagination in that view query.  I expect that's the source of the high memory usage in this scenario.

It's worth reviewing whether the go-couchbase SDK (used prior to 1.5) did a better job of streaming the view response to minimize memory usage.  I don't think that's the case, but would be good to understand whether this is a regression.

In general we should consider switching _resync to use DCP instead of a view query to re-process the bucket - it would be a more efficient/reliable/restartable streaming model than attempting to paginate through a view query.

**Comment by adamcfraser** [comment]
@SightplanDipen Can you share some of the specifics around why you need to run resync against such a large bucket?  Normally we'd expect resync to be a rare operation when there's been that much data already processed in the bucket - if you've got a more common use case, I'd like to understand the details.

**Comment by SightplanDipen** [comment]
Part of the 1.5 upgrade we wanted to update our sync-config function, so need to resync.  Even before we tried the resync the SGW would crash, with small amount of load, so that was more concerning vs the resync. As for the resync we add more RAM 8GB to 32GB and the issue went away. Has the sizing requirements changed with 1.5 vs 1.3?

**Comment by adamcfraser** [comment]
Should review moving resync to DCP as part of general HA enhancements in 3.0

**Comment by adamcfraser** [comment]
Tracking with CBG-690, CBG-249.
