### ISSUE TITLE
Support CBL 2 blobs

### ISSUE THREAD

**Issue by snej** [couchbase/sync_gateway#3377]
SG supports the old-style `_attachments` dictionary but not the CBL 2 blob schema. This requires CBL 2's push replicator to add a fake `_attachments` dictionary to documents with blobs, which the pull replicator then removes. (This is also required for CBL 1.x backward compatibility.)

As we phase out CBL 1.x, SG should recognize the new schema for blobs: A blob is any JSON object (anywhere in a document) with a property `"@type":"blob"`.

**Comment by adamcfraser** [comment]
In general we want to move away from Sync Gateway having to unmarshal the document body - particularly at read time.  Sync Gateway currently needs to unmarshal the document body at least once during write (to execute the Sync Function), but I'm not convinced it should be scanning the document looking for `"@type":"blob"` references.  Probably merits a discussion to identify whether attachment information can be communicated as metadata over blip-sync, completely external to the document body.

**Comment by snej** [comment]
The replicator does need to look for blobs, in both directions.

* When receiving a revision (`rev` handler) it needs to find the digests of all the blobs, look them up locally, and send `getAttach` requests for each one it doesn't have.
* When receiving a `getAttach` request, it needs to check that it's sending a `rev` for a document that contains that attachment, i.e. to prove the client has access to the attachment.

**Comment by adamcfraser** [comment]
I'd like to review what our options are to optimize the first step:

> When receiving a revision (rev handler) it needs to find the digests of all the blobs, look them up locally, and send getAttach requests for each one it doesn't have.

 - In a no-conflicts scenario, can we use generation number as the equivalent of revpos, to avoid having to do the digest lookup for attachments that were associated with a revision.   I don't think this would require maintaining a rev history - just compare the current generation with the one associated with the attachment.
 - Can the active participant in replication be responsible for identifying the set of blobs in the document, and send them in an `attachments` property on the `rev` message, so that the passive participant can avoid unmarshalling and parsing the document body?

**Comment by snej** [comment]
Listing the attachment digests in the `rev` message sounds reasonable. Although of course you don't want SG to have to do that in the `rev` message _it_ sends! So it introduces some asymmetry in the protocol, where the digests are mostly optional but some peers require them in messages they receive.

**Comment by adamcfraser** [comment]
I was considering storing the attachment digests in the _sync metadata, so that we could keep things symmetrical but still avoid unmarshalling the document body on a get/rev.

**Comment by adamcfraser** [comment]
@snej Currently targeting this for 2.2.0, as we're trying to lock down the 2.1.0 scope.  If you think this needs to be in 2.1.0, let me know.

**Comment by adamcfraser** [comment]
Migrated to https://issues.couchbase.com/browse/CBG-799
