### ISSUE TITLE
auth.Save() should be CAS safe 

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#3414]
From the looks of it, `auth.Save()` is not doing a CAS safe write, and it should be.

The implication is that under certain scenarios changes to a user could be accidentally discarded.  For example, if multiple SG's were trying to update the same user concurrently.

Noticed during development for https://github.com/couchbase/sync_gateway/issues/3389

The development for https://github.com/couchbase/sync_gateway/issues/3389 is adding the ability to inject test behavior into certain operations to simulate CAS failures, which would probably useful for reproducing this issue in a unit test.

**Comment by adamcfraser** [comment]
Since we don't maintain a revision history on principals, and auth.Save doesn't have any merge behaviour, we'd need to review which auth.Save() usages are making additive changes to principals (and so would have the potential to lose data during concurrent updates).  It's possible that we don't need a CAS-safe write in every scenario, and performing a CAS-safe write should be optional in some cases.
