### ISSUE TITLE
2.1 handling for Bucket, DCP logging

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#3478]
Prior to 2.1, Bucket and DCP log keys weren't included when `*` logging was enabled, because they create a very large amount of logging output.

I think this is still the case for 2.1 - Bucket and DCP are too verbose to be enabled by default with Debug level logging.  In scenarios where we want to temporarily enable debug logging to diagnose an issue, including Bucket and DCP will blow up those logs and make them difficult to work with.

Two possible solutions:

1. We only support logging Bucket and DCP to console, and only include it when those log keys are explicitly enabled.  This would probably require a new Consolef() log method, and a LevelConsole log level.  
2. Bucket and DCP level logging are disabled, and require a code change to enable (i.e. they are dev-time only functionality).

**Comment by JFlath** [comment]
My initial thoughts:

* Is this ever something we can foresee needing in an environment other than dev? (And for "dev" read "Couchbase development of Sync Gateway" rather than users dev envs). Particularly for DCP, and the use of that for XATTRs, as a part of the more recent features may be somewhere we might need more insight at some point.
* How verbose is too verbose? And more specifically, how verbose in a steady state (e.g. ongoing ops), vs. an "unusual" state (e.g. a DCP rollback), vs. an error state (e.g. something we haven't envisioned, or  some external failure).
* Sync Gateway has an excellent Get Out Of Jail Free card in the `unsupported` config section. My gut feel on anything we're in doubt about is to throw a config option in there, over making in hardcoded. From an enterprise standpoint, it's basically the same; but if we really need it, we have the option.

**Comment by adamcfraser** [comment]
@JFlath I actually prefer option 1, as it addresses your first and third points (it's not on by default for customers, but could be enabled via the console logging config if really needed).  Along those lines, we'd want to be able to enable w/out SG restart.

Related to your first point - we do have some differentiation already today between DCP info and debug logging.  Things like DCP rollback would end up in info.  I should clarify that the above discussion is only intended to apply to DCP debug logging (the former DCP+).

For your second point - Bucket logs every bucket operation we make, so every bucket read/write/query/whatever.  DCP logs every DCP event received, not just errors/rollback.

**Comment by bbrks** [comment]
I think we should add a new `trace` log level for extremely verbose log keys such as `DCP` and `Bucket`, and maybe even HTTPR (#3470). Trace should only log to the console, and not to any file outputs.

This avoids having to have any special log key handling (i.e. exceptions to the `* == all keys` rule).

Adding `Consolef`/`LevelConsole` is effectively the same as adding the `trace` level, but the naming would mix output destination and verbosity. A `trace` level already has prior-art, so wouldn't be too foreign for people to pick up: https://logging.apache.org/log4j/1.2/apidocs/org/apache/log4j/Level.html#TRACE

Happy to hear thoughts: @JFlath @adamcfraser
