### ISSUE TITLE
[Perf] _changes request is  20% slower in SG 2.1 when logging is enabled

### ISSUE THREAD

**Issue by agyryk** [couchbase/sync_gateway#3614]
Test:
GET "_changes?since=<seq>&feed=normal" 

Test results:
http://showfast.sc.couchbase.com/#/timeline/Linux/syncgateway/sync/xattr

Possible reason is new logging:
CPU profiles (attached) show that SG2.1 spends more time in "github.com/couchbase/sync_gateway/db.(*Database).changesFeed" 
And about 40% of the call is taken by base.LogTo (called by base.Debugf) while with SG2.0 the base.LogTo  takes <10% of the request time (see screenshot, SG2.1 is on the left)

![screen shot 2018-05-30 at 4 18 26 pm](https://user-images.githubusercontent.com/20347420/40752627-38a8e5e8-6425-11e8-9680-2c7e6db3d24b.png)

[CPU profiles.zip](https://github.com/couchbase/sync_gateway/files/2055950/CPU.profiles.zip)

**Comment by agyryk** [comment]
Further thoughts:

Does base.Debugf() mean that I have Debug log level enabled?

My log config is following:
  "logging": {
    "logFilePath": "/var/tmp/sglogs"
  },

So logLevel isn't defined, and according to comment in logging.go:

//By setting DebugLevel to -1, if LogLevel is not set in the logging config it
//will default to the zero value for int32 (0) which will disable debug
//logging, InfoLevel logging will be the default output.

it should be set as InfoLevel.

**Comment by agyryk** [comment]
Run with logging disabled (see config below) confirms that logging causes the regression. I'll update the summary.
Still its unclear for me what log level is set by default when no settings specified.

I've disabled the logging with following config:
 "logging": {
    "log_file_path": "/var/tmp/sglogs",
    "error": {
      "enabled": false
    },
    "warn": {
      "enabled": false,
    },
    "info": {
      "enabled": false
    },
    "debug": {
      "enabled": false
    }
  },

**Comment by agyryk** [comment]
And one more comment.
Running test with logging enabled again...
Even if nothing is being printed to log SG still spends that extra time on Debugf() method so the throughput is constantly lower

**Comment by bbrks** [comment]
Hey Alex,

Thanks for the detailed report, it looks like we're doing quite an expensive timestamp formatting operation before we do a log-level check on the file outputs. There's definitely an optimization here we can make. More specifically, it seems we're formatting the timestamp if ***any*** of the file outputs are enabled, not the particular output level we want to check.

> Does base.Debugf() mean that I have Debug log level enabled?

Not necessarily. If you have a different log level set, base.Debugf, and the functions further down the stack will exit pretty quickly, essentially being a no-op.

> Run with logging disabled (see config below) confirms that logging causes the regression. I'll update the summary.

The config snippet you provided for disabling logging is missing the console output, so default behaviour will be (info level, HTTP log key).

In order to disable *all* logging completely, you will need to use something like the following:

```json
  "logging": {
    "log_file_path": "/var/tmp/sglogs",
    "console": {
      "log_level": "none",
      "log_keys": [],
    },
    "error": {
      "enabled": false
    },
    "warn": {
      "enabled": false
    },
    "info": {
      "enabled": false
    },
    "debug": {
      "enabled": false
    }
  }
```
