### ISSUE TITLE
OIDC provider throws error when optional value token_endpoint_auth_signing_alg_values_supported is missing

### ISSUE THREAD

**Issue by stcleezy** [couchbase/sync_gateway#4786]
### Sync Gateway version
Couchbase Sync Gateway/2.7.3(3;33d352f) EE

### Operating system
Windows 10

### Config file
```javascript
"oidc": {
  "providers": {
    "test": {
      "issuer":"https://dev-XXXX.oktapreview.com/oauth2/default",
	"client_id":"XXXX",
	"register":true
     }
  }
}
```

### Expected behavior
Optional params should not be required

I believe this was fixed in the underlying go-oidc package here: https://github.com/coreos/go-oidc/pull/138/files

### Actual behavior
2020-09-15T14:08:38.510-07:00 [ERR] Unable to initialize OIDC client: unable to discover config: token_endpoint_auth_signing_alg_values_supported cannot include 'none' -- auth.(*OIDCProvider).GetClient.func1() at oidc.go:102

### Steps to reproduce
This optional value is not supplied by Okta's discovery API: https://developer.okta.com/docs/reference/api/oidc/#well-known-openid-configuration

**Comment by sarathkumarsivan** [comment]
@stcleezy, Thank you for reporting this issue!

As per the OpenID Connect core specification, the `token_endpoint_auth_signing_alg_values_supported` property is optional and it represents a JSON array containing a list of the JWS signing algorithms (alg values) supported by the Token Endpoint for the signature on the JWT used to authenticate the Client at the Token Endpoint for the `private_key_jwt` and `client_secret_jwt` authentication methods. The specification also states that Servers SHOULD support RS256. The value `none` MUST NOT be used.

Further investigation of this issue revealed that the problem emerged from the underlying Go OpenID Connect library (`go-oidc v1`); the library was using the wrong field to ensure that the OIDC provider’s token endpoint always supports JWS signing algorithms, i.e. the library was checking whether the `token_endpoint_auth_methods_supported` is equal to `none` instead of `token_endpoint_auth_signing_alg_values_supported` to enforce the rule “The value none MUST NOT be used” defined against `token_endpoint_auth_signing_alg_values_supported` to adhere the OIDC core specification. This made Sync Gateway unhappy and he right away aborted the OIDC client initialization upon receiving the provider metadata discovery error from the underlying library. If the library would have checked `token_endpoint_auth_methods_supported` is equal to `none` instead, this issue would have never popped up.

This issue is fixed in `SG 2.8.0`, it uses the latest stable version of Go OpenID Connect library (`go-oidc v2`). Hope you can wait till `SG 2.8.0` is out the door. Moved to [CBG-1082](https://issues.couchbase.com/browse/CBG-1082).
