### ISSUE TITLE
SG TAP timeout issue

### ISSUE THREAD

**Issue by zgramana** [couchbase/sync_gateway#525]

**Comment by jchris** [comment]
I reread this and part isn't clear enough: "SG would also create feed since the lower sequence, which is expected to be silent until TAP coughs up the slow item." So I am rewriting it to capture the implementation and coin some nomenclature:
- the new normal, a **fast sequence sequence iterator**
- what we have today after adding Infinite timeout: a **buffering / waiting sequence iterator**
- **compound sequence numbers** like `167:204`

What I mean is that the gateway could adopt new behavior and send docs immediately as they come over the TAP / DCP feed, not buffering / waiting for missing sequences. In cases where the TAP feed is in order, the served sequence number (appearing in the seq entries and the last_seq value) would look like it does today. But in cases where the lowest missing sequence (last stable sequence) differs from the highest known sequence, the sequence number is presented as a compound, something like `low:high`.

When a request does not have a since parameter with a compound sequence number, the gateway does the normal thing: spawning internally a fast sequence iterator from the since value. A fast sequence iterator is one that doesn't buffer missing sequences / wait for them to fill in, it just serves the new ones as they come in. When a sequence becomes late, the fast iterator switches over to serving compound sequences. When all the late arrivers arrive, the fast iterator can go back to serving non-compound sequences. (Or in the simplification I describe below, it can serve something like `204:204` and avoid any conditional formatting logic.)

When changes feed requests come in with a since value containing compound sequences (maybe some channels have compound and some don't...), Sync Gateway does a new trick: internally it spawns two iterators (the fast iterator, like normal, from the high value) and a buffering / waiting sequence iterator from the low value. This iterator features today's behavior (it waits forever for the next gap to fill in). This iterator has priority about knowing what the highest stable sync is (it controls the low end of the compound sequence).

When the waiting / buffering iterator is caught up with the fast iterator (it has an empty buffer) it can shut down until the fast iterator detects another missing sequence to wait for.

One tricky bit is when the buffering iterator fills in a gap (a late arriver arrives). Let's say the client connects with `150:175` and the fast iterator has spewed up to 200 when 150 finally arrives. Since there could have been gaps anywhere between 150 and 175 for that client, we have to serve all changes in that range (and the client can ignore them via revs diff). But when we get to 175 we know which gaps matter because they are the ones the fast iterator buffered. So if the fast iterator served 176, 177, and 180, the buffering / waiting iterator knows it doesn't to serve 176, or 177, it can jump to waiting for 178. Hopefully this just falls out of the way the fast iterator manages the buffer.

## Implementation

As I was writing this up I tried to focus on conceptual clarity, actually in implementation I hope it could be simpler. I'm not looking at the code but just based on what I've written above here are a few "hacks" I would suggest using:
- Always serve compound sequences like `171:308` and run the simple path on Sync Gateway in cases where high = low eg `308:308`
- Probably doesn't require two "iterators" -- it's more like making the current code (infinite timeout) run next to the new code (send right away). So in practice might be able to just fix the places we generate seq nums, and maybe the buffering can be optimized (later, but not in the first implementation for correctness). Maybe a buffer optimization could be making it global instead of per channel?

**Comment by amazkovoi** [comment]
Hi Guys,

Thank a lot for looking into this. We really appreciate it!

Please correct me if I am wrong (trying to understand this): there needs to be some sort of a time out for the buffering / waiting sequence iterator as sequence numbers could get lost if e.g. a sync gateway process crashes after acquiring a sequence number.

This timeout could be set to quite a large number, e.g. 10 minutes.

Is this true?

**Comment by jchris** [comment]
@amazkovoi the only (simple) correct solution would be a timeout of Infinity, so that in effect, the channel pauses until it can give all results. This is in the work queue and will happen soon. 

What I've written above is the part of our engineering discussion about how to implement a correct version that doesn't suffer from waiting and buffering.

**Comment by amazkovoi** [comment]
@jchris Thanks for your fast response. Again, I really appreciate it. I believe the solution outlined here is exactly what we need and will make sync gateway even more solid.

I must be missing something, and would love to understand what it is. The reason for this is, the better we understand the technologies we use and how they work, the better service we can provide to our customers. So sorry for the numerous questions. I really appreciate your help with this!

Can a sequence number get permanently lost? I believe it can,  e.g. if sync gateway process acquires a sequence number (by calling incr on the Couchbase bucket) but then crashes (for whatever reason). For example, the underlying machine dies.

If a sequence number can get lost, how will other sync gateway processes know about this without a timeout? I believe there is no way at the moment to communicate this information to other sync gateway processes.

So without a timeout, the way I understand it, the low part of the compound sequence number will never advance past the lost sequence number.

Please let me know if I am on the right track, or where I am misunderstanding things.

**Comment by amazkovoi** [comment]
@jchris Thanks for the update!

Am I right that with the above approach, the listener creates a `_sync:seq:381` document before it declares an update as "failed" and bumps the `low` in the `compound sequence number`?

In step 2, "If the CAS fails we know that a listener has given up on us (see step 4) and that our document update needs to be repeated".

In this case the actual document has been updated already. Is this correct? If so, that would leave the system in an inconsistent state for a while. Is the TODO in Step 4 about dealing with this?

**Comment by jchris** [comment]
4 could look like a process that occasionally takes the MIN of all the low values of the current sequence number across all nodes in the cluster, and cleans up _sync:seq:N docs below that cutoff. Since this isn't latency sensitive it's probably easiest to drive it from a view query.

**Comment by jchris** [comment]
4a: Also, at the point where the buffering / waiting iterator decides a seq got dropped (it gets `_sync:seq:381` and the document id/rev there is missing or was written with a different sequence number, or the `_sync:seq:381` was never added.)

So in that case the iterator would check for the document and it's not there yet, so it advances `low` and marks the `_sync:seq:N` doc as allocated-but-not-committed. We assume the write was lost and if it does come through late it will be ignored by the iterators and return an error to the client.

The race condition to watch is inside 1. If the time between INCR on the sequence counter and adding the   `_sync:seq:N` doc is longer than the buffering / waiting timeout for first testing a seq, that's a fault. We can detect that in Sync Gateway and return an error status to the client. Paging @steveyen -- this would be a very helpful time to have small batch transactions in CBS.

All this is off-the-cuff and I'm a big fan of by-the-book when it makes sense, so the next step is to compare to [Raft](http://thesecretlivesofdata.com/raft/) etc and make sure there aren't well worn paths that would serve just as well. Even if we go by the book I think writing up an off-the-cuff makes sense for giving us a way to understand the problem in our context.

**Comment by jchris** [comment]
Actually thinking more about "marks the _sync:seq:N doc as allocated-but-not-committed" maybe we don't need to worry about the race in 1 I mentioned. Because if the buffering / waiting iterator CAS updates the doc as allocated-but-not-committed then the add in 1 will fail for the writer and it can return an error to the client or retry with a new seq.

**Comment by tleyden** [comment]
I wish I could understand this discussion.  A diagram would help ( I know it would be a lot of work, but I think it would pay off )

**Comment by amazkovoi** [comment]
@jchris Thanks for the write up. I also love by-the-book solutions especially if they are bulletproof :)

The bulletproof solution seems fairly involved.

Do we get most of the way there by introducing `compound sequence numbers` and making the contract for increasing a `low` a long enough timeout (say 10 minutes)?

It's certainly not bulletproof, but allows to not block callers when a seq has not arrived on the TAP feed (using `compound sequence numbers`) and the fairly long timeout should ensure that a huge percentage of updates that take a while to arrive still get published to clients.

I believe it will take care of our use case for a while.

The bulletproof solution could be the next step.

What do you think?

**Comment by amazkovoi** [comment]
The "middle ground" solution I have talked about above has a problem of what sequence number to use as `low` when a Sync Gateway has just started.

Could this be solved by including a timestamp in the view Sync Gateway uses in Couchbase to construct the _changes feed. When Sync Gateway starts it inspects the contents of the view and if it has gaps for records that are created within the timeout that is used to increment `low` it uses the highest value that does not have gaps. Otherwise `low` is set to the highest value found in the view.

Clients need to be able to deal with receiving sequence numbers where `low` has been set to a lower value than the `since` parameter that the client has provided. Sync Gateway also needs to deal with receiving a `since` parameter that is higher than its `low` parameter.

Another downside is having to synchronise clocks on all machines: couchbase machines and sync gateway machines.

However, I think all of the above should be possible.

@jchris @zgramana what are your latest thoughts on this?
