### ISSUE TITLE
Return error or warning when using unsupported view flags

### ISSUE THREAD

**Issue by stemail23** [couchbase/sync_gateway#676]
Couchbase Server = 3.0.2-1603 Enterprise Edition (build-1603)
Sync_Gateway = Couchbase Sync Gateway/master(da04959)

When attempting to query sync_gateway admin channel views with `include_docs=true`, no rows are returned:

`curl "http://user:password@localhost:4985/unit_tests/_design/testDoc/_view/testView?key=%22test_data%22&stale=false&include_docs=false"`
returns
`{"total_rows":3,"rows":[{"id":"test_data","key":"test_data","value":null}]}`

`curl "http://user:password@localhost:4985/unit_tests/_design/testDoc/_view/testView?key=%22test_data%22&stale=false&include_docs=true"`
returns
`{"total_rows":0,"rows":null}`

This is with the current git master branch code. Attempting the same with the release version download (Couchbase Sync Gateway/1.0.3(81; fa9a6e7)) results in:

`curl "http://user:password@localhost:4985/unit_tests/_design/testDoc/_view/testView?key=%22test_data%22&stale=false&include_docs=true"`
returns
`{"error":"Internal Server Error","reason":"Internal error: invalid byte in chunk length"}`

**Comment by stemail23** [comment]
Any comment on this guys? It's close to a blocker for me.

**Comment by adamcfraser** [comment]
I'm not sure Couchbase Server supports `include_docs` - I get a similar error when trying to set include_docs=true in a query against a 3.x server, like:

http://127.0.0.1:8092/default/_design/test/_view/testview?inclusive_end=true&key=%22mydoc1%22&stale=false&connection_timeout=60000&limit=10&skip=0&include_docs=true

I also don't see it included as a supported parameter in the API docs here:
http://docs.couchbase.com/admin/admin/REST/rest-views-get.html

**Comment by ingenthr** [comment]
I don't work on Sync Gateway, but I may be able to help.  

When Couchbase Server 2.0 was planned out, the team at the time intentionally deprecated support for include_docs.  It was documented as not supported, though it was still there and did work at a significant performance penalty.  In the SDKs, Couchbase added support for a "logical" include_docs, which did a KV fetch for the document asynchronously/in-parallel when passing the view results back to the application calling it's API.

include_docs is likely still there through 2.5, but it was removed in 3.0 as @adamcfraser found.

One workaround would be to move to Couchbase 2.5.  The disadvantage here is that the views are significantly slower in 2.5... slower to update in particular.  It may also have some poor resource usage characteristics.

The best approach is probably for Sync Gateway to implement the same logical include_docs when it proxies this request.  Do note, however, there is a slight semantic difference with respect to CouchDB as a document may differ from what's in the view or may not exist at all, since the doc is not being fetched as the specific version being referred to in the view, but rather the current state as known in memory.  The semantics are different w.r.t. CouchDB in some other ways too, as the view execution on a distributed system can vary since the time and order in which things are processed will be relative to the the place executing the query and the state of the systems it's querying before the merge.

That may be fine for your app though @stemail23, in which case you'd just need SG to add the logical fetch to support what you need.

**Comment by stemail23** [comment]
I see explicit code to handle include_docs, and I'm sure I've seen discussions about it in other threads, so I believe it is supposed to work. I suspect it may have broken with server 3.0, but I'm having difficulties rolling back to 2.X to confirm that.

**Comment by stemail23** [comment]
X-post above!

I'm working around this with a bulk fetch after the view query returns, but this feels like double handling, and less than optimal. Would be good to hear from one of the sync_gateway guys to know whether this functionality is to be reinstated?

**Comment by ingenthr** [comment]
It may not be so much double handling.  One of the reasons CouchDB had this originally was that it was already scanning the records in the files, so it was a pretty linear walk.  In Couchbase Server, the file layout is different and much of the data is in memory.  Since that subsequent doc fetch is going to memory in most cases, it's effectively the same thing whether your app does it or SG does it and assembles the results. 

Theoretically, it's better at the app since you'll be able to fetch the view results, then start processing them while the document body fetching is happening in parallel.  You'd only have to block when the data isn't immediately there.  This was done with Futures in Java under the hood, but there are similar approaches in other languages.

Hope that helps.  @adamcfraser can probably speak to where this is on the roadmap for SG.

**Comment by adamcfraser** [comment]
Thanks for the input on this @ingenthr.  I'll review this with @snej tomorrow to confirm, but I believe the initial motivation for the query functionality in SG was to expose any existing server capabilities through the SG API - so if your backing bucket supported include_docs, SG would support it.  I'll try to have more details for you tomorrow.

**Comment by stemail23** [comment]
Actually, it would be interesting to get an opinion on the relative merits of configuring the view to emit the whole document, versus emitting nothing and using the id array to bulk retrieve the result set documents.

**Comment by snej** [comment]
The view support is just a passthru, really. If Couchbase Server doesn't support include_docs, I don't see a reason that SG should try to add its own implementation.

**Comment by stemail23** [comment]
Given that current behaviour raises errors, or returns erroneous result set, I would suggest stripping out the include_docs parameter if you're not intending to support it.

**Comment by adamcfraser** [comment]
Agree with the general sentiment (providing more information on unsupported parameters on the request).  Should revisit in the context of the 2.0 API design for query.

**Comment by davengeo** [comment]
I would like to know whether this is going to be solved. Thanks

**Comment by adamcfraser** [comment]
@davengeo What aspect of this are you looking to be solved?  This is really just about providing feedback that a client is requesting unsupported parameters.

**Comment by davengeo** [comment]
In my case the include_docs doesn't work even when I try to fetch them from the admin port (4985). I've made a patch in my client library in order to get the documents one by one and paste them in the response mimicking what couchdb or the walrus db would do. I really think this should be supported by the sync-gateway in the admin port at least.

**Comment by adamcfraser** [comment]
@davengeo As discussed above, this is down to the fact that include_docs isn't a supported view parameter for Couchbase Server 3.0 and higher.

I'd like to better understand your use case, particularly if you're looking for this via the admin port.  With the current functionality, you'd need to execute the view query, then build a bulk_get request based on the response to get the full document bodies.  Adding include_docs processing in Sync Gateway for admin-based views requests would provide a performance advantage (avoiding the additional request/response to issue the bulk_get request), but the expectation is that admin API-based view calls shouldn't be used for performance sensitive operations.

**Comment by davengeo** [comment]
Thanks @adamcfraser, I have developed a middleware around the sync-gateway which is able to give sessions to users and provide them access to the adequate channels, that information is generated from a view of current documents of certain type inside the sync gateway. These documents contain their approved level of access for different stores accross the country. I have made a patch so that I am able to fetch the documents one by one but I am still feeling that this should be solved in the sync gateway instead.

**Comment by fredericgermain** [comment]
@stemail23  on "Actually, it would be interesting to get an opinion on the relative merits of configuring the view to emit the whole document, versus emitting nothing and using the id array to bulk retrieve the result set documents."

I feel it should be discussed too. For what I understood, views are the main way to have your db indexed by some fields in CouchDB. The include_docs is then just a flag to do the lookup in one call, avoiding some round trips. And emitting the whole documents during the mapping would probably lead to some waste of memory.
Couchbase has its own query and indexing, it might be the way to go there, do all the porting on this. But when integrating a software made on couchdb which uses views, I feel the aboved two step lookup is not so optimized.

But I'm maybe wrong somehow.

**Comment by stemail23** [comment]
In the two years since I posted that question, we’ve settled on the bulk fetch from Ids approach. It works, but is still the biggest performance bottleneck in our application, especially for large result sets.

**Comment by adamcfraser** [comment]
Closing based on age, can reopen in JIRA if there's a compelling use case not covered by N1QL.
