### ISSUE TITLE
Tracking CBS 3.0 View query performance

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#697]
Previously ticket #409 was tracking CBS 3.0 compatibility, this removed the requirement to Observe (block until data is persisted to disk) on writing to CBS 3.0

But there is a second issue with view performance when querying  with stale=false in CBS 3.0 as currently tracked here:

https://issues.couchbase.com/browse/MB-12607

The above appears to be the most recent and active ticket 

This ticket has been created to allow us to track progress here

**Comment by melkote** [comment]
Folks, please realize that views in 2.x with 3.x are significantly different. Earlier, it used to go a shared disk and read. Now it goes over a network protocol. In addition, there's a significant cost of finding the latest vbucket sequence numbers using the STATS call.

Some things are much faster, such as the latency between SET and Indexer picking it up. Some things are slower such as query latency. It is unlikely 3.x will match 2.x in all areas - some measures are faster, and some will be slower.

So we need to do a use case review. Basically, in 3.0, stale=false must be used sparingly. We should review the use of it, and see if it is necessary or if it can make do with the faster stale=ok.

**Comment by tleyden** [comment]
Note to self:

Some tangible results -- in [perf run 849](http://ci.sc.couchbase.com/view/sync%20gateway/job/cen006-p0-cbsgw-real-perf/849/) against CBS 3.0.2, I'm seeing the following warnings in the Sync Gw logs:

```
2015/03/27 15:39:55 go-couchbase: call to ViewCustom("sync_gateway", "role_access") in 
github.com/couchbase/sync_gateway/db.(*DatabaseContext).ComputeRolesForUser took 15.015518796s
```

repeated many times.

**Comment by tleyden** [comment]
Todo: post run results from 3.0.3 toy build

**Comment by adamcfraser** [comment]
We need to sanity test that changing user creation to do an indexable write/stale=false view actually performs better in 3.x than in 2.5 (for the combined operations).

**Comment by adamcfraser** [comment]
Reviewed our use of stale=false in access and role_access view in more details - here are the notes previously shared with Zack"

I dug deeper into the stale=false view calls that we make during user creation, and I don't actually think that we're doing something "wrong" in the way we do our writes.  Previously we thought there was a scenario where we weren't doing persistTo/indexable writes (where we should have been).  I don't think that's actually the case.

The stale=false queries we're making during user creation are doing access and role_access lookups based on documents that ARE being written with indexable=true.  

We're performing two stale=false view queries during user creation:
querying the 'access' view, to find the set of channels that have been granted to the user by documents
querying the 'role_access' view, to find the set of roles that have been granted to the user by documents
The key point is that channels and roles may have been assigned to a user before the user record is actually created.   We need to use stale=false here, because in real world cases we don't know whether there's a concurrent document write happening that's assigning access/role_access to the user.  In fact that's probably a common scenario for app developers – creating a user and assigning them channels in the same push replication window.

For any potential writes that are granting access/role access, we ARE writing with Indexable=true.  So we do not have an incorrect scenario where we're doing a non-indexable write, and then making a stale=false call.

Per Cihan, the changes in indexable/stale=false in 3.0 are:
- Indexable is faster
- stale=false is slower
  with an overall improvement for the combination of 1 and 2.  

What that means for us is that we'll see a performance improvement for our indexable document writes (i.e. when writing docs that trigger access/role_access changes via the sync function), but performance degradation when we recalculate the channels/roles for a user.  This recalculation happens in two scenarios:
1. When creating a new user
2. The next time the user replicates, after a doc has made an access change.  (Specifically – when a doc makes an access change, we zero out the channels/roles on the user document.  When we load a user with zeroed channels/roles, we perform the view query.)

Whether we end up with a net performance gain or loss in 3.x probably depends on the developer's use case: 
- If you're not doing any channel/role assignment in the sync function, it's a net loss – the hit during user creation (gateload!)
- If you're doing infrequent channel/role assignment in the sync function, it's probably neutral (slower user creation, faster indexable writes, slower refresh of user access/roles)
- If you're doing frequent channel/role assignment, it should be a net performance gain (slower user creation, many faster indexable writers, many slower refresh of user access/roles)

I think our plan for 3.x should probably look something like:
1. Provide an option for user creation that performs a stale=ok query instead of stale=false.  This could be part of a bulk user creation API.  We'd need to document the caveat that this shouldn't be run in parallel with doc updates that grant channel/role access to those users.  
2. Consider an enhancement to the way we zero out user records to allow us to use stale=ok queries instead of stale=false.  Instead of just clearing out channels/roles to trigger recalculation, we could also include information about the revision making the change, and then validate whether that revision is included in the view result set.

**Comment by adamcfraser** [comment]
This has been backported to 3.0.5 and verified (https://issues.couchbase.com/browse/MB-14904).
