### ISSUE TITLE
feed=channels mode on changes feed

### ISSUE THREAD

**Issue by jchris** [couchbase/sync_gateway#712]
This would be one way to implement an API to let clients know which channels have changed since they last connected.

See https://github.com/couchbase/couchbase-lite-ios/issues/619 for a description of the use case to support.

I guess the result would be a list of channels that have changed since the since parameter, maybe with seqids that go with them.

**Comment by jchris** [comment]
Here is an initial implementation. https://github.com/couchbase/sync_gateway/tree/feature/issue_712

**Comment by jchris** [comment]
@adamcfraser I wonder if you think there is any sense in refactoring `generateContinuousChanges` to take a render function also, to handle [the reducer that I implemented here.](https://github.com/couchbase/sync_gateway/blob/53d7fdff050cfb4839c0a03e52c9ed2847bcfc87/src/github.com/couchbase/sync_gateway/rest/changes_api.go#L209) so it doesn't have to be implemented N times if we need to bring this feature to other transports.

**Comment by adamcfraser** [comment]
@jchris I feel like it wouldn't be much work to write a more efficient version of this, that just checks the state of the channel cache(s), instead of retrieving all the values from 'since' and then running the `wroteChannelNames` reduce on them.  This would be especially true when the since value provided is older than the channel cache's `validFrom` - in that case you'd be triggering a view-based backfill of the channel cache that you don't need.

I guess the exception would be if we've got specific use cases for other reduce-style operations, but it feels to me that we'd want this particular operation to be as lightweight as possible, given the use case from couchbase/couchbase-lite-ios#619

**Comment by jchris** [comment]
Is there a facade API for interrogating the channel caches across all implementations? Can you point to a link of vaguely related code? I can probably figure it out from there.

**Comment by adamcfraser** [comment]
changeCache and channelCache have been refactored to more of a facade API on the distributed_index branch, but that hasn't made it to master yet. 

My take would be to add changeCache.HasChanges(channelName, options) to changeCache, and then call into a new channelCache.HasChanges(options).  When we merge down distributed_index, we can do the work to make that part of the facade API, and implement for the bucket-based index.

The basic case for channelCache.HasChanges would be just to compare the last entry in c.logs with your since value.

The tricky bit for channelCache.HasChanges would be for the case where the c.logs is empty (i.e. there hasn't been activity on the channel since SG started).  At that point you'd need to check validFrom to determine whether you backfill from the view.

**Comment by jchris** [comment]
Thanks, from here's its just a simple matter of coding. :)

**Comment by adamcfraser** [comment]
Closing based on age, can reopen in JIRA if there's a compelling use case.
