### ISSUE TITLE
Perfrunner enhancement to support distributed cache bucket

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#734]

**Comment by tleyden** [comment]
- Additional bucket
- Needs config for memcached vs couchbase bucket

RAM size of bucket: same size as current bucket.  Will tune later.
Couchbase bucket: 1 replica

**Comment by tleyden** [comment]
In order to use this:
- When kicking off a build, use test_config: gateload_twobucket.test.  This will cause it to create two identical buckets in Couchbase server: **bucket-1** and **bucket-2**.  
- Use a custom Sync Gateway config.  The first bucket (bucket-1) can be referenced via `{{bucket}}`, as in [this example](https://gist.githubusercontent.com/tleyden/3696a6d5f507df8e7e7c/raw/6b9caa87fafe41b8c86d8cc46192695f6e6bdf7e/gistfile1.txt#), but the second bucket (bucket-2) will need to be hardcoded in the config.

**Comment by tleyden** [comment]
Example perf run: [perf run 839](http://ci.sc.couchbase.com/view/sync%20gateway/job/cen006-p0-cbsgw-real-perf/839/)

**Comment by tleyden** [comment]
For instructions on how to use a custom sync gw config, see https://github.com/couchbase/sync_gateway/issues/632#issuecomment-86253231
