### ISSUE TITLE
Perfrunner changes to support cache testing

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#735]
We want to be able to test the following configuration in the perf testing environment:

2 CBS nodes
3 SG nodes - one configured as cache writer, two as cache readers
2 Gateload nodes, targeting the cache readers

**Comment by tleyden** [comment]
This has been pushed to my fork in https://github.com/tleyden/perfrunner/commit/1d191d4c160cfd0e4d9c19e2f72fe13b5e0e4cee and is ready for testing on the perf cluster.

Documentation:

To make the first node a cache writer, use:

```
gateway.node0_cache_writer.true
```

to make the second or third node a cache writer, use:

```
gateway.node1_cache_writer.true
gateway.node2_cache_writer.true
```

Note: Only supports up to **three** sync gateway nodes.  You can also make all nodes cache writers by setting all to true.

Example perf run: http://ci.sc.couchbase.com/view/sync%20gateway/job/cen006-p0-cbsgw-real-perf/843/

Leaving the ticket open since I still need to open a Gerrit change request.

**Comment by tleyden** [comment]
Done, just waiting for gerrit review from @andreibaranouski 

http://review.couchbase.org/#/c/48948/
