### ISSUE TITLE
Multimaster replication

### ISSUE THREAD

**Issue by kroese** [couchbase/sync_gateway#757]
I have figured out how to do two-way replication. But suppose I have 10 masters and I want to make sure that every master holds all documents, how would I set that up so I waste the least amount of bandwidth?

Would I split those 10 in 5 pairs, and let those 5 do two-way replication? And would it be best to always form the same pairs, or should I randomly switch peers?

**Comment by ajres** [comment]
@Kroese 

Are you wanting each server to be a master, or is there one master and the others are read only replications?

Andy

**Comment by kroese** [comment]
I have 10 masters that need to sync. And I would like to add read-only replicators to the masters later on, but that shouldnt be the hard part.

**Comment by ajres** [comment]
@Kroese 

If the servers are collocated then you would be better creating a 10 server Couchbase Server cluster with document replication for redundancy.

If the servers(clusters) are remote from each other, then the potential options are to replicate at the Couchbase Server level using XDCR (see caveats below, this probably won't work for your case), or use sg-replicate at the Sync Gateway level.

@tleyden gave this description on another ticket.

"The only safe way to use XDCR is if you have a single master Couchbase Cluster + Sync Gateway that accepts writes, and all of your other CBCluster + Sgw are read-only.  (Sync Gateway doesn't currently have a read-only mode to my knowledge, not sure about Couchbase Server).  Otherwise, since XDCR is not aware of the _sync metadata field in the documents, it will essentially corrupt documents.  

Having said that, we've done zero testing of XDCR + Sync Gateway in-house so far, so you'd be in unchartered territory.

Another option is to try sg-replicate, which uses the ReST replication protocol to sync between Sync Gateways in an eventually consistent fashion.  You would be able to have all your Couchbase Clusters + Sync Gateways accept writes, but:
- They would be eventually consistent -- there will be a delay when docs make it from one cluster to the other.
- You might end up with document conflicts.  Sync Gateway is architected to handle these gracefully, so they won't cause any issues, but there will be more work on your part to handle these conflicts in your application.

sg-replicate is still fairly alpha / POC, but has undergone some real world dogfood testing and seemed to work fine.  Since most of the work is handled on the Sync Gateway side, it's a fairly simple tool that just shuttles documents back and forth."

As the sync protocol supports master-master replication, you can sync between any pair of Sync Gateway instances.

There is no need to spit the 10 servers into pairs, you can replicate between any two instances and as long as there is a replication path between all the instances they will eventually become consistent.

Using four servers as an example:

S1 <-- REPLICATE --> S2 | S2 <-- REPLICATE --> S3 | S3 <-- REPLICATE --> S4

Or pick a different topology with some redundancy so that if one server goes down replication can still take place between the other nodes.

S1 <-- REPLICATE --> S3 | S3 <-- REPLICATE --> S4 | S4 <-- REPLICATE --> S2 | S2 <-- REPLICATE --> S1

You can add more redundant replications links, at the expense of some additional network traffic. The sync protocol will not replicate doc revisions that have already been sync'd over a different link.

Andy

**Comment by kroese** [comment]
@ajres I think sg-replicate would be the best. The 10 masters are not co-located. 

I was considering a different solution: Just store my data in plain text format, and use 'Git Bundles' to create small packets which contain delta differential patches, and just let masters exchange these bundles amongst themselves. 

Now, is there anything that Couchbase/Sync gateways could improve on the above scheme. The bandwidth used? The efficiency of the syncing? Because Id like to use CouchDB, but Git's way of syncing seems much simpeler for my use-case?

EDIT: Actually, your 'sg-replicate' proposal is pretty simple too. But it makes a strict disctinction between  'Sync Gateway' instances, and normal masters. And I like every member of the network to be able to sync without that third party. Is there anything against making every master also a sync gateway?

**Comment by tleyden** [comment]
> I was considering a different solution: Just store my data in plain text format, and use 'Git Bundles' to create small packets which contain delta differential patches, and just let masters exchange these bundles amongst themselves.

That sounds like a _really_ deep rabbit hole.

>  And I like every member of the network to be able to sync without that third party. 

Eventually the plan is that sg-replicate will get fused into Sync Gateway (which should be relatively easy, since they are both written in Go).  In the meantime, you can just run an sg-replicate instance next to Sync Gateway on the same box, and then configure your replication topology as @ajres described it above.

**Comment by kroese** [comment]
> That sounds like a really deep rabbit hole.

Could be, but still I like the concept of those 'bundles', it would nice to have something like that in CouchBase too. Because it allows for easy offline syncing for machines that are airgapped or on different networks. 

> Eventually the plan is that sg-replicate will get fused into Sync Gateway 

I didnt mean to fuse those, but why is Sync Gateway a different product from CouchBase? For example, every MySQL install contains 'mysqldump' to import/export database. I'm trying to understand why sync_gateway is a seperate application.

**Comment by tleyden** [comment]
> Because it allows for easy offline syncing for machines that are airgapped or on different networks.

Why do I get the distinct feeling there are BTC involved here? :D 

> but why doesnt every master is a sync gateway?

When you say "master", are you referring to Couchbase Server?  Not really sure what you mean by master here.

**Comment by kroese** [comment]
> Why do I get the distinct feeling there are BTC involved here?

You are not bad at guessing.

> When you say "master", are you referring to Couchbase Server? 

Yes, I am. I'm just trying to figure out how to deploy it. It seems very Client --> Server based, where you have a few servers, and thousands of light-clients. But I am looking for a way to eliminate those gateway-servers, and let the peers sync amonst themselves. Just like in Bitcoin, where each peer holds a full copy of the chain, and propagates chunks arounds it peers.

It should be easy to setup, since Cloudbase is focussed around syncing. But when I have two Android-devices who can reach eachother, why should there be a need for a third party mediating for them?

**Comment by tleyden** [comment]
> thousands of light-clients

Where are these running?  On mobile / desktop?

**Comment by tleyden** [comment]
PS: feel free to hop in our [gitter chat room](https://gitter.im/couchbase/mobile)

**Comment by tleyden** [comment]
This seems more like a question than an issue, so I'll close it.
