### ISSUE TITLE
Inventory needed Gatling scenarios

### ISSUE THREAD

**Issue by zgramana** [couchbase/sync_gateway#816]

**Comment by ajres** [comment]
Test coverage identified as being needed in Gatling performance scenarios

Already have
- [ ] 9. Continuous replication (already have) 
- [ ] 11. Channel grants in sync function (already have)

Tier 1
- [ ] 1. Access grants (users getting granted channel access by a doc, role grants)
  - [ ] 1b. Include access removal in subsequent revisions?
  - [ ] 1c. Have roles as a V2 enhancement to the scenario?
- [ ] 5. Document CRUD (not just inserts)
  - [ ] 5b. Large revision trees
  - [ ] 5c. Conflicting updates
  - [ ] 5d. Document delete
        - would need a lever for insert/update/delete distribution
  - [ ] 5e. Single doc vs. bulk docs, single get vs bulk get
- [ ] 8. Longpoll replication
- [ ] 10. Intermittent ad-hoc sync (not continuous or longpoll)
      - particularly where since=older than channel cache, triggering view backfill
- [ ] 18. Kitchen-sink scenario (todolite?)

Tier 2
- [ ] 2. Computationally expensive sync function (performance of js interpreter)
- [ ] 4. Sync function rejecting documents (requireUser() handling) 
- [ ] 13. Resync
- [ ] 14. Pass-through views
- [ ] 15. Creating users and roles mid-test, instead of front-loading
- [ ] 16. SG-replicate
- [ ] 17. Bucket shadowing (if we get to it before it's deprecated)

General levers/settings for tests
- [ ]  modify SG config file
- [ ] doc size
- [ ]  attachments on/off, attachment size
- [ ]  number of channels
- [ ]  distribution of docs in channels
- [ ]  writes/seconds/user
- [x] pusher/puller distribution
- [ ] websockets enabled (for appropriate calls)

**Comment by ajres** [comment]
Generated new tickets for tracking Tier 1 scenario coverage

**Comment by ajres** [comment]
Moved this list to wiki [page](https://github.com/couchbase/sync_gateway/wiki/Additional-gatling-performance-scenarios) for long term tracking.

Closing out this ticket.
