### ISSUE TITLE
AWS perfcluster: collect Gatling stats and push to Splunk

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#886]
@ajres we need to collect Gatling stats and get them pushed into Splunk.  Can you spec out the formats and mechanism for getting stats out of Gatling?  

We'll go from there, possibly re-assigning to @andreibaranouski for the implementation.

**Comment by zgramana** [comment]
@ajres is currently assigned to document some information for knowledge transfer to Andrei.

**Comment by ajres** [comment]
On a gatling client node which has been installed via the perfcluster-aws ansible scripts.

The base gatling directory is:

```
/home/projects/sg-gatling-load
```

Gatling writes all collected stats to a file called simulation.log, on each run the a numbered directory is created.

**Comment by tleyden** [comment]
@andreibaranouski can you add configuration to monitor the /home/projects/sg-gatling-load directory with the splunk forwarder?

**Comment by zgramana** [comment]
@ andreibaranouski please provide an update.

**Comment by andreibaranouski** [comment]
please check implementation
note:
I had to create a workaround because sg-gatling-load generates logs with random folder name, like /home/projects/sg-gatling-load/themes/gateload-sim/target/gatling/results/createuseraccountssimulation-1434825818403/simulation.log
Since splunk can not monitor a folder that does not yet exist( or recreate it in the next steps), I first had to create the folder
/home/projects/sg-gatling-load/themes/gateload-sim/target/gatling/results and monitor it(configure-gatling.yml)
and then I should clone sg-gatling-load not to recreate "themes" folder again( configure-gatling.yml)
