### ISSUE TITLE
Document Sync Gateway config properties

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#905]
As followup to #902 - we have a number of Sync Gateway config properties, including the new CouchbaseKeepaliveInterval - that are available, but are only documented via code comments:

ServerConfig:
https://github.com/couchbase/sync_gateway/blob/master/src/github.com/couchbase/sync_gateway/rest/config.go#L49

DbConfig:
https://github.com/couchbase/sync_gateway/blob/master/src/github.com/couchbase/sync_gateway/rest/config.go#L78

These should be reviewed for inclusion in the official docs.

**Comment by JeffThomasWriter** [comment]
I started to work on this, and sent Adam some questions. He answered some. Here is the list:
Adam,

A few questions (and notes):

Notes:

I envision keeping the current structure and content, more or less, and adding sections at the end equivalent to the CORS Configuration section for the other types of configuration. Do I omit shadow bucket configuration, for the moment? The list could be: Server, Database, Authentication (Persona and Facebook), CORS, Event handling (Webhooks), and Cache configuration.
[Adam] That sounds ok.  Once you get the content ready, we can assess whether it seems like the page is getting too large, and potentially create a new 'file-based config' page (that would include the CORS configuration).  I guess we do want to leave Shadow bucket out for now.  For the structure of each individual section – I like the example JSON included in the CORS configuration, but think it would benefit from a table to show the various properties.  
It makes sense to me to add Type to the tables, so, Option, Type, Default, Description. I wonder if the table width is a problem. I could put Type and Default in one column.
[Adam] I don't know if type is strictly needed, but it wouldn't hurt if it fits.

Questions:

The things one specifies on the command line, and in the config file, are variously called options (not a good choice, because some are not optional), settings, and parameters. Any thoughts on the best term? [Adam] I think 'property' is the standard terminology within JSON, so that makes the most sense for the config file.  'parameter' is probably appropriate when talking about the command line.  
Do the JSON structs, for example, for the DB config, constrain the key-value pairs or other structs in the struct to a specific order? The order appears to be “logical, and well we added stuff here and there.” Logical order works well for few items. For many, alphabetical can work better. Can we change the order in go.config, or is that a breaking schema change? (I could just alphabetize the items in the documentation; or match the order. For the command-line parser, a similar question: can I change the order in the file go.config, or perhaps just in the documentation? What are your thoughts on the logical versus alphabetical order? [Adam] There's no ordering constraint.  I don't think we'd bother changing the order in go.config, but you can order them however you think is appropriate in the documentation.
Am I correct that parameters not listed in ParseCommandLine cannot be specified on the command line? [Adam] As far as I know, but I haven't done much testing of command-line parameters.
Here are some questions about specific parameters. Perhaps I would have fewer if the sample files contained more.

For Interface and AdminInterface, if only the port is specified, what host is used? (I do see that the default for AdminInterface includes the IP address for localhost. I am asking about what you get when you specify the port and do not include the hostname.)
[Adam] The IP of the machine Sync Gateway is running on.  The significance of 'localhost' for the default AdminInterface is that localhost ensures the admin API port isn't available non-locally.  
Does it matter that our default ports are not registered to us with IANA? (They are registered, but to others.) I guess that behind a firewall, one can do pretty much anything with ports, as long as they do not conflict.
[Adam] No.
Apparently, you can specify the host as an IP address. Can you use a FQDN that a DNS would interpret? When would you want to specify the host?
For SSLCert and SSLKey, what is the path (on local filesystem? Absolute or relative? URI?). In AdminUI, the same question about the path.
What does ProfileInterface do? Is this also a port, and possibly a domain+host name?
What is ConfigServer?
Regarding Log, what are “log keywords,” and what does enabling them do?
Re LogFilePath, the same path questions as above.
For StatsReportInterval, what are the units?
For MaxCouchbaseConnections, MaxCouchbaseOverflow, and MaxIncomingConnections, it looks like 0 means no maximum. True?
For MaxFileDescriptors, can you use 0?
What are the units for CouchbaseKeepAliveInterval?
For SlowServerCallWarningThreshold, what constitutes a “database call”? Is this the time between a request from SG to CBS and a response?
What does MaxHeartbeat do?
In DbConfig, what is ImportDocs?
For CORSConfig MaxAge, what are the units and can 0 be used?
For EventHandlerConfig MaxEventProc, can 0 be used?
For EventHandlerConfig WaitForProcess, can 0 be used?
For EventConfig Timeout, what are the units?
For CacheConfig CachePendingSeqMaxWait, what are the units and can 0 be used?
For CacheConfig CachePendingSeqMaxNum, can 0 be used?
For CacheConfig CacheSkippedSeqMaxWait, what are the units and can 0 be used?
Regarding command-line parameters:

In what sense is personaOrigin “Base URL”? The server being connected to here is the Persona server, I imagine.
For the addresses, are these URLs including the port numbers?
Same question about log keys as above, and about the log file path.
I can probably dig around in the file and in the docs and answer some of these myself. But this is the list.

**Comment by adamcfraser** [comment]
A few questions (and notes):

Notes:
1. I envision keeping the current structure and content, more or less, and adding sections at the end equivalent to the CORS Configuration section for the other types of configuration. Do I omit shadow bucket configuration, for the moment? The list could be: Server, Database, Authentication (Persona and Facebook), CORS, Event handling (Webhooks), and Cache configuration.
   [Adam] That sounds ok.  Once you get the content ready, we can assess whether it seems like the page is getting too large, and potentially create a new 'file-based config' page (that would include the CORS configuration).  I guess we do want to leave Shadow bucket out for now.  For the structure of each individual section – I like the example JSON included in the CORS configuration, but think it would benefit from a table to show the various properties.  
2. It makes sense to me to add Type to the tables, so, Option, Type, Default, Description. I wonder if the table width is a problem. I could put Type and Default in one column.
   [Adam] I don't know if type is strictly needed, but it wouldn't hurt if it fits.

Questions:
1. The things one specifies on the command line, and in the config file, are variously called options (not a good choice, because some are not optional), settings, and parameters. Any thoughts on the best term? [Adam] I think 'property' is the standard terminology within JSON, so that makes the most sense for the config file.  'parameter' is probably appropriate when talking about the command line.  
2. Do the JSON structs, for example, for the DB config, constrain the key-value pairs or other structs in the struct to a specific order? The order appears to be “logical, and well we added stuff here and there.” Logical order works well for few items. For many, alphabetical can work better. Can we change the order in go.config, or is that a breaking schema change? (I could just alphabetize the items in the documentation; or match the order. For the command-line parser, a similar question: can I change the order in the file go.config, or perhaps just in the documentation? What are your thoughts on the logical versus alphabetical order? [Adam] There's no ordering constraint.  I don't think we'd bother changing the order in go.config, but you can order them however you think is appropriate in the documentation.
3. Am I correct that parameters not listed in ParseCommandLine cannot be specified on the command line? [Adam] As far as I know, but I haven't done much testing of command-line parameters.
   Here are some questions about specific parameters. Perhaps I would have fewer if the sample files contained more.
4. For Interface and AdminInterface, if only the port is specified, what host is used? (I do see that the default for AdminInterface includes the IP address for localhost. I am asking about what you get when you specify the port and do not include the hostname.)
   [Adam] The IP of the machine Sync Gateway is running on.  The significance of 'localhost' for the default AdminInterface is that localhost ensures the admin API port isn't available non-locally.   
5. Does it matter that our default ports are not registered to us with IANA? (They are registered, but to others.) I guess that behind a firewall, one can do pretty much anything with ports, as long as they do not conflict.
   [Adam] No.
6. Apparently, you can specify the host as an IP address. Can you use a FQDN that a DNS would interpret? When would you want to specify the host?
   [Adam] You mean as part of Interface/AdminInterface?  SG isn't going to be able to bind to anything that doesn't resolve to the machine where it's running, I don't think.  So I think localhost is the only meaningful host definition you might include.
   4.For SSLCert and SSLKey, what is the path (on local filesystem? Absolute or relative? URI?). In AdminUI, the same question about the path.
   [Adam] Relative or absolute path on file system, see https://github.com/couchbase/sync_gateway/tree/master/examples/ssl for more details. 
7. What does ProfileInterface do? Is this also a port, and possibly a domain+host name?
   [Adam] It's the port for the diagnostic endpoint, to get go profiling information.  
8. What is ConfigServer?
   [Adam] It allows SG nodes to load db configs dynamically from a remote endpoint.  If a config server is defined – when SG gets a request for a database that it doesn't know about, it will try to retrieve the config for that DB from [ConfigServer]/[dbname]
9. Regarding Log, what are “log keywords,” and what does enabling them do?
   [Adam] Those are the log keys I added to the other docs ticket you have.  Most diagnostic logging in SG is written to a specific log key, so you can use the log keys to filter to whatever logging you're looking for.
10. Re LogFilePath, the same path questions as above.
    [Adam] Same as above
11. For StatsReportInterval, what are the units?
    [Adam] Seconds
12. For MaxCouchbaseConnections, MaxCouchbaseOverflow, and MaxIncomingConnections, it looks like 0 means no maximum. True?
    [Adam] Setting MaxCouchbaseConnections to zero will end up reverting to the default used by go-couchbase (which I think is 64).  We have competing defaults at that point – between Sync Gateway's default of 16 and go-couchbase's 64.  It's probably not particularly meaningful for users to set MaxCouchbaseConnections to 0.  Similar for MaxCouchbaseOverflow.  For MaxIncomingConnections, the default is zero, so setting a value of 0 won't change anything, but you're right that it means no maximum on connections.
13. For MaxFileDescriptors, can you use 0?
    [Adam] I don't think we guard against it, but it's a bad idea.  I think you could lose the ability to interact with your host – even over ssh.
14. What are the units for CouchbaseKeepAliveInterval?
    [Adam] Seconds
15. For SlowServerCallWarningThreshold, what constitutes a “database call”? Is this the time between a request from SG to CBS and a response?
    [Adam] Right – the time for a request from SG to CBS to respond.  
16. What does MaxHeartbeat do?
    [Adam]https://github.com/couchbase/sync_gateway/pull/915
17. In DbConfig, what is ImportDocs?
    [Adam] I'm not sure we want to document that.  It was a precursor to bucket shadowing, and might be an 'expert user only' type feature.  See https://github.com/couchbase/sync_gateway/issues/239 for a bit of context.
18. For CORSConfig MaxAge, what are the units and can 0 be used?
    [Adam] Sets the access-control-max-age property, in seconds.  https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS
19. For EventHandlerConfig MaxEventProc, can 0 be used?
    [Adam] Setting zero reverts to the default max (500).
20. For EventHandlerConfig WaitForProcess, can 0 be used?
    [Adam] WaitForProcess=0 is valid – it won't wait for a process (should be details in the webhooks docs)
21. For EventConfig Timeout, what are the units?
    [Adam] Seconds
22. For CacheConfig CachePendingSeqMaxWait, what are the units and can 0 be used?
    [Adam] Milliseconds, no.
23. For CacheConfig CachePendingSeqMaxNum, can 0 be used?
    [Adam] No.
24. For CacheConfig CacheSkippedSeqMaxWait, what are the units and can 0 be used?
    [Adam] Milliseconds, no.
    Regarding command-line parameters:
25. In what sense is personaOrigin “Base URL”? The server being connected to here is the Persona server, I imagine.
    [Adam] Right – see http://developer.couchbase.com/mobile/develop/guides/sync-gateway/administering-sync-gateway/authenticating-users/index.html.
26. For the addresses, are these URLs including the port numbers?
    [Adam] Which addresses?
27. Same question about log keys as above, and about the log file path.
    [Adam] Same as above.

**Comment by JeffThomasWriter** [comment]
Also document issue 881: Either use CL parameters or config file properties, not both.

**Comment by JeffThomasWriter** [comment]
The syntax for starting Sync Gateway currently has [ConfigFile...], but the ... is not explained. Can one use multiple config files? In the event of conflicting contents, does the last one win?

**Comment by adamcfraser** [comment]
It turns out you _can_ specify multiple config files, which was news to me.  It will do a merge of the content, in most cases using 'first one wins' priority.  It's only merging the properties included here:
https://github.com/couchbase/sync_gateway/blob/master/src/github.com/couchbase/sync_gateway/rest/config.go#L272

You can see from that code that in most cases it's only replacing values that were previously nil, with the exception of log flags (get unioned), pretty-printing JSON (forces when true), and databases (does union, throws error for duplicate definition).

**Comment by JeffThomasWriter** [comment]
When it takes half a page to describe what happens, it is often an indication to take a different approach. "Use one config file" works. Or perhaps "use config files that do not duplicate the same sections." For example, I guess you could have a master config file that gave the server and db config, and others as needed for other things like event handling, auth, CORS, etc. Or perhaps separate config files for server and dbconfig. Or would that not work because of the way the merge works. Looking for something I can put in writing...

**Comment by adamcfraser** [comment]
Documenting the single config file scenario is the key goal here.  You can limit the discussion to that.

**Comment by tleyden** [comment]
Jeff, I'm with you on this one.  I would go even so far to suggest that we
deprecate that feature and remove it in 2.0.  (with the possibility of
re-adding it later, in a more requirements driven manner)

**Comment by zgramana** [comment]
Related to https://github.com/couchbase/sync_gateway/issues/905 and https://github.com/couchbase/sync_gateway/issues/881.
