### ISSUE TITLE
Filtered replication of user-defined public channels

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#947]
Sync Gateway doesn't have an ideal way to handle the scenario where there is a large volume of public data (accessible to everyone), but users only want to replicate a subset of that data at a time, on demand.  

The current approach is to assign that data to channels, and have a process to add/remove a user's access to those channels as they request that data.  However, this comes with processing overhead - changing a user's channels is a relatively expensive operation.  It also requires that client replicate data in order to trigger the channel access, which also adds replication overhead.

An alternative would be to allow applications to define custom public channels.  One approach would be to prefix these channels with `!`, which we currently use as the public channel name.  An application could define channels as `!ABC` and `!PBS` with the following behaviour:
- Users would be granted access to any `!`-prefixed channels by default
- The `_changes` feed would only return data for `!`-prefixed channels if the channel was explicitly included in the `channels` query parameter

A potential concern is that this doesn't trigger any removal of previously synchronized documents from the client DB.  e.g If a user requests documents from channel `!ABC`, there isn't an automated process to remove those documents if they specify different public channels in a subsequent replication.  Similarly, clients won't get a `_removed` notification for documents that are later removed from `!ABC` unless they explicitly replicate against `!ABC`.  

However, I don't think either of those two potential concerns are fundamentally different than the current handling when specifying channels during replication.

The key technical challenge on the Sync Gateway side would be to identify and maintain the set of public channels in an efficient way (i.e. without making a view call every time)

**Comment by alex7egli** [comment]
+1
Would be very useful in our case where our users will be logging in and out a lot, generating a lot of historical data we don't need to pull everytime, and they want to be able to sync as quickly as possible.

**Comment by cujo** [comment]
Any news and estimates on this issue? Very useful for us too to sync only top level of hierarchical data and sync other on demaind.

**Comment by jchris** [comment]
I wonder if this isn't just sugar for folks who want to control selection of public channels from the server side. Today clients can control it by requesting channels on their replication objects. 

Registered users could be added to a group, and all "public" channels granted to that group. So then it's just up to the application to publish a directory of public channels, and up to clients to decide what to request.

So I think this `!` shorthand is sugar for something we've got longhand apis for already. That's not to say we shouldn't do it, but for people who are waiting I wanted to outline the current option, and maybe it can inform an implementation.

**Comment by jchris** [comment]
Thinking about it more, I am hesitant to use channel name schemes as a way to set up access, because that's just asking for injection attacks. So maybe we'd sugar it like `public("mychannel")` but underneath it would ensure the `public` role has been granted access to `mychannel`. 

@adamcfraser might have a use case that this pattern doesn't handle, so it's worth more discussion.

**Comment by adamcfraser** [comment]
The use case I was thinking of was:
- User has access to a number of 'private' channels - only accessible to that user, but this set of channels changes over time, and the user wouldn't necessarily know the entire list (e.g. sync function is doing an access grant based on some document/business logic)
- User has access to a large number of 'public' channels - the scenario described above
- User wants to replicate all of their private channels, but only a subset of their public channels

I agree that the "public role w/ published list of channels" is the better way to handle the second item on its own. 

However, it still means that users who want to retrieve everything in the first category need to know the list of 'private' channels they have access to - if they tried to do a unfiltered replication to get the private data, they'd also get the full set of public channel data.

**Comment by alex7egli** [comment]
I'd like to revoke my +1, I didn't realize this ticket did not address our scenario. We wanted to use channels as filters for replicating private data, but this ticket is still only using them for access control and specifically for filtering replicating public data. Since channels are the only way to filter data having the ability to use them as filters for public and private data would be enormously helpful. We currently have some users who have to have access to thousands of channels so that we can do time based channel filtering, but if we had public filter channels then they would only need to access a few hundred channels.

I have opened a separate ticket for the issue of being able to filter public and private documents by public channels: https://github.com/couchbase/sync_gateway/issues/1296

**Comment by darshanDevrai** [comment]
+1

**Comment by adamcfraser** [comment]
Closing based on age, can reopen in JIRA if there's a compelling use case.
