### ISSUE TITLE
SG as a service is not supported on Windows

### ISSUE THREAD

**Issue by andreibaranouski** [couchbase/sync_gateway#948]
believe that we need to have the same functionality on all supported platforms

for linux:
https://github.com/couchbase/sync_gateway/tree/master/service

**Comment by zgramana** [comment]
The issue is unique to Windows. On *nix platforms, the best practice is to write a "foreground" executable and rely on service managers to handle the rest.

On Windows, however, a service must respond to messages and thus cannot so easily rely on tooling for this. One option is to create a custom service wrapper that starts/stops the current SG executable as a child process. I'm currently writing a sample service to test the idea.
