### ISSUE TITLE
Panic if Origin header sent in request with no SG config

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#991]
Panic if Origin header sent in public _session POST request without CORS configuration being set on SG.

From this thread:
https://forums.couchbase.com/t/post-db--session-doesnt-check-password/4523

```
net/http.func·011()
        /usr/local/go/src/net/http/server.go:1130 +0xbb
github.com/couchbase/sync_gateway/rest.(*handler).handleSessionPOST(0xc20805ea20, 0x0, 0x0)
        /home/couchbase/jenkins/workspace/sync-gateway-unix-builds/release/1.1.0/community/app-under-test/sync_gateway/src/github.com/couchbase/sync_gateway/rest/session_api.go:43 +0x35d
github.com/couchbase/sync_gateway/rest.(*handler).invoke(0xc20805ea20, 0xd8c750, 0x0, 0x0)
        /home/couchbase/jenkins/workspace/sync-gateway-unix-builds/release/1.1.0/community/app-under-test/sync_gateway/src/github.com/couchbase/sync_gateway/rest/handler.go:159 +0x4b8
github.com/couchbase/sync_gateway/rest.func·015(0x7fb122f0f448, 0xc20827bd60, 0xc2081c4820)
        /home/couchbase/jenkins/workspace/sync-gateway-unix-builds/release/1.1.0/community/app-under-test/sync_gateway/src/github.com/couchbase/sync_gateway/rest/handler.go:86 +0x7d
net/http.HandlerFunc.ServeHTTP(0xc2080d0b00, 0x7fb122f0f448, 0xc20827bd60, 0xc2081c4820)
        /usr/local/go/src/net/http/server.go:1265 +0x41
github.com/gorilla/mux.(*Router).ServeHTTP(0xc20803b5e0, 0x7fb122f0f448, 0xc20827bd60, 0xc2081c4820)
        /home/couchbase/jenkins/workspace/sync-gateway-unix-builds/release/1.1.0/community/app-under-test/sync_gateway/src/github.com/gorilla/mux/mux.go:86 +0x29e
github.com/couchbase/sync_gateway/rest.func·017(0x7fb122f0f448, 0xc20827bd60, 0xc2081c4820)
        /home/couchbase/jenkins/workspace/sync-gateway-unix-builds/release/1.1.0/community/app-under-test/sync_gateway/src/github.com/couchbase/sync_gateway/rest/routing.go:236 +0x32f
net/http.HandlerFunc.ServeHTTP(0xc208136b00, 0x7fb122f0f448, 0xc20827bd60, 0xc2081c4820)
        /usr/local/go/src/net/http/server.go:1265 +0x41
net/http.serverHandler.ServeHTTP(0xc20825d080, 0x7fb122f0f448, 0xc20827bd60, 0xc2081c4820)
        /usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc20827bcc0)
        /usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:1751 +0x35e
```

**Comment by dbergan** [comment]
Ok, call me weird, but I'd rather use an app to make REST calls rather than curl.  In the Chrome Web Store, we have some pretty good options for this:

[Postman](https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop)
[Advanced REST client](https://chrome.google.com/webstore/detail/advanced-rest-client/hgmloofddffdnphfgcellkdfbfbjeloo)
[DHC REST/HTTP API Client](https://chrome.google.com/webstore/detail/dhc-resthttp-api-client/aejoelaoggembcahagimdiliamlcdmfm)
[Insomnia](https://chrome.google.com/webstore/detail/insomnia-rest-client/gmodihnfibbjdecbanmpmbmeffnmloel)

All of them fumble on POST /{dbname}/_session because apparently it's Google's policy that these apps MUST include an Origin header (or the chrome browser does it automatically or something).

For the rest of my REST calls, they work fine.  But _session doesn't even give a response when it gets an Origin header.  Some kind of error response would be preferred to just dead silence (and having to look it up on the sync gateway console).

But best of all, would be to make it such that these apps **_could**_ POST /{dbname}/_session... some kind of workaround for the whole Origin header issue.

**Another function that also has this problem...**
`/{dbname}/_facebook`

Kind regards,
David
